Repository ethereum/EIPs, pull requests merged in 2018-04, with the labels that each got.

#646 eip-615: initialize current_sub variable
  EIPS/eip-615.md
Labels: EVM

#689 Address Collision of Contract Address Causes Exceptional Halt
  EIPS/eip-689.md
Labels: EIP

#627 Draft EIP: Whisper packet codes spec
  EIPS/eip-627.md
Labels: wire protocol

#867 Standardized Ethereum Recovery Proposals (ERPs)
  EIPS/eip-867.md
Labels: meta

#210 Create blockhash_refactoring.md
  EIPS/eip-210.md
Labels: EIP, follow-up-with-author

#1013 Constantinople EIP
  EIPS/eip-1013.md
Labels: EIP, meta

#897 ERC DelegateProxy
  EIPS/eip-897.md
Labels: ERC

#902 Token Validation
  EIPS/eip-902.md
Labels: ERC

#918 ERC 918 - Mineable Token Standard
  EIPS/eip-918.md
Labels: ERC

#823 EIP: Token Exchange Standard for ERC20 tokens
  EIPS/eip-823.md
  EIPS/token-exchange-standard-visual-representation-1.PNG
  EIPS/token-exchange-standard-visual-representation-2.PNG
Labels: ERC, PR-created
