Repository ethereum/EIPs, pull requests merged in 2019-12, with the labels that each got.

#2020 EIP-2020: E-Money Standard Token
  EIPS/eip-2020.md
Labels: type: ERC

#2371 Fix citation formats [R4R]
  EIPS/eip-1056.md
  EIPS/eip-1155.md
  EIPS/eip-1261.md
  EIPS/eip-1276.md
  EIPS/eip-137.md
  EIPS/eip-1462.md
  EIPS/eip-1484.md
  EIPS/eip-162.md
  EIPS/eip-1812.md
  EIPS/eip-190.md
Labels: maintenance/editing

#2417 Rename PNGs to lowercase extension in EIP-823
  EIPS/eip-823.md
  assets/eip-823/eip-823-token-exchange-standard-visual-representation-1.png
  assets/eip-823/eip-823-token-exchange-standard-visual-representation-2.png
Labels: maintenance/editing

#2335 Draft EIP: BLS12-381 Keystore
  EIPS/eip-2335.md
Labels: type: ERC

#2385 EIP-634: Add peepeth and made it more DRY
  EIPS/eip-634.md
Labels: waiting: approval/rejection

#1086 correct a sentence semantically, and a spelling mistake
  EIPS/eip-1080.md
Labels: waiting: approval/rejection

#2410 Mark all Istanbul EIPs are Final
  EIPS/eip-1108.md
  EIPS/eip-152.md
  EIPS/eip-1679.md
  EIPS/eip-1884.md
  EIPS/eip-2028.md
  EIPS/eip-2200.md
Labels: maintenance/editing

#1866 Support MathJax
  _includes/head.html
Labels: type: Meta, waiting: approval/rejection

#2254 EIP-1155: Rename backwards compatibility section to "Backwards compatibility"
  EIPS/eip-1155.md
Labels: waiting: approval/rejection

#2416 Small link fixes to EIP-8, EIP-778, EIP-868, EIP-1459
  EIPS/eip-1459.md
  EIPS/eip-778.md
  EIPS/eip-8.md
  EIPS/eip-868.md
Labels: maintenance/editing

#2098 Compact Signature Representation
  EIPS/eip-2098.md
Labels: type: Informational, waiting: clarifications from author

#2400 ERC: URL Format for Transaction Receipts
  EIPS/eip-2400.md
Labels: type: ERC

#1963 Adding mandatory "Security Considerations" to EIP-1
  EIPS/eip-1.md
  eip-template.md
Labels: type: EIP1 (Process), type: Meta
