Repository ethereum/EIPs, pull requests merged in 2019-08, with the labels that each got.

#2124 EIP 2124: Fork identifier for chain compatibility checks
  EIPS/eip-2124.md
Labels: type: Networking

#2059 Fix Markdown rendering within summary/detail
  .gitignore
  .travis.yml
  EIPS/eip-1057.md
  EIPS/eip-1102.md
  EIPS/eip-1123.md
  EIPS/eip-1474.md
  EIPS/eip-1484.md
  EIPS/eip-1620.md
  EIPS/eip-1775.md
  EIPS/eip-1812.md
  Gemfile
  Gemfile.lock
  _config.yml
Labels: type: Meta

#2129 EIP-152: Blake2b `F` precompile
  EIPS/eip-152.md
Labels: type: Core
