Repository ethereum/EIPs, pull requests merged in 2019-07, with the labels that each got.

#2160 Mark EIP-158 properly: superseded and not replaced
  EIPS/eip-158.md
Labels: meta

#2161 Update eip_validator to 0.8.2
  EIPS/eip-1186.md
  Gemfile
  Gemfile.lock
Labels: meta

#2159 Add information EIP: Common Prometheus metrics
  EIPS/eip-2159.md
Labels: ERC

#1753 EIP-1753 - Define a smart contract interface for permits and licences
  EIPS/eip-1753.md
Labels: ERC, follow-up-with-author

#1954 EIP-225: mark Clique engine status as final
  EIPS/eip-225.md
Labels: waiting-for-merge-approval

#1549 Change status to 'Final' for eip875
  EIPS/eip-875.md
Labels: follow-up-with-author

#2168 Mark EIP1571 for interface category and not networking
  EIPS/eip-1571.md
Labels: waiting-for-merge-approval

#1901 EIP-1901: Add OpenRPC Service Discovery To JSON-RPC Services
  EIPS/eip-1901.md
  assets/eip-1901/OpenRPC_structure.png
  assets/eip-1901/multi-geth-use-case.png
Labels: follow-up-with-author, type: Interface

#2178 EIP 1102: Loosens the constraints a bit.
  EIPS/eip-1102.md
Labels: waiting-for-merge-approval

#1900 EIP-1900 Decentralized Type System for EVM
  EIPS/eip-1900.md
Labels: type: ERC

#2158 Add ERC - dType Storage Extension - Decentralized Type System for EVM
  EIPS/eip-2157.md
Labels: type: ERC

#1504 ERC-1504 Upgradable Smart Contract (USC)
  EIPS/eip-1504.md
Labels: type: ERC

#1991 Expand EIP Championing Section in EIP-1
  EIPS/eip-1.md
Labels: type: Meta

#2162 Remove Deferred from the status list
  EIPS/eip-1.md
  EIPS/eip-1015.md
  EIPS/eip-3.md
  EIPS/eip-616.md
  README.md
  _data/statuses.yaml
  index.html
Labels: type: Meta

#2193 Add ERC: dType Alias Extension - Decentralized Type System
  EIPS/eip-2193.md
Labels: type: ERC

#2171 Check-In first draft of EIP-2135
  EIPS/eip-2135.md
Labels: type: ERC

#2201 Rename eip-X template to eip-template
  EIPS/eip-1.md
  ISSUE_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  _config.yml
  eip-template.md
  index.html
Labels: type: Meta

#2210 EIP-1056 Ethereum Lightweight Identity implementation
  EIPS/eip-1056.md
Labels: type: ERC

#1994 EIP-1344: Move to Final after Last Call Review
  EIPS/eip-1344.md
Labels: waiting-for-merge-approval
