Repository ethereum/EIPs, pull requests merged in 2019-11, with the labels that each got.

#2234 EIP-1191: Change status to Last Call
  EIPS/eip-1191.md
Labels: follow-up-with-author

#2325 Update meta tags
  README.md
  _config.yml
  _includes/head.html
  assets/css/style.scss
Labels: type: Meta

#2327 Draft EIP: BEGINDATA opcode
  EIPS/eip-2327.md
Labels: type: Core

#2364 EIP-2364: eth/64: forkid-extended protocol handshake
  EIPS/eip-2364.md
Labels: type: Networking

#2267 dType Functions Extension - Decentralized Type System for EVM
  EIPS/eip-1921.md
Labels: type: ERC

#1996 EIP-1996: Holdable token
  EIPS/eip-1996.md
Labels: type: ERC

#2018 EIP-2018: Clearable Token
  EIPS/eip-2018.md
Labels: type: ERC

#2019 EIP-2019: Fundable Token
  EIPS/eip-2019.md
Labels: type: ERC

#2009 EIP-2009: Compliance Service
  EIPS/eip-2009.md
Labels: type: ERC

#2021 EIP-2021: Payoutable Token
  EIPS/eip-2021.md
Labels: type: ERC

#2262 Make the return value of `account()` optional
  EIPS/eip-1767.md
Labels: waiting: approval/rejection

#2387 Hard fork proposal to address the Ice age
  EIPS/eip-2387.md
Labels: type: Meta

#2333 Draft EIP: BLS12-381 Key Generation
  EIPS/eip-2333.md
Labels: type: ERC

#2370 Add name to metadata title
  EIPS/eip-1450.md
Labels: maintenance/editing

#2334 Draft EIP: BLS12-381 Deterministic Account Hierarchy
  EIPS/eip-2333.md
  EIPS/eip-2334.md
Labels: type: ERC
