Repository ethereum/EIPs, pull requests merged in 2019-09, with the labels that each got.

#2070 Add hardfork meta after Istanbul (Berlin)
  EIPS/eip-2070.md
Labels: type: Meta

#2256 Add ERC for wallet_getOwnedAssets
  EIPS/eip-2256.md
Labels: type: Interface

#2236 EIP-1: formatting fixes and clarifications
  EIPS/eip-1.md
  EIPS/eip-1812.md
  EIPS/eip-2.md
  README.md
  eip-template.md
Labels: type: EIP1 (Process), type: Meta

#2186 EIP-1: remove requirement for simple summary
  EIPS/eip-1.md
Labels: type: EIP1 (Process), type: Meta

#1682 EIP-1682: Storage Rent
  EIPS/eip-1682.md
Labels: type: Core

#2196 EIP-1: clarify the process around core EIPs
  EIPS/eip-1.md
Labels: type: EIP1 (Process), type: Meta

#2069 Add YAML ABI draft
  EIPS/eip-2069.md
Labels: type: ERC

#2242 EIP-2242 Transaction postdata
  EIPS/eip-2242.md
Labels: type: Core
