Repository ethereum/EIPs, pull requests merged in 2019-06, with the labels that each got.

#2092 EIP-1193 improvements
  EIPS/eip-1193.md
Labels: ERC

#2058 Add EIP-1474 as a requirement to RPC ERCs
  EIPS/eip-1102.md
  EIPS/eip-1186.md
  EIPS/eip-1898.md
  EIPS/eip-234.md
  EIPS/eip-695.md
  EIPS/eip-758.md
Labels: ERC

#1968 Add special requirement in EIP-1 for mentioning EVM instructions
  EIPS/eip-1.md
Labels: meta

#1983 Change the citation format in README to point to EIP-1
  README.md
Labels: meta

#2025 Funding ETH1.X through a Developer Block Reward for 18 Months
  EIPS/eip-1679.md
  EIPS/eip-2025.md
Labels: EIP, istanbul

#1426 EIP 747: wallet_watchAsset
  EIPS/eip-747.md
Labels: ERC, follow-up-with-author

#2057 EIP-1193: Add chainChanged event
  EIPS/eip-1193.md
Labels: ERC

#1948 ERC-1948: Non-fungible Data Token
  EIPS/eip-1948.md
Labels: ERC, follow-up-with-author

#2081 Add "Rejected EIPs" into EIP-233 (and EIP-1679)
  EIPS/eip-1679.md
  EIPS/eip-233.md
Labels: meta

#2051 Introduced Abandoned status in EIP-1
  EIPS/eip-1.md
  _data/statuses.yaml
Labels: meta

#1967 EIP-1967: Standard Proxy Storage Slots
  EIPS/eip-1967.md
Labels: ERC, follow-up-with-author
