Repository ethereum/EIPs, pull requests merged in 2020-10, with the labels that each got.

#2474 EIP: Coinbase Calls
  EIPS/eip-2474.md
Labels: type: Core

#2924 Changes 1559 to have a single shared pool for all transactions.
  EIPS/eip-1559.md
Labels: waiting: approval/rejection

#2892 Update EIP-2565 to clarify specification
  EIPS/eip-2565.md
  assets/eip-2565/Complexity_Regression.png
  assets/eip-2565/GQuad_Change.png
  assets/eip-2565/Library_Benchmarks.png
Labels: maintenance/editing, waiting: clarifications from author

#2581 Add anchor headings to EIPs website
  _includes/anchor_headings.html
  _layouts/eip.html
  assets/css/style.scss
Labels: type: Meta

#2582 Add `Table of Contents` to EIPs website
  _includes/toc.html
  _layouts/eip.html
Labels: type: Meta

#2680 Initial cut of wallet layout EIP.
  EIPS/eip-2680.md
  assets/eip-2680/sha256-384-512.pdf
Labels: type: ERC, waiting: clarifications from author
