Repository ethereum/EIPs, pull requests merged in 2020-08, with the labels that each got.

#2584 State tree format conversion with the tree overlay method
  EIPS/eip-2584.md
Labels: type: Core

#2612 ERC for `permit`: 712-signed token approvals
  EIPS/eip-2612.md
Labels: type: ERC

#2677 EIP-2677: Cap initcode (draft)
  EIPS/eip-2677.md
Labels: type: Core

#2583 EIP-2583: Penalty for account trie misses
  EIPS/eip-2583.md
Labels: type: Core

#2115 Update EIPs to follow the rules regarding EVM opcodes (as stated in EIP-1)
  EIPS/eip-1014.md
  EIPS/eip-1051.md
  EIPS/eip-1052.md
  EIPS/eip-1087.md
  EIPS/eip-1109.md
  EIPS/eip-1153.md
  EIPS/eip-1283.md
  EIPS/eip-1285.md
Labels: waiting: approval/rejection

#2488 Add deprecate CALLCODE EIP
  EIPS/eip-2488.md
Labels: type: Core

#2690 Update eip2537: Add link to noble library.
  EIPS/eip-2537.md
Labels: waiting: approval/rejection

#2859 EIP-1559: Changes specification to functional Python code
  EIPS/eip-1559.md
Labels: waiting: approval/rejection
