Repository ethereum/EIPs, pull requests merged in 2020-09, with the labels that each got.

#2926 Chunk-Based Code Merkleization
  EIPS/eip-2926.md
Labels: type: Core

#2918 Include last call review-end-date in the rendered summary
  _includes/eiptable.html
  _layouts/eip.html
Labels: type: Meta

#2511 Updated to Last Call
  EIPS/eip-2124.md
Labels: maintenance/editing

#2512 Updated EIP-778 and EIP-868 to Last Call as it has already been implemented in the Clients
  EIPS/eip-778.md
  EIPS/eip-868.md
Labels: maintenance/editing

#2822 Deprecate ERC 1123
  EIPS/eip-1123.md
Labels: maintenance/editing

#2699 1193: Finalize
  EIPS/eip-1193.md
Labels: maintenance/editing

#2827 EIP-908: Marking as withdrawn
  EIPS/eip-908.md
Labels: maintenance/editing

#2828 EIP-1240: Changes status to Withdrawn
  EIPS/eip-1240.md
Labels: maintenance/editing

#2649 2255: Add external images to assets folder
  EIPS/eip-2255.md
  assets/eip-2255/facebook_permissions.png
  assets/eip-2255/log_in_with_apple.jpeg
  assets/eip-2255/permissions_adventure.gif
Labels: maintenance/editing

#2672 695: Errata: remove EIP-1474 from dependencies
  EIPS/eip-695.md
Labels: maintenance/editing

#2939 Simplify the EIP template
  EIPS/eip-1.md
  EIPS/eip-1080.md
  EIPS/eip-1081.md
  EIPS/eip-1129.md
  EIPS/eip-1167.md
  EIPS/eip-1178.md
  EIPS/eip-1186.md
  EIPS/eip-1271.md
  EIPS/eip-1285.md
  EIPS/eip-1295.md
  EIPS/eip-1470.md
  EIPS/eip-1482.md
  EIPS/eip-1491.md
  EIPS/eip-152.md
  EIPS/eip-1523.md
  EIPS/eip-1538.md
  EIPS/eip-1616.md
  EIPS/eip-1620.md
  EIPS/eip-1706.md
  EIPS/eip-1710.md
  EIPS/eip-1775.md
  EIPS/eip-1829.md
  EIPS/eip-1895.md
  EIPS/eip-1922.md
  EIPS/eip-1923.md
  EIPS/eip-1967.md
  EIPS/eip-2014.md
  EIPS/eip-2025.md
  EIPS/eip-2026.md
  EIPS/eip-2027.md
  EIPS/eip-2029.md
  EIPS/eip-2031.md
  EIPS/eip-2035.md
  EIPS/eip-2159.md
  EIPS/eip-2266.md
  EIPS/eip-2309.md
  EIPS/eip-2327.md
  EIPS/eip-2330.md
  EIPS/eip-2378.md
  EIPS/eip-2458.md
  EIPS/eip-2481.md
  EIPS/eip-2535.md
  EIPS/eip-2537.md
  EIPS/eip-2542.md
  EIPS/eip-2612.md
  EIPS/eip-2711.md
  EIPS/eip-2767.md
  EIPS/eip-2844.md
  EIPS/eip-2876.md
  EIPS/eip-2926.md
  EIPS/eip-2936.md
  EIPS/eip-712.md
  EIPS/eip-747.md
  EIPS/eip-908.md
  eip-template.md
Labels: maintenance/editing, type: EIP1 (Process)

#2550 Update username in EIP-1319
  EIPS/eip-1319.md
Labels: waiting: approval/rejection

#2299 EIP 1901 - Add OpenRPC Tooling Implementations
  EIPS/eip-1901.md
  assets/eip-1901/eth-generated-client-openrpc.gif
  assets/eip-1901/eth-playground-openrpc.gif
  assets/eip-1901/inspector-mock-server-openrpc.png
Labels: maintenance/editing

#2308 EIP-2266: change status from draft to last call
  EIPS/eip-2266.md
Labels: maintenance/editing, stale, waiting: clarifications from author

#2494 EIP-2494 Baby Jubjub Elliptic Curve
  EIPS/eip-2494.md
Labels: type: ERC

#2867 2309 to Final
  EIPS/eip-2309.md
Labels: maintenance/editing

#2937 SET_INDESTRUCTIBLE opcode
  EIPS/eip-2937.md
Labels: type: Core

#2386 Ethereum 2 walletstore
  EIPS/eip-2386.md
Labels: type: ERC

#2593 Gas price market change: Escalator Algorithm (alternative to 1559)
  EIPS/eip-2593.md
Labels: stale, type: Core

#2452 Remove duplicate file
  EIPS/eip-1047.md
Labels: maintenance/editing, type: Meta

#2390 GeoENS pull request - initial revision
  EIPS/eip-2390.md
Labels: type: ERC

#2938 Account abstraction EIP
  EIPS/eip-2938.md
Labels: type: Core

#2617 ERC-1363: Move to Last Call
  EIPS/eip-1363.md
Labels: maintenance/editing, waiting: clarifications from author

#2539 BLS12-377 curve operations
  EIPS/eip-2539.md
Labels: type: Core

#1297 Reword README
  README.md
Labels: type: EIP1 (Process), type: Meta
