Repository ethereum/EIPs, pull requests merged in 2020-11, with the labels that each got.

#2520 Draft EIP: Multiple contenthash records for ENS
  EIPS/eip-2520.md
Labels: type: ERC

#2969 EIP-1: require at least one github username
  EIPS/eip-1.md
Labels: type: EIP1 (Process)

#2545 EIP-2025: Change Status to Withdrawn
  EIPS/eip-2025.md
Labels: maintenance/editing, waiting: clarifications from author

#2666 Precompiles and Keccak256 repricing
  EIPS/eip-2666.md
Labels: type: Core

#2777 747: Cleanup
  EIPS/eip-747.md
Labels: waiting: approval/rejection
