Repository ethereum/EIPs, pull requests merged in 2021-12, with the labels that each got.

#3696 Link to hardfork specs
  index.html
Labels: waiting: response from author, type: EIP1 (Process)

#4393 Eip micropayments standard for nfts and multi tokens
  EIPS/eip-micropayments_standard_for_nfts_and_multi_tokens.md
Labels: waiting: response from author

#4609 Fix pseudocode on EIP-4337 paymaster reputation status
  EIPS/eip-4337.md
Labels: updateEIP

#4617 [EIP-3978] Update specification
  EIPS/eip-3978.md
Labels: updateEIP
