Repository ethereum/EIPs, pull requests merged in 2022-05, with the labels that each got.

#5008 EIP5008: ERC-721 Nonce Extension
  EIPS/eip-5008.md
Labels: updateEIP

#5068 EIP-4399: add test cases
  EIPS/eip-4399.md
Labels: updateEIP

#5067 EIP-3675: add test cases
  EIPS/eip-3675.md
Labels: updateEIP

#5070 Fixed Deposit Snapshot Endpoint
  EIPS/eip-4881.md
Labels: updateEIP

#5061 EIP-1967: Editor revisions before Final
  EIPS/eip-1967.md
Labels: updateEIP

#5028 add more to the reference implementation of EIP-1153
  EIPS/eip-1153.md
Labels: updateEIP

#4974 EIP-4974: Fungible Non-tradable Tokens, or EXP
  EIPS/eip-4974.md
  assets/eip-4974/ERC4974.sol
  assets/eip-4974/IERC4974.sol
  assets/eip-4974/IERC4974Metadata.sol
Labels: ambiguous, updateEIP

#4931 EIP-4931 - Generic Token Upgrade Standard
  EIPS/eip-4931.md
Labels: updateEIP

#5026 Discourage 'standard' in EIP titles & descriptions (closes #5009)
  EIPS/eip-1.md
Labels: updateEIP

#5064 Mark ERC-4907 for Review
  EIPS/eip-4907.md
Labels: updateEIP

#5049 Mark ERC-4799 for Review
  EIPS/eip-4799.md
Labels: updateEIP

#4938 eth/67: Removal of GetNodeData
  EIPS/eip-4938.md
Labels: updateEIP

#5006 EIP5006: ERC-1155 Usage Rights Extension
  EIPS/eip-5006.md
Labels: updateEIP

#4992 Correct typo: BLSCommitment -> KZGCommitment
  EIPS/eip-4844.md
Labels: updateEIP

#5022 EIP-5022: Increase price of SSTORE from zero to non-zero to 40k gas
  EIPS/eip-5022.md
Labels: updateEIP

#5057 Set FORK_BLOCK in EIP-2929 and EIP-2930
  EIPS/eip-2929.md
  EIPS/eip-2930.md
Labels: updateEIP

#5073 [EIP EDITOR NEEDED TO] Debug the EIP bot
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#4972 Create eip-4972.md
  EIPS/eip-4972.md
Labels: updateEIP

#5065 EIP-5065 - Instruction to transfer Ether
  EIPS/eip-5065.md
Labels: updateEIP

#5081 Create eip-5081.md Expirable Transaction
  EIPS/eip-5081.md
Labels: updateEIP

#5085 EIP-3540: Remove Simplified Implementation section
  EIPS/eip-3540.md
Labels: updateEIP

#5093 EIP-3074: Clarify that ignored bytes still cost gas
  EIPS/eip-3074.md
Labels: updateEIP

#4858 Review of the EIP 3475
  EIPS/eip-3475.md
  assets/eip-3475/ERC3475.sol
  assets/eip-3475/IERC3475.sol
Labels: ambiguous, updateEIP

#5097 ERC4907: optimize for gas saving
  EIPS/eip-4907.md
  assets/eip-4907/.gitignore
  assets/eip-4907/contracts/ERC4907.sol
Labels: ambiguous, updateEIP

#5035 Move ERC1967 to Final (Last call deadline reached)
  EIPS/eip-1967.md
Labels: updateEIP

#5100 Update EIP4400 based on community feedback
  EIPS/eip-4400.md
Labels: updateEIP

#4906 EIP4906: ERC-721 Metadata Update Extension
  EIPS/eip-4906.md
Labels: updateEIP

#5027 Create EIP-5027
  EIPS/eip-5027.md
  assets/eip-5027/0001-unlimit-code-size.patch
Labels: ambiguous, updateEIP

#4995 Create EIP-4804
  EIPS/eip-4804.md
Labels: newEIPFile

#5105 Fixes "spelling error" in diff
  assets/eip-5027/0001-unlimit-code-size.patch
Labels: ambiguous

#5106 EIP-4844: Change to versioned hashes
  EIPS/eip-4844.md
Labels: updateEIP

#5108 EIP-4400: Text format optimization
  EIPS/eip-4400.md
Labels: updateEIP

#5110 Add support for EIP-3770 chain-specific address
  EIPS/eip-4804.md
Labels: updateEIP

#5005 add eip-zodiac
  EIPS/eip-5005.md
Labels: updateEIP

#5007 EIP5007: TimeNFT, ERC-721 Time Extension
  EIPS/eip-5007.md
  assets/eip-5007/.gitignore
  assets/eip-5007/README.md
  assets/eip-5007/contracts/ERC5007.sol
  assets/eip-5007/contracts/ERC5007Demo.sol
  assets/eip-5007/contracts/IERC5007.sol
  assets/eip-5007/migrations/1_initial_migration.js
  assets/eip-5007/package.json
  assets/eip-5007/test/test.js
  assets/eip-5007/truffle-config.js
Labels: ambiguous, updateEIP

#5098 ERC4907： Change status to Last Call
  EIPS/eip-4907.md
Labels: updateEIP

#5104 EIP3156: small fix in code example
  EIPS/eip-3156.md
Labels: updateEIP

#5116 EIP4400: Update status to Final
  EIPS/eip-4400.md
Labels: updateEIP

#5117 EIP-4906: Change status to Review
  EIPS/eip-4906.md
Labels: updateEIP

#5094 5094: URI Format for Ethereum Network Switching
  EIPS/eip-5094.md
Labels: updateEIP
