Repository ethereum/EIPs, pull requests merged in 2022-06, with the labels that each got.

#5066 Revamp github issue/PR config
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/propose-process-change.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ambiguous

#5126 EIP-4200: Update reference code
  EIPS/eip-4200.md
Labels: updateEIP

#5018 Create eip-5018
  EIPS/eip-5018.md
Labels: updateEIP

#5122 Finalize EIP-2464
  EIPS/eip-2464.md
Labels: updateEIP

#5133 Delaying Difficulty Bomb to Mid August 2022
  EIPS/eip-5133.md
Labels: updateEIP

#5125 Proposed changes in draft EIP-4906. The proposal would add consecuti…
  EIPS/eip-4906.md
Labels: updateEIP

#5137 Update eip-4804.md
  EIPS/eip-4804.md
Labels: updateEIP

#5121 Finalize EIP-2364
  EIPS/eip-2364.md
Labels: updateEIP

#5140 EIP-4844: remove blob-verification precompile in favor of point-evaluation precompile
  EIPS/eip-4844.md
Labels: updateEIP

#5141 remove "If it is not ready by then..."
  EIPS/eip-5133.md
Labels: updateEIP

#5114 Creates EIP-5114: Soulbound Token
  EIPS/eip-5114.md
Labels: updateEIP

#4675 Add Multi-Fractional Non-Fungible Token Standard
  EIPS/eip-4675.md
  assets/eip-4675/.gitignore
  assets/eip-4675/.solcover.js
  assets/eip-4675/README.md
  assets/eip-4675/contracts/ERC20Token.sol
  assets/eip-4675/contracts/MFNFT.sol
  assets/eip-4675/contracts/NFT.sol
  assets/eip-4675/contracts/helper/Verifier.sol
  assets/eip-4675/contracts/interface/IERC20.sol
  assets/eip-4675/contracts/interface/IERC721.sol
  assets/eip-4675/contracts/interface/IMFNFT.sol
  assets/eip-4675/contracts/math/SafeMath.sol
  assets/eip-4675/hardhat.config.ts
  assets/eip-4675/package.json
  assets/eip-4675/src/deploy/deploy_contracts.ts
  assets/eip-4675/test/MFNFT.General.spec.ts
  assets/eip-4675/test/utils/execution.ts
  assets/eip-4675/test/utils/setup.ts
  assets/eip-4675/tsconfig.json
Labels: ambiguous, updateEIP

#5139 Get a first pass of an RPC endpoint list standard going
  EIPS/eip-5139.md
  assets/eip-5139/AUTHORS.md
  assets/eip-5139/semver.md
Labels: ambiguous, updateEIP

#5151 Changed Prediction Script
  EIPS/eip-5133.md
Labels: updateEIP

#5153 Update eip-4804.md
  EIPS/eip-4804.md
Labels: updateEIP

#5154 Update Rationale
  EIPS/eip-5133.md
Labels: updateEIP

#5123 Add myself (@Pandapip1) as an editor
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#5148 EIP-4973: Add `function burn` to reference impl.
  assets/eip-4973/src/ERC4973.sol
  assets/eip-4973/src/ERC4973.t.sol
  assets/eip-4973/src/interfaces/IERC4973.sol
Labels: ambiguous

#5118 EIP-1: Mark sections that are optional as optional (closes #5112)
  EIPS/eip-1.md
Labels: updateEIP

#5159 Update Motivation
  EIPS/eip-5133.md
Labels: updateEIP

#5168 Eip 5139: Micah feedback
  EIPS/eip-5139.md
Labels: updateEIP

#5156 Include myself in the editor list of EIP-1
  EIPS/eip-1.md
Labels: updateEIP

#5171 Improve motivation section of EIP-4973 and cleanup co-authors
  EIPS/eip-4973.md
Labels: updateEIP

#5103 ERC4353: interface for staked NFTs (#4353)
  EIPS/eip-4353.md
Labels: updateEIP

#5180 Move EIP-2976 to final
  EIPS/eip-2976.md
Labels: updateEIP

#5175 fix: Split `transferFrom` flows
  EIPS/eip-4626.md
Labels: updateEIP

#5181 Status to Review
  EIPS/eip-5133.md
Labels: updateEIP

#5182 Status to Last Call
  EIPS/eip-5133.md
Labels: updateEIP

#5184 4626 -> fix`caller` is a reserved keyword in vyper
  EIPS/eip-4626.md
Labels: updateEIP

#5177 Run EIP bot on draft PRs
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#5161 EIP4907: Change Status to Final
  EIPS/eip-4907.md
  assets/eip-4907/README.md
  assets/eip-4907/contracts/ERC4907.sol
  assets/eip-4907/contracts/ERC4907Demo.sol
  assets/eip-4907/contracts/IERC4907.sol
  assets/eip-4907/package.json
Labels: ambiguous, updateEIP

#5069 EIP-5069: EIP editor handbook in EIP form
  EIPS/eip-1.md
  EIPS/eip-5069.md
  README.md
Labels: ambiguous, updateEIP, newEIPFile

#5143 ERC-5143: Slippage protection for Tokenized Vault ERC
  EIPS/eip-5143.md
Labels: updateEIP

#5186 Major update of ERC-3525 protocol
  EIPS/eip-3525.md
Labels: updateEIP

#5188 Minor update and clean-ups
  EIPS/eip-3525.md
Labels: updateEIP

#5090 Update eip-4788.md
  EIPS/eip-4788.md
Labels: updateEIP

#5179 Fix section order for EIP-4353
  EIPS/eip-4353.md
Labels: updateEIP
