Repository ethereum/EIPs, pull requests merged in 2022-03, with the labels that each got.

#4859 Add Sam Wilson (me) as an editor
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#4866 4626: rounding and overflow clarifications
  EIPS/eip-4626.md
Labels: updateEIP

#4867 4626: link fix
  EIPS/eip-4626.md
Labels: updateEIP

#4863 EIP-4863: Beacon chain push withdrawals
  EIPS/eip-4863.md
Labels: updateEIP

#4865 Add .gitpod.yml to gitignore
  .gitignore
Labels: ambiguous

#4869 EIP-3978 modifications
  EIPS/eip-3978.md
Labels: updateEIP

#4878 Added a caveat about refunds
  EIPS/eip-4393.md
Labels: updateEIP

#4872 Advise against external links & add myself as an active editor
  EIPS/eip-1.md
Labels: updateEIP

#4871 fix the link to eip-2929
  EIPS/eip-3651.md
Labels: updateEIP

#4883 Update eip-4573.md
  EIPS/eip-4573.md
Labels: updateEIP

#4881 Deposit Contract Snapshot Interface
  EIPS/eip-4881.md
  assets/eip-4881/deposit_snapshot.py
  assets/eip-4881/deposit_tree_evolution.png
  assets/eip-4881/eip4881.py
  assets/eip-4881/test_cases.yaml
  assets/eip-4881/test_deposit_snapshot.py
Labels: ambiguous, updateEIP

#4890 Addressed @lightclient's Comments
  EIPS/eip-4881.md
Labels: updateEIP

#4891 EIP-4844: Move consensus layer part to consensus specs repository
  EIPS/eip-4844.md
Labels: updateEIP

#4892 4626: clear up max functions & remove decimals clause
  EIPS/eip-4626.md
Labels: updateEIP

#4893 4626: decimals recommendation
  EIPS/eip-4626.md
Labels: updateEIP

#4894 Improve Rendering of EIP-4881 on eips.ethereum.org
  EIPS/eip-4881.md
Labels: updateEIP

#4896 Updates to EIP-4863
  EIPS/eip-4863.md
Labels: updateEIP

#4895 Beacon chain withdrawals as system-level operations
  EIPS/eip-4895.md
Labels: updateEIP

#4901 fix(eip-1153): add opcodes and some more info to the security considerations about memory
  EIPS/eip-1153.md
Labels: updateEIP

#4903 fix(eip-1153): update the copy with new opcodes 0xb3 and 0xb4
  EIPS/eip-1153.md
Labels: updateEIP

#4904 EIP-4844: v -> y_parity like EIP-1559, and fix intrinsic gas
  EIPS/eip-4844.md
Labels: updateEIP

#4898 ERC-4626: Clarify maxDeposit/maxMind
  EIPS/eip-4626.md
Labels: updateEIP

#4899 ERC-4626: Clarify Preview Revert behavior
  EIPS/eip-4626.md
Labels: updateEIP

#4905 Clarify ERC-4626 flows
  EIPS/eip-4626.md
Labels: updateEIP

#4909 align transaction ordering requirements after edit in #4896
  EIPS/eip-4863.md
Labels: updateEIP

#4908 Add CC0
  LICENSE
Labels: ambiguous

#4417 EIP725 - remove 'SupportedStandards:ERC725Account
  EIPS/eip-725.md
Labels: updateEIP

#4924 Move EIP-4626 to Final 🎉
  EIPS/eip-4626.md
Labels: updateEIP

#4920 Small reference typo correction in EIP-3540 (EVM Object Format)
  EIPS/eip-3540.md
Labels: updateEIP

#4925 Eip 3651: Stagnant -> Review
  EIPS/eip-3651.md
Labels: updateEIP

#4736 Consensus Layer Withdrawal Protection
  EIPS/eip-4736.md
Labels: updateEIP

#4929 Update eip-2315.md
  EIPS/eip-2315.md
Labels: updateEIP

#4491 Fix typo in contract reference number
  EIPS/eip-2309.md
Labels: updateEIP

#4464 Fixed markdown
  EIPS/eip-2334.md
Labels: stale, updateEIP

#4785 EIP-4400: Mark for review; Update motivation
  EIPS/eip-4400.md
Labels: updateEIP

#4885 EIP proposal: Subscription Token Standard for NFTs and Multi Tokens
  EIPS/eip-4885.md
Labels: updateEIP

#4940 EIP-3651 Description
  EIPS/eip-3651.md
Labels: updateEIP

#4537 Update EIP to refer to Ethereum Mainnet, wording as per EIP-2228
  EIPS/eip-1013.md
Labels: stale, updateEIP

#4947 EIP-1153 Review
  EIPS/eip-1153.md
Labels: updateEIP

#4937 docs: add function overloading
  EIPS/eip-725.md
Labels: updateEIP

#4571 EIP 712 assets: fix example.js (cosmetic)
  assets/eip-712/Example.js
Labels: ambiguous

#4913 EIP-3156: fix return type in implementation
  EIPS/eip-3156.md
Labels: updateEIP

#4942 mark EIP-1153 as review
  EIPS/eip-1153.md
Labels: updateEIP

#4760 EIP-4760: SELFDESTRUCT bomb
  EIPS/eip-4760.md
Labels: updateEIP

#4762 EIP-4762: Statelessness gas cost changes
  EIPS/eip-4762.md
Labels: updateEIP

#4758 EIP-4758: Deactivate selfdestruct
  EIPS/eip-4758.md
Labels: updateEIP

#4952 add staticcall behavior to transient storage EIP-1153
  EIPS/eip-1153.md
Labels: updateEIP

#4956 post-audit changes
  EIPS/eip-4337.md
Labels: updateEIP

#4951 Remove mention of rationale containing "proof of consensus".
  EIPS/eip-1.md
Labels: updateEIP
