Repository ethereum/EIPs, pull requests merged in 2022-01, with the labels that each got.

#4619 Renamed eip-micropayments_standard_... to eip-4393.md
  EIPS/eip-4393.md
Labels: updateEIP

#4546 Wrapped deposit EIP
  EIPS/eip-4546.md
Labels: updateEIP

#4341 EIP-4341: Ordered NFT Batch Standard
  EIPS/eip-4341.md
Labels: updateEIP

#4631 Changed to Natspec format for EIP-4393 document code comments, and ad…
  EIPS/eip-4393.md
Labels: updateEIP

#4632 More improvements to 3668
  EIPS/eip-3668.md
Labels: updateEIP

#4625 Change 'ERC#' to 'EIP#' for consistent documentation of EIPs in EIP-1
  EIPS/eip-1.md
Labels: updateEIP

#4634 Fix a typo in eip-1.md
  EIPS/eip-1.md
Labels: updateEIP

#4639 Fix broken links
  EIPS/eip-649.md
Labels: updateEIP

#4626 EIP-4626: Tokenized Vault Standard
  EIPS/eip-4626.md
Labels: newEIPFile

#4633 Move 3668 to Review
  EIPS/eip-3668.md
Labels: updateEIP

#4656 Make URL a substitution string
  EIPS/eip-3668.md
Labels: updateEIP

#4663 Update eip-3607.md
  EIPS/eip-3607.md
Labels: updateEIP

#4657 Move 3668 to last call
  EIPS/eip-3668.md
Labels: updateEIP

#4662 Move 3607 to Last Call
  EIPS/eip-3607.md
Labels: updateEIP

#4654 Fix a typo in eip-1011.md
  EIPS/eip-1011.md
Labels: updateEIP

#4557 EIP-4521: 721/20-compatible transfer
  EIPS/eip-4521.md
Labels: updateEIP

#4661 Update eip-4626.md
  EIPS/eip-4626.md
Labels: updateEIP

#4558 Move 3448 to Last Call
  EIPS/eip-3448.md
Labels: updateEIP

#4645 Update eip-4626.md
  EIPS/eip-4626.md
Labels: updateEIP

#4667 Procs safe subs again
  EIPS/eip-2315.md
  EIPS/eip-3779.md
  EIPS/eip-4573.md
Labels: updateEIP

#4668 calculate* requirements and rationale
  EIPS/eip-4626.md
Labels: updateEIP

#4669 Rewrite the `calculate*` descriptions
  EIPS/eip-4626.md
Labels: updateEIP

#4655 EIP-4361: fix mandatory fields (domain & chainId)
  EIPS/eip-4361.md
Labels: updateEIP

#4673 Tighter function descriptions
  EIPS/eip-4626.md
Labels: updateEIP

#4670 docs: fix a typo in eip-1015.md
  EIPS/eip-1015.md
Labels: ambiguous

#4676 Update eip-998.md
  EIPS/eip-998.md
Labels: updateEIP

#4679 Exact parameters, `calculate*` descriptions
  EIPS/eip-4626.md
Labels: updateEIP

#4681 Update eip-4573.md
  EIPS/eip-4573.md
Labels: updateEIP

#4682 Update eip-4573.md
  EIPS/eip-4573.md
Labels: updateEIP

#4684 LaTex
  EIPS/eip-4573.md
Labels: updateEIP

#4685 still fighting LaTex
  EIPS/eip-4573.md
Labels: updateEIP

#4686 No LaTex :(
  EIPS/eip-4573.md
Labels: updateEIP

#4687 Update eip-4573.md
  EIPS/eip-4573.md
Labels: updateEIP

#4688 Changed withdraw method name to withdrawReward and added clarification to royalty distribution section
  EIPS/eip-4393.md
Labels: updateEIP

#4689 Update eip-2315.md
  EIPS/eip-2315.md
Labels: updateEIP

#4691 [EIP-3978] Add LOGs gas refunds
  EIPS/eip-3978.md
Labels: updateEIP

#4690 Update eip-4573.md
  EIPS/eip-4573.md
Labels: updateEIP, automerge

#4697 Update ERC-4337 RPC methods
  EIPS/eip-4337.md
Labels: updateEIP, automerge

#4700 Update eip-3779.md
  EIPS/eip-3779.md
Labels: EVM, updateEIP

#4677 Typo in eip-191
  EIPS/eip-191.md
Labels: updateEIP, automerge

#4704 Updated interface identifier number for latest changes to ITipToken
  EIPS/eip-4393.md
Labels: updateEIP

#4710 EIP-4626: Preview functions
  EIPS/eip-4626.md
Labels: updateEIP

#4711 ERC-4626: Cleanup formatting
  EIPS/eip-4626.md
Labels: updateEIP

#4701 docs: fix a typo in eip-1052.md
  EIPS/eip-1052.md
Labels: updateEIP

#4718 update EIP4337: authors
  EIPS/eip-4337.md
Labels: updateEIP

#4716 4200: Change to Review
  EIPS/eip-4200.md
Labels: updateEIP

#4715 Update eip-4337.md
  EIPS/eip-4337.md
Labels: updateEIP

#4462 Add missing sections to eip-3770 and rename asset
  EIPS/eip-3770.md
  assets/eip-3770/examples.png
Labels: ambiguous, updateEIP

#4660 EIP-2980: Review status
  EIPS/eip-2980.md
Labels: updateEIP

#4724 Add an optional Reference section.
  eip-template.md
Labels: ambiguous

#4725 Revert "Add an optional Reference section. (#4724)"
  eip-template.md
Labels: ambiguous

#4717 Finalize ERC-1271
  EIPS/eip-1271.md
Labels: updateEIP

#4730 Gcolvin procedures
  EIPS/eip-4573.md
Labels: updateEIP

#4732 Gcolvin procedures
  EIPS/eip-4573.md
Labels: updateEIP

#4692 Move EIP-2315 to Review
  EIPS/eip-2315.md
Labels: updateEIP

#4719 3779-to-review
  EIPS/eip-3779.md
Labels: updateEIP
