Repository ethereum/EIPs, pull requests merged in 2022-07, with the labels that each got.

#5194 Update eip-2535.md
  EIPS/eip-2535.md
Labels: updateEIP

#5193 fix: Added "override" keyword to the ownerOf function in the ERC-4973 contract
  assets/eip-4973/ERC-4973.sol
Labels: ambiguous

#5195 Update eip-4804.md
  EIPS/eip-4804.md
Labels: updateEIP

#5185 NFT Updatable Metadata Extension
  EIPS/eip-5185.md
Labels: updateEIP

#5200 Generalize the language of ERC-5005 and remove external references.
  EIPS/eip-5005.md
Labels: updateEIP

#5203 EIP-5006: change frozenOfOwner to frozenAmountOfOwner
  EIPS/eip-5006.md
  assets/eip-5006/contracts/ERC5006.sol
  assets/eip-5006/contracts/ERC5006Demo.sol
  assets/eip-5006/contracts/IERC5006.sol
  assets/eip-5006/test/test.ts
Labels: ambiguous, updateEIP

#5201 Update eip-1202.md
  EIPS/eip-1202.md
Labels: updateEIP

#5204 EIP5006: Change Status to Last Call
  EIPS/eip-5006.md
Labels: updateEIP

#5208 add missing events
  EIPS/eip-5005.md
Labels: updateEIP

#5211 Changed reference implementation url
  EIPS/eip-4337.md
Labels: updateEIP

#5155 Fixed links to ERC-721, added keyword "payable" in some functions, and update to review
  EIPS/eip-4519.md
  assets/eip-4519/images/Fig5_rev.png
  assets/eip-4519/images/Figure1.jpg
  assets/eip-4519/images/Figure1.png
  assets/eip-4519/images/Figure2.jpg
  assets/eip-4519/images/Figure3.jpg
  assets/eip-4519/images/Figure4.jpg
Labels: statusChange, ambiguous

#5210 Move EIP-173 to final with minor (normal) changes
  EIPS/eip-173.md
Labels: updateEIP

#5131 Add EIP-5131: ENS Subdomain Authentication
  EIPS/eip-5131.md
Labels: updateEIP

#5166 EIP-3475 last call addition with changes in standard
  EIPS/eip-3475.md
  assets/eip-3475/Debond-ERC3475.sol
  assets/eip-3475/ERC3475.sol
  assets/eip-3475/ERC3475.test.ts
  assets/eip-3475/IERC3475.sol
  assets/eip-3475/Metadata.md
Labels: ambiguous, updateEIP

#5238 Update eip-2535.md
  EIPS/eip-2535.md
Labels: updateEIP

#5000 MULDIV instruction
  EIPS/eip-5000.md
Labels: updateEIP

#5221 Move EIP-4834 from Draft to Review
  EIPS/eip-4834.md
Labels: updateEIP

#5243 Fix typos in EIP-5189
  EIPS/eip-5189.md
Labels: updateEIP

#5230 Fix SPDX license identifier in EIP-4671
  EIPS/eip-4671.md
  assets/eip-4671/ERC4671.sol
  assets/eip-4671/ERC4671Consensus.sol
  assets/eip-4671/ERC4671Delegate.sol
  assets/eip-4671/ERC4671Pull.sol
  assets/eip-4671/ERC4671Store.sol
  assets/eip-4671/IERC4671.sol
  assets/eip-4671/IERC4671Consensus.sol
  assets/eip-4671/IERC4671Delegate.sol
  assets/eip-4671/IERC4671Enumerable.sol
  assets/eip-4671/IERC4671Metadata.sol
  assets/eip-4671/IERC4671Pull.sol
  assets/eip-4671/IERC4671Store.sol
Labels: ambiguous, updateEIP

#5225 Fix SPDX license identifier in EIP-3475
  EIPS/eip-3475.md
  assets/eip-3475/IERC3475.sol
Labels: ambiguous, updateEIP

#5244 Fix eth-bot automerging & configure kodiak
  .github/workflows/auto-merge-bot.yml
  .kodiak.toml
Labels: ambiguous

#5249 Small fix for when the Gemfile is updated
  .github/workflows/ci.yml
Labels: ambiguous

#5250 Add trial run of eipw
  .github/workflows/ci.yml
Labels: ambiguous

#5251 Remove defunct option in HTMLProofer CI
  .github/workflows/ci.yml
Labels: ambiguous

#5228 Add SPDX License Identifier to EIP-3448
  EIPS/eip-3448.md
  assets/eip-3448/MetaProxyFactory.sol
  assets/eip-3448/MetaProxyTest.sol
Labels: ambiguous, updateEIP

#5226 Add SPDX License Identifier to EIP-2266
  EIPS/eip-2266.md
  assets/eip-2266/Example.sol
Labels: ambiguous, updateEIP

#5256 Revert "Small fix for when the Gemfile is updated"
  .github/workflows/ci.yml
Labels: ambiguous

#5257 EIP-4200: Add test cases
  EIPS/eip-4200.md
Labels: updateEIP

#5259 Add vercel-based previewing
  .github/workflows/ci.yml
  .gitignore
  _config.yml
Labels: ambiguous

#5260 Fix vercel
  .github/workflows/ci.yml
  .github/workflows/vercel.yml
Labels: ambiguous

#5263 Fix vercel... again
  .github/workflows/vercel.yml
Labels: ambiguous

#5202 EIP-5202: Standard Factory Contract Format
  EIPS/eip-5202.md
Labels: updateEIP

#5267 Add EIP-5267: Retrieval of EIP-712 domain
  EIPS/eip-5267.md
Labels: updateEIP

#5266 Force LF line endings
  .gitattributes
  EIPS/eip-1485.md
  EIPS/eip-4341.md
  assets/eip-4519/ESP32_Firmware/readme.md
Labels: ambiguous, updateEIP

#5275 Try something to allow comments
  .github/workflows/ci.yml
Labels: ambiguous

#5276 Revert "Try something to allow comments"
  .github/workflows/ci.yml
Labels: ambiguous

#5277 Move EIPW into a pull_request_target workflow instead
  .github/workflows/auto-merge-bot.yml
  .github/workflows/ci.yml
Labels: ambiguous

#5278 Don't lint EIP-1 or EIP-5069
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#5247 ERC-5247: Smart Proposal
  EIPS/eip-5247.md
Labels: updateEIP

#5279 Revert "Move EIPW into a pull_request_target workflow instead (#5277)"
  .github/workflows/auto-merge-bot.yml
  .github/workflows/ci.yml
Labels: ambiguous

#5281 Use a workflow_run trigger to make the `eipw` comment
  .github/workflows/ci-comment.yml
  .github/workflows/ci.yml
Labels: ambiguous

#4416 Resurrect EIP-1328
  EIPS/eip-1328.md
Labels: waiting: response from author, updateEIP

#5034 Mark EIP-4361 for Review
  EIPS/eip-4361.md
  assets/eip-4361/example.js
  assets/eip-4361/package.json
  assets/eip-4361/signing.png
Labels: ambiguous, updateEIP

#5287 EIP-4519 - Tittle fixed to less than 44 characters.
  EIPS/eip-4519.md
Labels: updateEIP

#5286 Move EIP-1328 to review
  EIPS/eip-1328.md
Labels: updateEIP

#5290 Make the CI Commenting Cleaner
  .github/workflows/ci-comment.yml
Labels: ambiguous

#5284 EIP-4906: Change status to Last Call
  EIPS/eip-4906.md
Labels: updateEIP

#5222 EIP-5218: NFT Rights Management
  EIPS/eip-5218.md
  assets/eip-5218/contracts/README.md
  assets/eip-5218/contracts/foundry.toml
  assets/eip-5218/contracts/remappings.txt
  assets/eip-5218/contracts/src/IERC5218.sol
  assets/eip-5218/contracts/src/RightsManagement.sol
  assets/eip-5218/contracts/test/Contract.t.sol
  assets/eip-5218/ic3license/ic3license.pdf
  assets/eip-5218/ic3license/ic3license.tex
  assets/eip-5218/license-tree.png
Labels: ambiguous, updateEIP

#5291 Update the issue forms
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: ambiguous

#5304 ERC-5006 Implementation Bugfix
  EIPS/eip-5006.md
  assets/eip-5006/contracts/ERC5006.sol
Labels: ambiguous, updateEIP

#5229 Fix SPDX license identifier in EIP-4400
  EIPS/eip-4400.md
  assets/eip-4400/LICENSE
  assets/eip-4400/README.md
  assets/eip-4400/contracts/ERC721Consumable.sol
  assets/eip-4400/contracts/ExampleToken.sol
  assets/eip-4400/contracts/IERC721Consumable.sol
Labels: ambiguous, updateEIP

#5217 EIP 2400 - Tx hash URI: Move from Stagnant to Review
  EIPS/eip-2400.md
Labels: updateEIP

#5313 EIP-5313 Light Contract Ownership
  EIPS/eip-5313.md
Labels: updateEIP

#5309 Move EIP-5267 to Review
  EIPS/eip-5267.md
Labels: updateEIP

#5295 Move EIP-4834 to Last Call
  EIPS/eip-4834.md
Labels: updateEIP

#5314 Move to last call
  EIPS/eip-5313.md
Labels: updateEIP

#5326 wip: minor changes about ERC -> EIP and spaces
  EIPS/eip-3475.md
Labels: updateEIP

#5327 Remove an unnoticed single quote
  .github/workflows/rerun-bot-pull-request-review.yml
Labels: ambiguous

#5330 Revert "Improvify GitHub Action (#5312)"
  .github/workflows/auto-merge-bot.yml
  .github/workflows/auto-stagnate-bot.yml
  .github/workflows/ci-comment.yml
  .github/workflows/ci.yml
  .github/workflows/manual-bot-rerun.yml
  .github/workflows/rerun-bot-workflow-run.yml
  .github/workflows/stale.yml
Labels: ambiguous

#5271 Move EIP-712 to Last Call
  EIPS/eip-712.md
Labels: updateEIP

#5339 Add schemas "ethereum-web3://" and "eth-web3://"
  EIPS/eip-4804.md
Labels: updateEIP

#5338 Publish EIP-67 as withdrawn
  EIPS/eip-67.md
Labels: updateEIP

#4950 Entangled tokens
  EIPS/eip-4950.md
Labels: updateEIP

#5235 Fix SPDX license identifier in EIP-5007
  EIPS/eip-5007.md
  assets/eip-5007/contracts/ERC5007.sol
  assets/eip-5007/contracts/ERC5007Demo.sol
  assets/eip-5007/contracts/IERC5007.sol
Labels: ambiguous, updateEIP

#5343 EIP-5139: Switch from an array of providers to a map
  EIPS/eip-5139.md
Labels: updateEIP

#5233 Fix SPDX license identifier in EIP-4974
  EIPS/eip-4974.md
  assets/eip-4974/ERC4974.sol
  assets/eip-4974/IERC4974.sol
  assets/eip-4974/IERC4974Metadata.sol
Labels: ambiguous, updateEIP

#5346 Update eip-5114.md
  EIPS/eip-5114.md
Labels: updateEIP

#5347 Update eip-5114.md
  EIPS/eip-5114.md
Labels: updateEIP

#5348 Update eip-5114.md
  EIPS/eip-5114.md
Labels: updateEIP

#5354 Fix formatting eip refs
  EIPS/eip-4844.md
Labels: updateEIP

#5356 EIP-5139: Add validity requirement
  EIPS/eip-5139.md
Labels: updateEIP

#5359 Use uniform casing for keys
  EIPS/eip-5139.md
Labels: updateEIP

#5349 EIP-4626
  EIPS/eip-4626.md
Labels: updateEIP

#5342 Update Stale Bot
  .github/workflows/stale.yml
Labels: ambiguous

#5362 Attempt to fix the Automerge action
  .github/workflows/enable-automerge.yml
Labels: ambiguous

#5357 Add relevant labels to PRs automagically
  .github/workflows/auto-label-bot.yml
  .jekyll-labels.yml
Labels: ambiguous

#5219 PR-5219: Contract Resource Requests
  EIPS/eip-5219.md
  assets/eip-5219/IDecentralizedApp.sol
Labels: type: ERC, ambiguous, updateEIP

#5364 Revert "Update Stale Bot"
  .github/workflows/stale.yml
Labels: ambiguous

#5368 Add a word to clarify meaning in EIP-5267
  EIPS/eip-5267.md
Labels: type: ERC, updateEIP

#5365 Update Stale Bot Formatting
  .github/workflows/stale.yml
Labels: ambiguous

#5369 Fix ambiguity between EIP-1577 and HTTPS
  EIPS/eip-5139.md
Labels: type: ERC, updateEIP

#5355 Change EIP-5131 to use ENS TEXT records for signing resolution
  EIPS/eip-5131.md
Labels: type: ERC, updateEIP

#5358 EIP-5007: Change Status to Review
  EIPS/eip-5007.md
  assets/eip-5007/.gitignore
  assets/eip-5007/contracts/ERC5007.sol
  assets/eip-5007/contracts/ERC5007Composable.sol
  assets/eip-5007/contracts/ERC5007ComposableTest.sol
  assets/eip-5007/contracts/ERC5007Demo.sol
  assets/eip-5007/contracts/IERC5007.sol
  assets/eip-5007/contracts/IERC5007Composable.sol
  assets/eip-5007/migrations/1_initial_migration.js
  assets/eip-5007/package.json
  assets/eip-5007/test/test.js
Labels: type: ERC, ambiguous, updateEIP

#5371 Reverting behavior changes that didn't get editor approval.
  .github/workflows/stale.yml
Labels: ambiguous

#5372 Update EIP Bot
  .github/workflows/auto-merge-bot.yml
Labels: ambiguous

#5350 Submit EIP-3525 for review
  EIPS/eip-3525.md
  assets/eip-3525/contracts/ERC3525.sol
  assets/eip-3525/contracts/ERC3525Example.sol
  assets/eip-3525/contracts/ERC3525SlotApprovable.sol
  assets/eip-3525/contracts/ERC3525SlotEnumerable.sol
  assets/eip-3525/contracts/interface/IERC3525.sol
  assets/eip-3525/contracts/interface/IERC3525Metadata.sol
  assets/eip-3525/contracts/interface/IERC3525Receiver.sol
  assets/eip-3525/contracts/interface/IERC3525SlotApprovable.sol
  assets/eip-3525/contracts/interface/IERC3525SlotEnumerable.sol
  assets/eip-3525/test/test.ts
Labels: type: ERC, ambiguous, updateEIP

#5317 Adds DRAFT tag to items in review/stagnant/withdrawn when rendered.
  _layouts/eip.html
Labels: ambiguous

#5378 Update eip-2315.md
  EIPS/eip-2315.md
Labels: type: Core, updateEIP

#5382 Update eip-3779.md
  EIPS/eip-3779.md
Labels: type: Core, updateEIP

#5351 Move EIP-4987 to Review
  EIPS/eip-4987.md
  assets/eip-4987/Consumer.sol
  assets/eip-4987/IERC1155Holder.sol
  assets/eip-4987/IERC20Holder.sol
  assets/eip-4987/IERC721Holder.sol
  assets/eip-4987/Vault.sol
Labels: type: ERC, ambiguous, updateEIP

#5370 Corrects the name of EIPW.
  .github/workflows/ci.yml
Labels: ambiguous
