Repository ethereum/EIPs, pull requests merged in 2022-12, with the labels that each got.

#6073 Introduce the getRights() interface;
  EIPS/eip-5585.md
Labels: c-update, t-erc, s-draft

#6044 Update EIP-4750: Disallow dynamic jumps
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#6063 Update EIP-4750: Clarify stack overflow rules
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#6052 Update EIP-3540: Restrict EOF version in create
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6056 EIP-4200: Add RJUMPV
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6078 Update-4200: disallow empty jump table
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6079 Mark EIP-4750 and EIP-5450 as Review
  EIPS/eip-4750.md
  EIPS/eip-5450.md
Labels: c-status, t-core, s-review

#6072 Upgrade EIP-5773 to Review status
  EIPS/eip-5773.md
Labels: c-status, t-erc, s-review

#6074 Update EIP-6049: Move to review
  EIPS/eip-6049.md
Labels: c-status, t-meta, s-review

#6080 Update EIP-4750: Clarify RETF not cleaning the stack automatically
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#6082 EIP4844: Be explicit about precompile accepting canonical inputs
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6086 Clarifications to EIP-663
  EIPS/eip-663.md
Labels: c-update, t-core, s-draft

#6087 EIP-663: Mark for review
  EIPS/eip-663.md
Labels: c-status, t-core, s-review

#6090 EIP-4895: fix typo from #6089 to use correct type for withdrawal `amount`
  EIPS/eip-4895.md
Labels: c-update, t-core, s-review

#6085 Update EIP-6049: Move to Last Call
  EIPS/eip-6049.md
Labels: c-status, t-meta

#6092 Allows for multiple sales taxes
  EIPS/eip-5570.md
Labels: c-update, t-erc, s-draft

#6095 EIP-5646: Require only mutable state properties to be included in the state fingerprint
  EIPS/eip-5646.md
Labels: c-update, t-erc, s-review

#6096 Update EIP-4200: Add Test Cases for RJUMPV
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6098 incorporate thread feedback to EIP-1153
  EIPS/eip-1153.md
Labels: c-update, t-core

#6046 Add EIP-6046: Replace SELFDESTRUCT with DEACTIVATE
  EIPS/eip-6046.md
Labels: c-new, t-core, s-draft

#6100 Update EIP-4200: Add short new instruction summary
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6102 EIP-663: Fix some typos
  EIPS/eip-6046.md
Labels: c-update, t-core, s-draft

#6023 Update EIP-4750: Add JUMPF instruction
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#6101 Update EIP-5450: Add JUMPF simplification
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#6106 Update EIP-5247
  EIPS/eip-5247.md
Labels: c-update, t-erc, s-draft

#6109 Update EIP-5247 add assets
  EIPS/eip-5247.md
  assets/eip-5247/ProposalRegistry.sol
  assets/eip-5247/testProposalRegistry.ts
Labels: c-update, t-erc, s-draft

#6118 Update eip-1822.md
  EIPS/eip-1822.md
Labels: c-update, t-erc, s-stagnant

#6097 Update EIP-5646: Move to Last Call
  EIPS/eip-5646.md
Labels: c-status, t-erc

#6076 Update EIP-4519: Move to Final
  EIPS/eip-4519.md
Labels: c-update, t-erc

#6125 EIP-4750: Fix formatting
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#6124 Update EIP-4519: Move to Final
  EIPS/eip-4519.md
Labels: c-status, t-erc, s-final

#6111 EIP-4200: Do not suggest PC is deprecated
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6093 Add EIP-6093: Custom errors for commonly-used tokens
  EIPS/eip-6093.md
Labels: c-new, t-erc, s-draft

#6126 EIP-4200: Remove invalid comment about gas costs
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6053 Update EIP-3670: Drop "terminating" instruction restriction
  EIPS/eip-3540.md
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#6104 Update EIP-5375: Fix typo in JSON
  EIPS/eip-5375.md
Labels: c-update, t-erc, s-final

#5850 Add EIP-5850: Complex Numbers stored in Bytes32 types
  EIPS/eip-5850.md
Labels: c-new, t-erc, s-draft

#5135 Update EIP-4974: Community Feedback
  EIPS/eip-4974.md
  assets/eip-4974/ERC4974.sol
  assets/eip-4974/IERC4974.sol
Labels: c-update, t-erc, s-draft

#6140 Update ERC-5453
  EIPS/eip-5453.md
  assets/eip-5453/AERC5453.sol
  assets/eip-5453/EndorsableERC721.sol
  assets/eip-5453/IERC5453.sol
  assets/eip-5453/ThresholdMultiSigForwarder.sol
Labels: c-update, t-erc, s-draft

#6141 Update EIP-5453
  EIPS/eip-5453.md
Labels: c-update, t-erc, s-draft

#6059 Add EIP-6059: Parent-Governed Nestable Non-Fungible Tokens standard
  EIPS/eip-6059.md
  assets/eip-6059/contracts/INestable.sol
  assets/eip-6059/contracts/NestableToken.sol
  assets/eip-6059/contracts/mocks/ERC721Mock.sol
  assets/eip-6059/contracts/mocks/NestableTokenMock.sol
  assets/eip-6059/hardhat.config.ts
  assets/eip-6059/package.json
  assets/eip-6059/test/nestable.ts
Labels: c-new, t-erc, s-draft

#6152 Added security considerations and backwards compatibility texts for EIP-5023
  EIPS/eip-5023.md
Labels: c-update, t-erc, s-review

#6154 EIP-6059: Replace mermaid with images
  EIPS/eip-6059.md
  assets/eip-6059/img/eip-6059-abandon-child.png
  assets/eip-6059/img/eip-6059-nestable-tokens.png
  assets/eip-6059/img/eip-6059-reject-child.png
  assets/eip-6059/img/eip-6059-transfer-child-to-eoa.png
  assets/eip-6059/img/eip-6059-transfer-child-to-token.png
  assets/eip-6059/img/eip-6059-unnest-child.png
Labels: c-update, t-erc, s-draft

#6148 Update EIP-5192: Fix typo
  EIPS/eip-5192.md
Labels: c-update, t-erc, s-final

#6153 Update EIP-5023: Move to last call
  EIPS/eip-5023.md
Labels: c-status, t-erc

#6014 EIP-4938: Move to back to draft
  EIPS/eip-4938.md
Labels: c-status, t-networking, s-draft

#6062 Update EIP-5489: Move to final
  EIPS/eip-5489.md
Labels: c-status, t-erc, s-final

#6033 Update EIP-5757: Move to final
  EIPS/eip-5757.md
Labels: c-status, t-meta, s-final

#5744 Add EIP-5744: Latent Fungible Tokens
  EIPS/eip-5744.md
Labels: c-new, t-erc, s-draft

#6149 Update EIP-6093: Fix typos
  EIPS/eip-6093.md
Labels: c-update, t-erc, a-review, s-draft

#6015 Update EIP-2481: Move to final
  EIPS/eip-2481.md
Labels: c-status, t-networking, s-final

#6168 Remove terminating instructions validation
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#6173 EIP-6059: Add a note about inter-contract compatibility of EIP-6059
  EIPS/eip-6059.md
Labels: c-update, t-erc, s-draft

#6174 Update EIP-6049: Move to final
  EIPS/eip-6049.md
Labels: c-status, t-meta, s-final

#6176 Update EIP-5615: Change totalSupply behavior when exists is false
  EIPS/eip-5615.md
Labels: c-update, t-erc, s-review

#6161 Update EIP-1: Use updated list of EL clients
  EIPS/eip-1.md
Labels: c-update, t-process

#6179 Update EIP-5289: Add EIP-5568 signals, other extensibility, and security considerations
  EIPS/eip-5289.md
  assets/eip-5289/ERC5289Library.sol
  assets/eip-5289/example-popup.png
  assets/eip-5289/interfaces/IERC5289Library.sol
Labels: c-update, t-erc, s-draft

#6181 Update EIP-5507: Add Rationale stub
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#6182 Update EIP-5219: Fix small typo
  EIPS/eip-5219.md
Labels: c-update, t-erc, s-draft

#6184 Update EIP-5380: First update
  EIPS/eip-5380.md
Labels: c-update, t-erc, s-draft

#6110 Add EIP-6110: Supply validator deposits on chain
  EIPS/eip-6110.md
Labels: c-new, t-core, s-draft

#6191 Update EIP-5507: Fix typo (wei is a reserved name)
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#6156 3540,4570,5450: update EOF container format
  EIPS/eip-3540.md
  EIPS/eip-3670.md
  EIPS/eip-4750.md
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#6202 Fixes bug when replacing asset on sample implementation of 5773
  EIPS/eip-5773.md
  assets/eip-5773/contracts/MultiAssetToken.sol
  assets/eip-5773/test/multiasset.ts
Labels: c-update, t-erc, s-review

#6205 4750,5450: Specify stack overflow check only in CALLF
  EIPS/eip-4750.md
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#6206 Add EIP-6206: EOF - JUMPF instruction
  EIPS/eip-6206.md
Labels: c-new, t-core, s-draft

#6207 Update EIP-5115: Updates to interface based on community feedback
  EIPS/eip-5115.md
Labels: c-update, t-erc, s-draft

#6208 Update EIP-5115: Minor correction on interface
  EIPS/eip-5115.md
Labels: c-update, t-erc, s-draft

#6169 Update EIP-4337: fix typo desribed -> described
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6210 Clarify that initcode which fails validation still pays 3860 `initcode_cost`
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6172 Add EIP-6170: Cross-Chain Messaging Interface
  EIPS/eip-6170.md
Labels: c-new, t-erc, s-draft

#6177 Update EIP-5568: Move to review
  EIPS/eip-5568.md
Labels: c-status, t-interface, s-review

#6151 Update EIP-5606: Move to Last Call
  EIPS/eip-5606.md
Labels: c-status, t-erc

#6214 Update EIP-5380: Second Revision
  EIPS/eip-5380.md
Labels: c-update, t-erc, s-draft

#6123 Add EIP-6123: Smart Derivative Contract
  EIPS/eip-6123.md
  assets/eip-6123/README.md
  assets/eip-6123/contracts/ISDC.sol
  assets/eip-6123/contracts/SDC.sol
  assets/eip-6123/contracts/SDCToken.sol
  assets/eip-6123/doc/sample-tradedata-filestructure.xml
  assets/eip-6123/doc/sdc_livecycle_sequence_diagram.png
  assets/eip-6123/doc/sdc_trade_and_process_states.png
  assets/eip-6123/test/SDC.js
Labels: c-new, t-erc, s-draft

#5902 Add EIP-5902: Smart Contract Event Hooks
  EIPS/eip-5902.md
Labels: c-new, t-erc, s-draft

#6218 Update EIP-5507: Add interface IDs and use consistent formatting
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#6150 Add EIP-6150: Hierarchical NFTs
  EIPS/eip-6150.md
  assets/eip-6150/contracts/ERC-6150.sol
  assets/eip-6150/contracts/IERC-6150.sol
  assets/eip-6150/linux-hierarchy.png
  assets/eip-6150/website-hierarchy.png
Labels: c-new, t-erc, s-draft

#6051 Add EIP-6051: Private Key Encapsulation
  EIPS/eip-6051.md
Labels: c-new, t-interface, s-draft

#6217 Update EIP-5380: Move to Review
  EIPS/eip-5380.md
Labels: c-status, t-erc, s-review

#6223 Update EIP-6059: Fix multi-line list elements
  EIPS/eip-6059.md
Labels: c-update, t-erc, s-draft

#6225 EIP-5773: Fix formatting of ordered list in Rationale
  EIPS/eip-5773.md
Labels: c-update, t-erc, s-review

#6222 Updated EIP 3540's data section to new format
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6230 Update eip-3561.md
  EIPS/eip-3561.md
Labels: c-update, t-erc, s-review

#6232 Explained typesize in the v.1 header
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6233 Update EIP-4337 to latest working version
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6235 add material to EIP-5630
  EIPS/eip-5630.md
Labels: c-update, t-erc, s-draft

#6236 EIP-5630: small additional fixes.
  EIPS/eip-5630.md
Labels: c-update, t-erc, s-draft

#6237 Test cases: specify when contract creation fails in Valid initcode
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6240 Update EIP-5727: rename soul to owner; improve SlotEnumerable methods
  EIPS/eip-5727.md
  assets/eip-5727/contracts/ERC5727.sol
  assets/eip-5727/contracts/ERC5727Delegate.sol
  assets/eip-5727/contracts/ERC5727Enumerable.sol
  assets/eip-5727/contracts/ERC5727Example.sol
  assets/eip-5727/contracts/ERC5727Governance.sol
  assets/eip-5727/contracts/ERC5727Recovery.sol
  assets/eip-5727/contracts/ERC5727Shadow.sol
  assets/eip-5727/contracts/ERC5727SlotEnumerable.sol
  assets/eip-5727/contracts/interfaces/IERC5727.sol
  assets/eip-5727/contracts/interfaces/IERC5727Delegate.sol
  assets/eip-5727/contracts/interfaces/IERC5727Enumerable.sol
  assets/eip-5727/contracts/interfaces/IERC5727Governance.sol
  assets/eip-5727/contracts/interfaces/IERC5727Recovery.sol
  assets/eip-5727/contracts/interfaces/IERC5727SlotEnumerable.sol
  assets/eip-5727/pnpm-lock.yaml
Labels: c-update, t-erc, s-draft
