Repository ethereum/EIPs, pull requests merged in 2022-10, with the labels that each got.

#5738 update erc4337 to latest working version
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#5613 Update EIP-5553: Move to Review
  EIPS/eip-5553.md
Labels: c-status, t-erc, s-review

#5734 Update EIP-5643: Move to Review
  EIPS/eip-5643.md
Labels: c-status, t-erc, s-review

#5739 Update EIP-5679 Add Ref Impl
  EIPS/eip-5679.md
Labels: c-update, t-erc, s-review

#5740 Update EIP-5679: Add deployments of Ref Impl
  EIPS/eip-5679.md
Labels: c-update, t-erc, s-review

#5671 Update 4844: use clearer name for max fee value
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-draft

#5649 Synchronize EIP-4844 cryptography with consensus specs
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5746 Update EIP-5453
  EIPS/eip-5453.md
Labels: c-update, t-erc, s-draft

#5751 Update EIP-2135
  EIPS/eip-2135.md
Labels: c-update, t-erc, s-review

#5752 Add co-authors for EIP-5604
  EIPS/eip-5604.md
Labels: c-update, t-erc, s-draft

#5742 Update EIP-3475: Minor changes in description
  EIPS/eip-3475.md
  assets/eip-3475/ERC3475.sol
  assets/eip-3475/ERC3475.test.ts
  assets/eip-3475/interfaces/IERC3475.sol
Labels: c-update, t-erc, s-final

#5760 EIP-2135 update
  EIPS/eip-2135.md
Labels: c-update, t-erc, s-review

#5728 Add EIP-2294: Explicit bound to Chain ID size
  EIPS/eip-2294.md
Labels: c-new, t-core, a-review, s-draft

#5749 Add EIP-5749: The 'window.evmproviders' object
  EIPS/eip-5749.md
Labels: c-new, t-interface, s-draft

#5764 Update EIP-5173
  EIPS/eip-5173.md
Labels: c-update, t-erc, s-draft

#5466 Update EIP-1: Suggest that EIPs use RFC 8174 (updates RFC 2119)
  EIPS/eip-1.md
  eip-template.md
Labels: c-update, t-process, e-number, s-draft

#5231 Update EIP-4675: Fix SPDX license identifier
  EIPS/eip-4675.md
  assets/eip-4675/contracts/ERC20Token.sol
  assets/eip-4675/contracts/MFNFT.sol
  assets/eip-4675/contracts/NFT.sol
  assets/eip-4675/contracts/helper/Verifier.sol
  assets/eip-4675/contracts/interface/IERC20.sol
  assets/eip-4675/contracts/interface/IERC721.sol
  assets/eip-4675/contracts/interface/IMFNFT.sol
  assets/eip-4675/contracts/math/SafeMath.sol
  assets/eip-4675/package.json
Labels: c-update, t-erc, s-draft

#5729 Update EIP-5027 with cold/warm storage
  EIPS/eip-5027.md
  assets/eip-5027/0001-unlimit-code-size.patch
Labels: c-update, t-core, s-draft

#5774 Update EIP-5643 interface
  EIPS/eip-5643.md
Labels: c-update, t-erc, s-review

#5775 Fix typo in EIP-5643
  EIPS/eip-5643.md
Labels: c-update, t-erc, s-review

#5776 Final typo in EIP-5643
  EIPS/eip-5643.md
Labels: c-update, t-erc, s-review

#5777 ERC-4519: Change SmartNFT to EIP-4519 NFT
  EIPS/eip-4519.md
  assets/eip-4519/images/Fig5_rev.png
  assets/eip-4519/images/Figure4.jpg
Labels: c-update, t-erc, s-review

#5770 Update eip-5187.md
  EIPS/eip-5187.md
Labels: c-update, t-erc, s-draft

#5781 EIP4519: Change some images
  EIPS/eip-4519.md
  assets/eip-4519/images/Fig5_rev.png
  assets/eip-4519/images/Figure3.jpg
  assets/eip-4519/images/Figure4.jpg
Labels: c-update, t-erc, s-review

#5750 Add EIP-5750: Method with Extra Data
  EIPS/eip-5750.md
Labels: c-new, t-erc, s-draft

#5783 Update EIP-5187: update identifier for this interface
  EIPS/eip-5187.md
Labels: c-update, t-erc, s-draft

#5795 Update EIP-2294 for content
  EIPS/eip-2294.md
Labels: c-update, t-core, s-draft

#5655 CI: Disable certain labels from becoming stale
  .github/workflows/stale.yml
Labels: e-consensus

#5798 EIP-2535: Additions and improvements
  EIPS/eip-2535.md
  assets/eip-2535/Contributors.md
  assets/eip-2535/reference/EIP2535-Diamonds-Reference-Implementation.zip
Labels: c-update, t-erc

#5800 EIP-2535: small change
  EIPS/eip-2535.md
  assets/eip-2535/Contributors.md
  assets/eip-2535/reference/EIP2535-Diamonds-Reference-Implementation.zip
Labels: c-update, t-erc

#5607 Update EIP-2771: Add myself as an author and bring it up to date
  EIPS/eip-2771.md
Labels: c-status, t-erc, a-review, s-review

#5802 Make EIP-2535 Final
  EIPS/eip-2535.md
Labels: c-status, t-erc, s-final

#5790 Update EIP-5528: Move to final
  EIPS/eip-5528.md
Labels: c-status, t-erc, s-review

#5811 Fix interface identifier to 0x8d7bac72
  EIPS/eip-4973.md
  assets/eip-4973/ERC-4973.sol
Labels: c-update, t-erc, s-review

#5694 Update eip-template.md
  eip-template.md
Labels: c-update, t-process, e-number, s-draft

#5367 CI: Add Markdown Linter
  .github/workflows/ci.yml
  EIPS/eip-1.md
  README.md
  config/.markdownlint.yaml
  eip-template.md
  last-call.xml
Labels: c-update, t-process, e-number, s-draft

#5023 Add EIP-5023: Shareable non-transferable non-fungible token
  EIPS/eip-5023.md
Labels: c-new, t-erc, s-draft

#5815 Catch up to Yellow Paper
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5814 Update EIP-2315: Catch up to latest Yellow Paper
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5791 Add EIP-5791: Physical Backed Tokens
  EIPS/eip-5791.md
Labels: c-new, t-erc, s-draft

#5813 Update EIP-5375: Clarify address casing and move to Last Call
  EIPS/eip-5375.md
Labels: c-status, t-erc

#5529 Update EIP-5218: New version of the IC3 NFT License
  EIPS/eip-5218.md
  assets/eip-5218/ic3license/ic3license.pdf
  assets/eip-5218/ic3license/ic3license.tex
Labels: c-update, t-erc, w-stale, s-draft

#5809 Update EIP-5484: Move to Last Call
  EIPS/eip-5484.md
Labels: c-status, t-erc

#5832 EIP-5528 update MD contents in review state
  EIPS/eip-5528.md
Labels: c-update, t-erc, s-review

#5833 EIP-5006: typo fix
  EIPS/eip-5006.md
Labels: c-update, t-erc

#5835 Update EIP-4895: `validator_index` and more info around `index`
  EIPS/eip-4895.md
Labels: c-update, t-core, s-draft

#5822 Update EIP-4895: update status to review
  EIPS/eip-4895.md
Labels: c-status, t-core, s-review

#5823 Update EIP-2315: Yellow Paper link
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5837 Update EIP-5585: Introduce a “rights” attribute in UserRecord struct to identify diffe…
  EIPS/eip-5585.md
Labels: c-update, t-erc, s-draft

#5839 Update EIP-5216: Move to Last Call
  EIPS/eip-5216.md
Labels: c-status, t-erc

#5834 Update EIP-3525: verbiage improvements, typos
  EIPS/eip-3525.md
Labels: c-update, t-erc, s-final

#5842 Update EIP-5791: Change payload to be type bytes
  EIPS/eip-5791.md
Labels: c-update, t-erc, s-draft

#5763 Update EIP-2294: Move to Review
  EIPS/eip-2294.md
Labels: c-status, t-core, s-review

#5829 Update EIP-4955: Move to review
  EIPS/eip-4955.md
Labels: c-status, t-erc, s-review

#5841 Update EIP-5528: Move to Last Call
  EIPS/eip-5528.md
Labels: c-status, t-erc

#5759 Update EIP-5679: Move to Last Call
  EIPS/eip-5679.md
Labels: c-status, t-erc

#5845 Update EIP-5679: Update Last Call Deadline
  EIPS/eip-5679.md
Labels: c-update, t-erc

#5758 Update EIP-5732: Move to Last Call
  EIPS/eip-5732.md
Labels: c-status, t-erc

#5846 nit
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5848 Update EIP-5606: Remove unnecessary variables from a struct a function
  EIPS/eip-5606.md
  assets/eip-5606/contracts/MultiverseNFT.sol
Labels: c-update, t-erc, s-draft

#5784 Update EIP-4519: Fix typos in figures 4 and 5
  EIPS/eip-4519.md
  assets/eip-4519/images/Fig5_rev.png
  assets/eip-4519/images/Figure4.jpg
  assets/eip-4519/images/Figure5.jpg
Labels: c-update, t-erc, s-review

#5086 Update EIP-1271: Fix example
  EIPS/eip-1271.md
Labels: c-update, t-erc, s-final

#5718 Update EIP-2315: Example bytecode fix
  EIPS/eip-2315.md
Labels: c-update, t-core, a-review, s-review

#3848 Update EIP-1202: Resolve new EIPW and bring this EIP back to live
  EIPS/eip-1202.md
Labels: c-update, t-erc, s-draft

#5808 Update EIP-5164: Move to review
  EIPS/eip-5164.md
Labels: c-status, t-erc, s-review

#5785 Update EIP-5750: Move to Review
  EIPS/eip-5750.md
Labels: c-status, t-erc, s-review

#5858 Update EIP-5732 to improve backward compatibility and address collaborator suggestions
  EIPS/eip-5732.md
Labels: c-update, t-erc

#5792 Add EIP-5792: Wallet Abstract Transaction Send API
  EIPS/eip-5792.md
Labels: c-new, t-interface, s-draft

#5860 [EIP-4844] Fix Linting
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft
