Repository ethereum/EIPs, pull requests merged in 2022-09, with the labels that each got.

#5563 Update EIP-5521: Add more descriptions
  EIPS/eip-5521.md
Labels: c-update, t-erc, s-draft

#5003 Add EIP-5003: Insert Code into EOAs with `AUTHUSURP`
  EIPS/eip-5003.md
Labels: c-new, t-core, s-draft

#5560 Add EIP-5560: Redeemable NFTs
  EIPS/eip-5560.md
Labels: c-new, t-erc, s-draft

#5574 fix typos
  EIPS/eip-3525.md
Labels: c-update, t-erc

#5575 wording "intellectual property"
  EIPS/eip-5553.md
Labels: c-update, t-erc, s-draft

#5213 Update EIP-4907: Cleanup trailing whitespaces
  EIPS/eip-4907.md
  assets/eip-4907/contracts/ERC4907.sol
  assets/eip-4907/contracts/ERC4907Demo.sol
  assets/eip-4907/contracts/IERC4907.sol
  assets/eip-4907/migrations/1_initial_migration.js
  assets/eip-4907/test/test.js
  assets/eip-4907/truffle-config.js
Labels: c-update, t-erc, s-final

#5507 Add EIP-5507: Refundable NFTs
  EIPS/eip-5507.md
Labels: c-new, t-erc, s-draft

#5380 Add EIP-5380: EIP-721 Entitlement Extension
  EIPS/eip-5380.md
Labels: c-new, t-erc, s-draft

#5571 Update EIP-5216: Move to Review
  EIPS/eip-5216.md
  assets/eip-5216/ERC1155ApprovalByAmount.sol
Labels: c-status, t-erc, s-review

#4824 Add EIP-4824: Common Interfaces for DAOs
  EIPS/eip-4824.md
  assets/eip-4824/daostar_context.jsonld
  assets/eip-4824/daostar_ontology.ttl
Labels: c-new, t-erc, s-draft

#5590 Lots of refactoring and port to pseudo-python
  EIPS/eip-2315.md
Labels: c-update, t-core, s-draft

#5592 Grammar & magicians link fix based on EIP number
  EIPS/eip-5553.md
Labels: c-update, t-erc, s-draft

#5595 no external links
  EIPS/eip-2315.md
Labels: c-update, t-core, s-draft

#5566 Add EIP-5564: Stealth Address Wallets
  EIPS/eip-5564.md
  assets/eip-5564/EllipticCurve.sol
  assets/eip-5564/gnosisSafeModule.sol
  assets/eip-5564/minimal_poc.ipynb
Labels: c-new, t-erc, s-draft

#5478 Add EIP-5478: CREATE2COPY Opcode
  EIPS/eip-5478.md
Labels: c-new, t-core, w-response, s-draft

#5252 Add EIP-5252: Account-bound Finance
  EIPS/eip-5252.md
  assets/eip-5252/.gitignore
  assets/eip-5252/README.md
  assets/eip-5252/contracts/ABT.sol
  assets/eip-5252/contracts/ERC721A.sol
  assets/eip-5252/contracts/Factory.sol
  assets/eip-5252/contracts/Finance.sol
  assets/eip-5252/contracts/Manager.sol
  assets/eip-5252/contracts/governance/Governor.sol
  assets/eip-5252/contracts/governance/Influencer.sol
  assets/eip-5252/contracts/governance/Vote.sol
  assets/eip-5252/contracts/interfaces/IABT.sol
  assets/eip-5252/contracts/interfaces/IDescriptor.sol
  assets/eip-5252/contracts/interfaces/IERC20Minimal.sol
  assets/eip-5252/contracts/interfaces/IFactory.sol
  assets/eip-5252/contracts/interfaces/IFinance.sol
  assets/eip-5252/contracts/interfaces/IInfluencer.sol
  assets/eip-5252/contracts/interfaces/IManager.sol
  assets/eip-5252/contracts/interfaces/IWETH.sol
  assets/eip-5252/contracts/libraries/CloneFactory.sol
  assets/eip-5252/contracts/libraries/Initializable.sol
  assets/eip-5252/contracts/libraries/SVG.sol
  assets/eip-5252/contracts/libraries/TransferHelper.sol
  assets/eip-5252/hardhat.config.ts
  assets/eip-5252/media/media.svg
  assets/eip-5252/package.json
  assets/eip-5252/scripts/deploy.ts
  assets/eip-5252/test/Lock.ts
  assets/eip-5252/tsconfig.json
Labels: c-new, t-erc, s-draft

#5599 Incorporate @xinbenlv review
  EIPS/eip-2315.md
Labels: c-update, t-core, s-draft

#5239 Update EIP-5005: Move status to "Review"
  EIPS/eip-5005.md
Labels: c-status, t-erc, s-review

#5591 Update EIP-3525: Move to final
  EIPS/eip-3525.md
Labels: c-status, t-erc, s-final

#5602 Error that passed the review stage.
  EIPS/eip-5516.md
  assets/eip-5516/IERC5516.sol
Labels: c-update, t-erc, s-review

#5605 Update EIP-5484: Move to Review
  EIPS/eip-5484.md
Labels: c-status, t-erc, s-review

#5604 Add EIP-5604: NFT Lien
  EIPS/eip-5604.md
Labels: c-new, t-erc, s-draft

#5611 Review EIP-5553 : Representing IP and its Royalty Structure
  EIPS/eip-5553.md
Labels: c-update, t-erc, s-draft

#5609 Update EIP-5528: Move to Review
  EIPS/eip-5528.md
Labels: c-status, t-erc, s-review

#4910 Add EIP-4910: Royalty Bearing NFTs
  EIPS/eip-4910.md
  assets/eip-4910/eip-4910-print-families.png
  assets/eip-4910/eip-4910-royalties.png
Labels: c-new, t-erc, s-draft

#5610 Update EIP-1418: More progress // and formatting
  EIPS/eip-1418.md
Labels: c-update, t-core, s-draft

#5353 Update EIP-4844: Remove system contract concept
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5629 EIP-4844: fix typo
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5637 Fix eip5516 error
  EIPS/eip-5516.md
  assets/eip-5516/IERC5516.sol
Labels: c-update, t-erc, s-review

#5643 Add EIP-5643: Subscription NFTs
  EIPS/eip-5643.md
Labels: c-new, t-erc, s-draft

#5644 fix(5643): typo in specification
  EIPS/eip-5643.md
Labels: c-update, t-erc, s-draft

#5645 fix(4563): missing parameter natspec
  EIPS/eip-5643.md
Labels: c-update, t-erc, s-draft

#5636 fix(4844): leave G_transaction at 21000
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5547 Update EIP-3475: Reference Implementation Typo Fixes
  EIPS/eip-3475.md
  assets/eip-3475/interfaces/IERC3475.sol
Labels: c-update, t-erc, a-review, s-final

#5635 Add EIP-5635: NFT Licensing Agreement Standard
  EIPS/eip-5635.md
Labels: c-new, t-erc, s-draft

#5638 Update EIP-2315: Ready for Review
  EIPS/eip-2315.md
Labels: c-status, t-core, s-review

#5539 Add EIP-5539: Revocation List Registry
  EIPS/eip-5539.md
Labels: c-new, t-erc, s-draft

#5658 Update EIP-4844: Add @Inphi to author list
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5625 Add EIP-5625: NFT Metadata JSON Schema dStorage Extension
  EIPS/eip-5625.md
Labels: c-new, t-erc, s-draft

#5630 Add EIP-5630: Encryption and Decryption
  EIPS/eip-5630.md
Labels: c-new, t-erc, s-draft

#5657 CI: Update Stale Bot
  .github/workflows/stale.yml
Labels: e-review

#5669 Update EIP-5289: Fix false positive codespell error
  EIPS/eip-5289.md
Labels: c-update, t-erc, s-draft

#5668 CI: Only run codespell on changed files
  .github/workflows/ci.yml
  config/.codespell-whitelist
Labels: e-review

#5642 Update EIP-1: Fix that stupid Jekyll/Markdown bug
  EIPS/eip-1.md
Labels: c-update, t-process

#5554 Add EIP-5554: NFT Legal Use, Sharing, Repurposing, and Remixing
  EIPS/eip-5554.md
Labels: c-new, t-erc, w-stale, s-draft

#5639 Add EIP-5639: Delegation Registry
  EIPS/eip-5639.md
  assets/eip-5639/DelegationRegistry.sol
  assets/eip-5639/IDelegationRegistry.sol
Labels: c-new, t-erc, s-draft

#5556 Update EIP-4834: Move Last Call Deadline
  EIPS/eip-4834.md
  assets/eip-4834/IDomain.sol
  assets/eip-4834/IDomainAccessControl.sol
  assets/eip-4834/IDomainEnumerable.sol
  assets/eip-4834/NaiveDomain.sol
  assets/eip-4834/OwnableDomain.sol
Labels: c-update, t-erc

#5570 Add EIP-5570: Digital Receipt Non-Fungible Tokens
  EIPS/eip-5570.md
Labels: c-new, t-erc, s-draft

#5615 Add EIP-5615: EIP-1155 Supply Extension
  EIPS/eip-5615.md
Labels: c-new, t-erc, s-draft

#5672 fix signature to use `Header` rather than `ExecState`
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5673 Reformatting EIP2535
  EIPS/eip-2535.md
  assets/eip-2535/reference/.gitattributes
  assets/eip-2535/reference/.gitignore
  assets/eip-2535/reference/.prettierignore
  assets/eip-2535/reference/.prettierrc
  assets/eip-2535/reference/LICENSE
  assets/eip-2535/reference/README.md
  assets/eip-2535/reference/contracts/Diamond.sol
  assets/eip-2535/reference/contracts/facets/DiamondCutFacet.sol
  assets/eip-2535/reference/contracts/facets/DiamondLoupeFacet.sol
  assets/eip-2535/reference/contracts/facets/OwnershipFacet.sol
  assets/eip-2535/reference/contracts/facets/Test1Facet.sol
  assets/eip-2535/reference/contracts/facets/Test2Facet.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamond.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamondCut.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamondLoupe.sol
  assets/eip-2535/reference/contracts/interfaces/IERC165.sol
  assets/eip-2535/reference/contracts/interfaces/IERC173.sol
  assets/eip-2535/reference/contracts/libraries/LibDiamond.sol
  assets/eip-2535/reference/contracts/upgradeInitializers/DiamondInit.sol
  assets/eip-2535/reference/contracts/upgradeInitializers/DiamondMultiInit.sol
  assets/eip-2535/reference/hardhat.config.js
  assets/eip-2535/reference/package.json
  assets/eip-2535/reference/scripts/deploy.js
  assets/eip-2535/reference/scripts/libraries/diamond.js
  assets/eip-2535/reference/test/cacheBugTest.js
  assets/eip-2535/reference/test/diamondTest.js
  assets/eip-2535/storage-examples/AppStorage.sol
  assets/eip-2535/storage-examples/DiamondStorage.sol
Labels: c-update, t-erc

#5670 Update EIP-5528: Move to Last Call
  EIPS/eip-5528.md
Labels: c-status, t-erc

#5654 Update EIP-5192: Move to Final
  EIPS/eip-5192.md
Labels: c-status, t-erc, s-final

#5681 Update eip-2315.md
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5683 Update eip-2315.md
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5684 eip-2315.md formatting nits
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5685 Update eip-2315.md
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#3975 Update EIP-2982: Move to Final
  EIPS/eip-2982.md
  assets/eip-2982/2982-issuance.png
  assets/eip-2982/arxiv-1710.09437-Casper-the-Friendly-Finality-Gadget.pdf
  assets/eip-2982/arxiv-1809.09044-Fraud-and-Data-Availability-Proofs--Maximising-Light-Client-Security-and-Scaling-Blockchains-with-Dishonest-Majorities.pdf
  assets/eip-2982/arxiv-2003.03052-Combining-GHOST-and-Casper.pdf
  assets/eip-2982/ef-Discouragement-Attacks.pdf
  assets/eip-2982/iacr-2015-702-Demystifying-Incentives-in-the-Consensus-Computer.pdf
Labels: c-status, t-informational, w-response, s-final, e-consensus

#5679 Add EIP-5679: Token Minting and Burning
  EIPS/eip-5679.md
Labels: c-new, t-erc, s-draft

#5690 Update EIP-5081: Add Kevin as a co-author
  EIPS/eip-5081.md
Labels: c-update, t-core, s-draft

#5688 Update EIP-5646: Move to review
  EIPS/eip-5646.md
Labels: c-status, t-erc, s-review

#5612 Update EIP-5496: Move to review
  EIPS/eip-5496.md
  assets/eip-5496/test/test.js
  assets/eip-5496/test/testCloneable.js
Labels: c-status, t-erc, s-review

#5689 Update EIP-2718: Fix the spelling of transaction
  EIPS/eip-2718.md
Labels: c-update, t-core, s-final

#5661 EIP-4399: move to Final
  EIPS/eip-4399.md
Labels: c-status, t-core, s-final, e-blocked

#5660 EIP-3675: move to Final
  EIPS/eip-3675.md
Labels: c-status, t-core, s-final, e-blocking, w-dependency

#5626 Update EIP-4910: Move from Draft to Review
  EIPS/eip-4910.md
Labels: c-status, t-erc, s-review

#5569 Configuration: Add .DS_Store to .gitignore
  .gitignore
Labels: e-review, e-blocking

#5502 Update EIP-1: Adds @xinbenlv as an EIP Editor
  .github/workflows/auto-review-bot.yml
Labels: e-consensus

#5666 Update EIP-4750: Add reference implementation
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#5704 Update eip-2315.md
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5598 Update EIP-4393: Gas Savings
  EIPS/eip-4393.md
Labels: c-update, t-erc, s-draft

#5664 Update EIP-3670: Use exceptions with error messages in reference code
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#5665 Update EIP-4200: Use exceptions with error messages in reference code
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#5693 Update EIP-2135: Move to Review
  EIPS/eip-2135.md
Labels: c-status, t-erc, s-review

#5506 Update EIP-2612: Move to Last Call
  EIPS/eip-2612.md
Labels: c-status, t-erc, a-review

#5164 Add EIP-5164: Cross-Chain Execution
  EIPS/eip-5164.md
Labels: c-new, t-erc, s-draft

#5710 Update EIP-3525: Add README file to explain the purpose of the code
  EIPS/eip-3525.md
  assets/eip-3525/README.md
Labels: c-update, t-erc, s-final

#5676 Update EIP-2535: Fix Internal Link to Reference Implementation
  EIPS/eip-2535.md
  assets/eip-2535/reference/.gitattributes
  assets/eip-2535/reference/.gitignore
  assets/eip-2535/reference/.prettierignore
  assets/eip-2535/reference/.prettierrc
  assets/eip-2535/reference/Diamond.sol
  assets/eip-2535/reference/EIP2535-Diamonds-Reference-Implementation.zip
  assets/eip-2535/reference/LICENSE
  assets/eip-2535/reference/README.md
  assets/eip-2535/reference/contracts/Diamond.sol
  assets/eip-2535/reference/contracts/facets/DiamondCutFacet.sol
  assets/eip-2535/reference/contracts/facets/DiamondLoupeFacet.sol
  assets/eip-2535/reference/contracts/facets/OwnershipFacet.sol
  assets/eip-2535/reference/contracts/facets/Test1Facet.sol
  assets/eip-2535/reference/contracts/facets/Test2Facet.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamond.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamondCut.sol
  assets/eip-2535/reference/contracts/interfaces/IDiamondLoupe.sol
  assets/eip-2535/reference/contracts/interfaces/IERC165.sol
  assets/eip-2535/reference/contracts/interfaces/IERC173.sol
  assets/eip-2535/reference/contracts/libraries/LibDiamond.sol
  assets/eip-2535/reference/contracts/upgradeInitializers/DiamondInit.sol
  assets/eip-2535/reference/contracts/upgradeInitializers/DiamondMultiInit.sol
  assets/eip-2535/reference/hardhat.config.js
  assets/eip-2535/reference/package.json
  assets/eip-2535/reference/scripts/deploy.js
  assets/eip-2535/reference/scripts/libraries/diamond.js
  assets/eip-2535/reference/test/cacheBugTest.js
  assets/eip-2535/reference/test/diamondTest.js
Labels: c-update, t-erc

#5713 EIP2535: Improved descriptions of some things
  EIPS/eip-2535.md
Labels: c-update, t-erc

#5714 EIP2535: Fixed misspelling, tweaked wording
  EIPS/eip-2535.md
Labels: c-update, t-erc

#5715 EIP2535: Updated dependencies
  EIPS/eip-2535.md
  assets/eip-2535/reference/EIP2535-Diamonds-Reference-Implementation.zip
Labels: c-update, t-erc

#5716 reason for using an on chain token for digital receipts explained
  EIPS/eip-5570.md
Labels: c-update, t-erc, s-draft

#5706 Update EIP-1: Fix outdated links
  EIPS/eip-1.md
Labels: c-update, t-process, e-review

#5723 Update eip-2315.md
  EIPS/eip-2315.md
Labels: c-update, t-core, s-review

#5709 Update EIP-3525
  EIPS/eip-3525.md
  assets/eip-3525/contracts/ERC3525.sol
Labels: c-update, t-erc, s-final

#5726 EIP-4883: remove rights requirement
  EIPS/eip-4883.md
Labels: c-update, t-erc, s-draft

#5692 Update EIP-5679: Move to Review
  EIPS/eip-5679.md
Labels: c-status, t-erc, s-review

#5730 EIP-2535: Made clear facets do not have to be reusable
  EIPS/eip-2535.md
Labels: c-update, t-erc

#5565 Update README.md: improved grammar
  README.md
Labels: e-review
