Repository ethereum/EIPs, pull requests merged in 2022-08, with the labels that each got.

#5192 Add EIP-5192 - Minimal Soulbound NFTs
  EIPS/eip-5192.md
Labels: type: ERC, updateEIP

#5209 Adjust EIP-4973 interface to add `function give(...)` and `function take(...)`
  EIPS/eip-4973.md
  assets/eip-4973/ERC-4973.sol
Labels: type: ERC, ambiguous, updateEIP

#5386 Adjust framing in EIP-5192 spec
  EIPS/eip-5192.md
Labels: type: ERC, updateEIP

#5390 Hash `string tokenURI`
  EIPS/eip-4973.md
Labels: type: ERC, updateEIP

#5360 Change Stale Thresholds
  .github/workflows/stale.yml
Labels: ambiguous

#5389 Promote EIP-5313 to last call
  EIPS/eip-5313.md
Labels: type: ERC, updateEIP

#5397 Revert "Change Stale Thresholds"
  .github/workflows/stale.yml
Labels: ambiguous

#5405 Update name for EIP-5131 and fix documentation for usage of TEXT records
  EIPS/eip-5131.md
Labels: type: ERC, updateEIP

#5410 Add tested EIP-712/2098 compact signature script
  EIPS/eip-4973.md
  assets/eip-4973/generateSignature.mjs
  assets/eip-4973/generateSignature_test.mjs
Labels: type: ERC, ambiguous, updateEIP

#5401 Update Label Action
  .github/workflows/auto-label-bot.yml
Labels: ambiguous

#5416 Update eip-5131 name
  EIPS/eip-5131.md
Labels: type: ERC, updateEIP

#5335 Resurrect EIP-831 and add "eth" shorhand
  EIPS/eip-831.md
Labels: type: ERC, updateEIP

#4888 EIP-4883 Composable SVG NFT
  EIPS/eip-4883.md
Labels: type: ERC, updateEIP

#5418 Removes MicahZoltu as EIP editor.
  .github/workflows/auto-merge-bot.yml
  EIPS/eip-1.md
Labels: type: EIP1 (Process), ambiguous, updateEIP

#5428 Move Jekyll Label Action Config to Config Folder
  .github/workflows/auto-label-bot.yml
  config/.jekyll-labels.yml
Labels: ambiguous

#5430 Update eip-4804.md
  EIPS/eip-4804.md
Labels: type: ERC, updateEIP

#5432 Update EIP-831 to Review
  EIPS/eip-831.md
Labels: type: ERC, updateEIP

#5289 PR-5289: Ethereum Notary Interface
  EIPS/eip-5289.md
  assets/eip-5289/ERC5289Library.sol
  assets/eip-5289/interfaces/IERC165.sol
  assets/eip-5289/interfaces/IERC5289Library.sol
Labels: type: ERC, ambiguous, updateEIP

#5375 EIP-5375 - NFT Authorship.md
  EIPS/eip-5375.md
Labels: type: ERC, updateEIP

#5400 Fix EIP Bot
  .github/CODEOWNERS
  .github/workflows/auto-merge-bot.yml
  .github/workflows/auto-review-bot.yml
  .github/workflows/auto-review-trigger.yml
  .github/workflows/enable-automerge.yml
  .github/workflows/manual-bot-rerun.yml
  .github/workflows/rerun-bot-pull-request-review.yml
  .github/workflows/rerun-bot-workflow-run.yml
  EIPS/eip-5069.md
Labels: type: Informational, type: EIP1 (Process)

#5440 Add Name to Label Bot
  .github/workflows/auto-label-bot.yml
Labels: ambiguous

#5412 Add Waiting on EIP Number Label
  config/.jekyll-labels.yml
Labels: ambiguous

#5442 Update EIP Bot
  .github/workflows/auto-review-bot.yml
Labels: ambiguous

#5258 EIP-4750: Make type section optional
  EIPS/eip-4750.md
Labels: type: Core, updateEIP, waiting: EIP number

#5446 Fix "waiting: EIP number" label
  config/.jekyll-labels.yml
Labels: ambiguous

#5413 Use New Classification Labels
  config/.jekyll-labels.yml
Labels: ambiguous

#5433 Move EIP-712 to Final
  EIPS/eip-712.md
Labels: type: Interface, updateEIP

#5436 Move EIP-2330 to Draft status
  EIPS/eip-2330.md
  assets/eip-2330/Extsload.sol
Labels: type: Core, ambiguous, updateEIP, waiting: EIP number

#5448 Fix the waiting on EIP number label again
  config/.jekyll-labels.yml
Labels: ambiguous

#5449 Remove safeTransferFrom methods
  EIPS/eip-3525.md
  assets/eip-3525/contracts/ERC3525.sol
  assets/eip-3525/contracts/interface/IERC3525.sol
Labels: type: ERC, ambiguous, updateEIP, classification: update EIP

#5451 Fix waiting for EIP number label again again
  config/.jekyll-labels.yml
Labels: ambiguous

#5411 Move 4973 to review
  EIPS/eip-4973.md
Labels: type: ERC, updateEIP

#5409 EIP-1155 Non-Fungible Token extension
  EIPS/eip-5409.md
Labels: type: ERC, updateEIP, classification: new EIP

#5458 correct broken links
  EIPS/eip-3525.md
Labels: type: ERC, updateEIP, classification: update EIP

#5460 EIP-4400, fix typo, change ConsumEIPhanged to ConsumerChanged
  EIPS/eip-4400.md
Labels: type: ERC, updateEIP, classification: update EIP

#5269 EIP-5269: ERC Interface Detection
  EIPS/eip-5269.md
Labels: type: ERC, updateEIP, classification: new EIP

#5476 Remove gitter link
  index.html
Labels: ambiguous

#5459 EIP-5192: add event LockingStatusChanged(uint256 tokenId, bool status)
  EIPS/eip-5192.md
Labels: type: ERC, updateEIP, classification: update EIP

#5477 Update eip-5313.md
  EIPS/eip-5313.md
Labels: type: ERC, updateEIP, classification: EIP status change

#5482 Re-removes Micah from editor list.
  .github/workflows/auto-review-bot.yml
Labels: ambiguous

#5480 Update label bot
  .github/workflows/auto-label-bot.yml
Labels: ambiguous

#5467 Improve SEO
  _includes/head.html
  assets/css/style.scss
Labels: ambiguous

#5483 Fix Codespell
  .github/workflows/ci.yml
Labels: ambiguous

#5481 Update EIP-Bot
  .github/workflows/auto-review-bot.yml
Labels: ambiguous

#5485 EIP-5485: Legitimacy, Jurisdiction and Sovereignty
  EIPS/eip-5485.md
Labels: type: ERC, classification: new EIP

#5473 EIP-3675 to Last Call
  EIPS/eip-3675.md
Labels: type: Core, classification: EIP status change

#5491 Several revises
  EIPS/eip-3525.md
Labels: type: ERC, classification: update EIP

#5472 EIP-4399 to Last Call
  EIPS/eip-4399.md
Labels: type: Core, classification: EIP status change

#5499 Revisions to EIP-5485
  EIPS/eip-5485.md
Labels: type: ERC, classification: update EIP

#5345 EIP-5345 Walletconnect Silent-Signing Extension
  EIPS/eip-5345.md
  assets/eip-5345/walletconnect-flow.png
Labels: type: Interface, classification: new EIP

#5050 EIP-5050: Interactive NFTs with Modular Environments
  EIPS/eip-5050.md
  assets/eip-5050/ActionsSet.sol
  assets/eip-5050/ERC5050.sol
  assets/eip-5050/ERC5050Receiver.sol
  assets/eip-5050/ERC5050Sender.sol
  assets/eip-5050/ERC5050State.sol
  assets/eip-5050/ExampleStateContract.sol
  assets/eip-5050/ExampleToken2Token.sol
  assets/eip-5050/IERC5050.sol
Labels: type: ERC, classification: new EIP

#5450 Add EIP-5450: EOF - Stack Validation
  EIPS/eip-5450.md
Labels: type: Core, classification: new EIP

#5514 EIP-5139: add note about the prime-provider problem
  EIPS/eip-5139.md
Labels: type: ERC, classification: update EIP

#5497 Move EIP-3525 to last call
  EIPS/eip-3525.md
Labels: type: ERC, waiting: walidator to pass, classification: EIP status change

#5385 Eip 3475 final patch
  EIPS/eip-3475.md
  assets/eip-3475/ERC3475.sol
  assets/eip-3475/ERC3475.test.ts
  assets/eip-3475/Metadata.md
  assets/eip-3475/interfaces/IERC3475.sol
Labels: type: ERC, waiting: author to review, classification: EIP status change

#5393 Update eip-4626.md
  EIPS/eip-4626.md
Labels: type: ERC, waiting: EIP number

#5465 Change EIP-5375 (NFT Author Information and Consent) status to "Review"
  EIPS/eip-5375.md
Labels: type: ERC, classification: EIP status change

#5527 Update eip-4972.md
  EIPS/eip-4972.md
Labels: type: ERC, waiting: walidator to pass, classification: update EIP

#5531 Revise of preamble
  EIPS/eip-3525.md
Labels: type: ERC, classification: update EIP

#5463 Add adoptable field
  EIPS/eip-1.md
  eip-template.md
Labels: type: Meta, type: EIP1 (Process), waiting: EIP number, classification: update EIP

#5526 EIP-4750: Change bullet point list for markdown rendering
  EIPS/eip-4750.md
Labels: type: Core, classification: update EIP

#5443 EIP-4881: DepositTreeSnapshot Refactor
  EIPS/eip-4881.md
  assets/eip-4881/deposit_snapshot.py
  assets/eip-4881/deposit_tree_evolution.png
  assets/eip-4881/eip_4881.py
  assets/eip-4881/test_cases.yaml
  assets/eip-4881/test_deposit_snapshot.py
Labels: type: Interface, waiting: walidator to pass, classification: update EIP

#5484 EIP5484 Draft submit
  EIPS/eip-5484.md
Labels: type: ERC, waiting: walidator to pass, classification: new EIP

#5532 Revert "Add adoptable field (#5463)"
  EIPS/eip-1.md
  eip-template.md
Labels: type: Meta, type: EIP1 (Process), waiting: EIP number, classification: update EIP

#5489 ADD: EIP-5489 NFT Hyperlink Extension
  EIPS/eip-5489.md
  assets/eip-5489/contracts/ERC5489.sol
  assets/eip-5489/contracts/IERC5489.sol
Labels: type: ERC, classification: new EIP

#5058 EIP-5058:Lockable ERC-721 Standard
  EIPS/eip-5058.md
  assets/eip-5058/ERC5058.sol
  assets/eip-5058/IERC5058.sol
  assets/eip-5058/extensions/ERC5058Bound.sol
  assets/eip-5058/factory/ERC5058Factory.sol
  assets/eip-5058/factory/ERC721Bound.sol
  assets/eip-5058/factory/IERC5058Factory.sol
  assets/eip-5058/factory/IERC721Bound.sol
  assets/eip-5058/mock/EIP5058Mock.sol
  assets/eip-5058/test/test.ts
Labels: type: ERC, classification: new EIP

#5505 adding a EIP draft for ERC1155 asset backed NFT extension
  EIPS/eip-5505.md
Labels: type: ERC, waiting: walidator to pass, classification: new EIP

#5516 eip-5516 draft
  EIPS/eip-5516.md
  assets/eip-5516/ERC5516.sol
  assets/eip-5516/IERC5516.sol
Labels: type: ERC, waiting: htmlproofer to pass, classification: new EIP

#5521 EIP-5521: Referable NFT (rNFT)
  EIPS/eip-5521.md
Labels: type: ERC, waiting: htmlproofer to pass, classification: new EIP

#5535 EIP-5450: Add rationale, more clarifications and update authors
  EIPS/eip-5450.md
Labels: type: Core, classification: update EIP

#5534 Fix typos reported by codespell
  EIPS/eip-1967.md
  EIPS/eip-225.md
  EIPS/eip-2470.md
  EIPS/eip-2494.md
  EIPS/eip-3000.md
  EIPS/eip-3156.md
  EIPS/eip-3368.md
  EIPS/eip-3584.md
  EIPS/eip-3607.md
  EIPS/eip-5345.md
  EIPS/eip-5484.md
  EIPS/eip-969.md
  assets/eip-3448/MetaProxyFactory.sol
  assets/eip-4886/contracts/ProxyRegister.sol
Labels: type: Core, type: ERC, type: Interface, waiting: walidator to pass, classification: update EIP

#5536 Use new label format
  .github/workflows/post-ci.yml
  .github/workflows/stale.yml
  config/.jekyll-labels.yml
Labels: waiting: editor to review

#5520 Fix rerun CI trigger
  .github/workflows/ci-rerun-trigger.yml
Labels: bug, e-review

#5524 Update Bug Report Template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: e-review

#5541 Fix Bug Report Template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: bug

#5540 CI: Fix typo in labels & add missing labels
  config/.jekyll-labels.yml
Labels: bug, e-review

#5543 Update EIP-5007: Move Status to Last Call
  EIPS/eip-5007.md
Labels: c-status, t-erc"

#5537 Update EIP-5006: Update interface and implementation
  EIPS/eip-5006.md
  assets/eip-5006/contracts/ERC5006.sol
  assets/eip-5006/contracts/ERC5006Demo.sol
  assets/eip-5006/contracts/IERC5006.sol
  assets/eip-5006/test/test.ts
Labels: a-review

#5542 Update EIP-4906: Move Status to Final
  EIPS/eip-4906.md
Labels: c-status

#5544 Update EIP-5008: Move Status to Review
  EIPS/eip-5008.md
  assets/eip-5008/.gitignore
  assets/eip-5008/contracts/ERC5008.sol
  assets/eip-5008/contracts/ERC5008Demo.sol
  assets/eip-5008/contracts/IERC5008.sol
  assets/eip-5008/hardhat.config.ts
  assets/eip-5008/package.json
  assets/eip-5008/test/test.ts
  assets/eip-5008/tsconfig.json
Labels: c-status, t-erc, s-review

#5453 Add EIP-5453: Smart Contract Crypto Endorsement
  EIPS/eip-5453.md
Labels: c-new, t-erc, s-draft

#5437 Add EIP-5437: Interface for Security Contact
  EIPS/eip-5437.md
Labels: c-new, t-erc, w-response, s-draft

#5334 Add EIP-5334: EIP-721 User And Expires And Level Extension
  EIPS/eip-5334.md
  assets/eip-5334/ERC5334.sol
  assets/eip-5334/IERC5334.sol
Labels: c-new, t-erc, s-draft

#5283 A Semaphore for Parallelizable Reentrancy Protection
  EIPS/eip-5283.md
Labels: c-new, t-core, s-draft

#5522 Update EIP-4885: Corrected balanceOf method spec; the subscriber doesn’t need to be an…
  EIPS/eip-4885.md
Labels: c-update, t-erc, w-ci, s-draft

#5523 CI: Add "shiping" to CodeSpell whitelist
  .codespell-whitelist
Labels: bug, e-review

#5492 CI: Run EIP-Bot on ready for review
  .github/workflows/auto-review-trigger.yml
Labels: bug, e-review

#5549 Update EIP-5192: Move to Last Call
  EIPS/eip-5192.md
Labels: c-status, t-erc

#5496 Add EIP-5496: Multi-privilege Management Extension for EIP-721
  EIPS/eip-5496.md
  assets/eip-5496/contracts/ERC5496.sol
  assets/eip-5496/contracts/ERC5496CloneableDemo.sol
  assets/eip-5496/contracts/ERC5496Demo.sol
  assets/eip-5496/contracts/IERC5496.sol
  assets/eip-5496/contracts/extensions/ERC5496Cloneable.sol
  assets/eip-5496/contracts/extensions/IERC5496Cloneable.sol
  assets/eip-5496/test/test.js
  assets/eip-5496/test/testCloneable.js
Labels: c-new, t-erc, s-draft

#5558 Move EIP-5516 to Review
  EIPS/eip-5516.md
  assets/eip-5516/ERC5516.sol
  assets/eip-5516/IERC5516.sol
Labels: c-status, t-erc, s-review

#5187 Add EIP-5187: Extend EIP-1155 with rentable usage rights
  EIPS/eip-5187.md
Labels: c-new, t-erc, s-draft

#5427 Update EIP-3561: Move from Stagnant to Review
  EIPS/eip-3561.md
Labels: c-status, t-erc, s-review

#5561 Update eip-3561.md
  EIPS/eip-3561.md
Labels: c-update, t-erc, s-review

#5562 Update eip-3561.md
  EIPS/eip-3561.md
Labels: c-update, t-erc, s-review

#5564 Clarify address casing for EIP-5375
  EIPS/eip-5375.md
Labels: c-update, t-erc, s-review

#5559 Add EIP-5559: Cross Chain Write Deferral Protocol
  EIPS/eip-5559.md
Labels: c-new, t-erc, s-draft

#5567 Update EIP-5289: Use Base 64
  EIPS/eip-5289.md
Labels: c-update, t-erc, s-draft
