Repository ethereum/EIPs, pull requests merged in 2022-11, with the labels that each got.

#5707 Update EIP-4844: Fee Market Update
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5857 Update EIP-5606: Moving to Review stage
  EIPS/eip-5606.md
Labels: c-status, t-erc, s-review

#5782 Update EIP-2612: Move to Final
  EIPS/eip-2612.md
Labels: c-status, t-erc, a-review, s-final

#5568 Add EIP-5568: Required Action Signals Using Revert Reasons
  EIPS/eip-5568.md
Labels: c-new, t-interface, s-draft

#5869 EIP-5757: apply changes from EIPIP meeting
  EIPS/eip-5757.md
  assets/eip-5757/template.md
Labels: c-status, t-meta, s-review

#5866 Update EIP-5750: Change the specification to suit more use cases, fix grammar and some formatting
  EIPS/eip-5750.md
Labels: c-update, t-erc, s-review

#5870 EIP-5757: Move to last call
  EIPS/eip-5757.md
Labels: c-status, t-meta, e-review

#5573 Add EIP-5573: SIWE ReCap Extension
  EIPS/eip-5573.md
Labels: c-new, t-erc, s-draft

#5876 EIP-3540: Reformat, fix typos
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#5861 Update EIP-5750: Move to Last Call
  EIPS/eip-5750.md
Labels: c-status, t-erc

#5879 Update EIP-5750
  EIPS/eip-5750.md
Labels: c-update, t-erc

#5885 Update EIP-5615: Add short note about the function naming
  EIPS/eip-5615.md
Labels: c-update, t-erc, s-draft

#5893 EIP-3670: Improve text style
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#5207 Update EIP-2335: Remove superfluous use of "verifies"
  EIPS/eip-2335.md
Labels: c-update, t-erc, s-stagnant

#5884 EIP-4844.md: Fixed punctuation inconsistency
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5793 Add EIP-5793: eth/68: Add transaction type to tx announcement
  EIPS/eip-5793.md
Labels: c-new, t-networking, s-draft

#5898 Fix data-only contract example
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#5897 Updated EIP-5375: Move to Final
  EIPS/eip-5375.md
Labels: c-status, t-erc, s-final

#5900 Update EIP-5528: Move to Final
  EIPS/eip-5528.md
Labels: c-status, t-erc, s-final

#5905 Update EIP-5507: Add EIP-20 support
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#5889 Update EIP-4519: Make a few wording changes
  EIPS/eip-4519.md
Labels: c-update, t-erc, s-review

#5899 Update EIP-5679: Move to Final
  EIPS/eip-5679.md
Labels: c-status, t-erc, s-final

#5663 Update EIP-3540: Use exceptions with error messages in reference code
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#5656 Add EIP-5656: Memory Copying Instruction
  EIPS/eip-5656.md
Labels: c-new, t-core, s-draft

#5906 EIP-4844: declare withdrawals in 4895 as a dependency
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5909 Update EIP-5732: include @fulldecent's change
  EIPS/eip-5732.md
Labels: c-update, t-erc

#5910 Update EIP-5732 Clean up
  EIPS/eip-5732.md
Labels: c-update, t-erc

#5901 Update EIP-5732 Clean up
  EIPS/eip-5732.md
Labels: c-update, t-erc

#5913 Update EIP-5732: Fix typos
  EIPS/eip-5732.md
Labels: c-update, t-erc

#5915 Update EIP-5679: Fix ERC165 identifiers
  EIPS/eip-5679.md
Labels: c-update, t-erc, s-final

#5911 fix nit on the language of eip-1153
  EIPS/eip-1153.md
Labels: c-update, t-core, s-review

#5918 Update EIP-5000: Fix external link
  EIPS/eip-5000.md
Labels: c-update, t-core, s-draft

#5923 5000: Fix complaints of the markdown linter
  EIPS/eip-5000.md
Labels: c-update, t-core, s-draft

#5924 Update EIP-5604
  EIPS/eip-5604.md
Labels: c-update, t-erc, s-draft

#5919 Update EIP-5732: Move to Final
  EIPS/eip-5732.md
Labels: c-status, t-erc, s-final

#5736 Update EIP-5489: Move to review
  EIPS/eip-5489.md
Labels: c-status, t-erc, s-review

#5593 Add EIP-5593: Restrict Web3 Provider Object API Injection
  EIPS/eip-5593.md
Labels: c-new, t-interface, s-draft

#5863 [EIP-4844] Reduce Throughput
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5931 EIP-5072 edits
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-draft

#5908 Update EIP-4519: Move to last call
  EIPS/eip-4519.md
Labels: c-status, t-erc

#5300 Add EIP-5298: ENS as Token Holder
  EIPS/eip-5298.md
Labels: c-new, t-erc, s-draft

#5881 Update EIP-5484: Move to Final
  EIPS/eip-5484.md
Labels: c-status, t-erc, s-final

#5978 Update EIP-5202: Move to review
  EIPS/eip-5202.md
Labels: c-status, t-erc, s-review

#5827 Add EIP-5827: Auto-renewable allowance extension
  EIPS/eip-5827.md
Labels: c-new, t-erc, s-draft

#5933 Update EIP-2535: fix typos (unnecessary/incorrect words)
  EIPS/eip-2535.md
Labels: c-update, t-erc, s-final

#5614 Update EIP-1: Clarify when to use `requires`
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#5984 Remove redundant ValidationException definition from EOF EIPs
  EIPS/eip-3670.md
  EIPS/eip-4200.md
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft, s-review

#5921 Update EIP-4750: change CALLF/RETF opcodes to not conflict with PUSH0
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#5981 Update EIP-5496: Change status to Last Call
  EIPS/eip-5496.md
  assets/eip-5496/contracts/ERC5496.sol
  assets/eip-5496/contracts/IERC5496.sol
  assets/eip-5496/test/test.js
  assets/eip-5496/test/testCloneable.js
Labels: c-status, t-erc

#6001 EIP-1153: clean up use cases, add security considerations
  EIPS/eip-1153.md
Labels: c-update, t-core, s-review

#5991 Update EIP-5023: Move to Review, minor corrections to interface
  EIPS/eip-5023.md
Labels: c-status, t-erc, s-review

#5874 Update EIP-1: Add first two external origins
  EIPS/eip-1.md
Labels: c-update, t-process

#5995 Update EIP-5489: Move to Last Call
  EIPS/eip-5489.md
Labels: c-status, t-erc

#6006 EIP-4844: Add adietrichs as co-author
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5980 Update EIP-1898: Move to draft
  EIPS/eip-1898.md
Labels: c-status, t-interface, s-draft

#6007 Add "EOF - " prefix to 3540, 4200
  EIPS/eip-3540.md
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#5907 EIP-3540: Clarify contract creation rules
  EIPS/eip-3540.md
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#5894 EIP-3670: Reject CALLCODE and SELFDESTRUCT
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#6019 EIP-4987 hardening/cleanup
  EIPS/eip-4987.md
  assets/eip-4987/Consumer.sol
Labels: c-update, t-erc, s-review

#6020 Update EIP-4844: Clarify Fork Block Behavior
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6002 EIP4844: Update crypto API (simplify precompile / sync with consensus-specs)
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6024 EIP-4987: asset links
  EIPS/eip-4987.md
Labels: c-update, t-erc, s-review

#5930 Update EIP-4844: Disable Blob Transaction Broadcast
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6026 Update EIP-4844: Clarify Precompile Return Data Endianness
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6029 Update EIP-4895: fix small typo
  EIPS/eip-4895.md
Labels: c-update, t-core, s-review

#5988 Add EIP-5988: Add Poseidon hash function precompile
  EIPS/eip-5988.md
  assets/eip-5988/benchmarks/.gitkeep
  assets/eip-5988/papers/poseidon_paper.pdf
  assets/eip-5988/papers/practical_algebraic_attacks.pdf
  assets/eip-5988/papers/proving_resistance_linear_layer.pdf
  assets/eip-5988/papers/report_security_stark_friendly_hash.pdf
  assets/eip-5988/papers/security_poseidon_non_binary_differential_attacks.pdf
  assets/eip-5988/reference-implementation/.gitkeep
  assets/eip-5988/test/poseidon/test_vectors.txt
Labels: c-new, t-core, s-draft

#5920 Add EIP-5920: PAY opcode
  EIPS/eip-5920.md
Labels: c-new, t-core, s-draft

#6035 Update EIP-4844: small clarification
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6018 Update EIP-5749: Move to last call
  EIPS/eip-5749.md
Labels: c-status, t-interface

#6042 Update EIP-663: Bring back to draft
  EIPS/eip-663.md
Labels: c-status, t-core, s-draft

#6043 EIP-5007: Change uint64 to int64
  EIPS/eip-5007.md
  assets/eip-5007/contracts/ERC5007.sol
  assets/eip-5007/contracts/ERC5007Composable.sol
  assets/eip-5007/contracts/ERC5007ComposableTest.sol
  assets/eip-5007/contracts/ERC5007Demo.sol
  assets/eip-5007/contracts/IERC5007.sol
  assets/eip-5007/contracts/IERC5007Composable.sol
  assets/eip-5007/test/test.js
Labels: c-update, t-erc

#6040 Update EIP-3860: Clarify nonce rules
  EIPS/eip-3860.md
Labels: c-update, t-core, s-review

#5719 Add EIP-5719: Signature replacing for smart contract wallets
  EIPS/eip-5719.md
Labels: c-new, t-erc, s-draft

#5725 Add EIP-5725: Transferable Vesting NFT
  EIPS/eip-5725.md
  assets/eip-5725/README.md
  assets/eip-5725/contracts/ERC5725.sol
  assets/eip-5725/contracts/IERC5725.sol
  assets/eip-5725/contracts/mocks/ERC20Mock.sol
  assets/eip-5725/contracts/reference/LinearVestingNFT.sol
  assets/eip-5725/contracts/reference/VestingNFT.sol
  assets/eip-5725/test/LinearVestingNFT.test.ts
  assets/eip-5725/test/VestingNFT.test.ts
  assets/eip-5725/test/helpers/time.ts
Labels: c-new, t-erc, s-draft

#5753 Add EIP-5753: Lockable Extension for EIP-721
  EIPS/eip-5753.md
Labels: c-new, t-erc, s-draft

#5773 Add EIP-5773: Multi-Resource Token standard
  EIPS/eip-5773.md
  assets/eip-5773/contracts/IMultiAsset.sol
  assets/eip-5773/contracts/MultiAssetToken.sol
  assets/eip-5773/contracts/library/MultiAssetLib.sol
  assets/eip-5773/contracts/mocks/ERC721ReceiverMock.sol
  assets/eip-5773/contracts/mocks/MultiAssetTokenMock.sol
  assets/eip-5773/contracts/mocks/NonReceiverMock.sol
  assets/eip-5773/contracts/utils/MultiAssetRenderUtils.sol
  assets/eip-5773/hardhat.config.ts
  assets/eip-5773/package.json
  assets/eip-5773/test/multiasset.ts
  assets/eip-5773/test/renderUtils.ts
Labels: c-new, t-erc, s-draft

#5778 Update EIP-5615: Move to Review
  EIPS/eip-5615.md
Labels: c-status, t-erc, s-review

#5804 Update EIP-191: Improve Comprehensibility
  EIPS/eip-191.md
Labels: c-update, t-erc, a-review, s-final

#6013 Update EIP-4527: Move to draft
  EIPS/eip-4527.md
Labels: c-status, t-erc, s-draft

#6041 Update 4758: Move to Review
  EIPS/eip-4758.md
Labels: c-status, t-core, s-review

#6054 Small updates to EIP-663
  EIPS/eip-663.md
Labels: c-update, t-core, s-draft

#6050 Update EIP-4527: Move to review
  EIPS/eip-4527.md
Labels: c-status, t-erc, s-review

#6057 Update EIP-1153: Move to last call
  EIPS/eip-1153.md
Labels: c-status, t-core

#6049 Add EIP-6049: Deprecate SELFDESTRUCT
  EIPS/eip-6049.md
Labels: c-new, t-core, s-draft

#6034 Update EIP-1: add devp2p repo as accepted external resource
  EIPS/eip-1.md
Labels: c-update, t-process

#6061 EIP-4750: Add rationale for 1024 code sections limit
  EIPS/eip-4750.md
Labels: c-update, t-core, s-draft

#6064 Update eip-6049.md
  EIPS/eip-6049.md
Labels: c-update, t-meta, s-draft

#6067 Update EIP-3540: Clarify that code size limit applies to container
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6055 Clarifications to EIP-663
  EIPS/eip-663.md
Labels: c-update, t-core, s-draft
