Repository ethereum/EIPs, pull requests merged in 2023-01, with the labels that each got.

#6246 EIP-4337 - AA-100: Change bundling rules to prevent any cross-op access
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6248 3540: type size range should start at 0
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6250 EIP-4337 AA-99 account returns validAfter,validUntil
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6252 update unstaked entity rules
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6120 Add EIP-6120: Universal Token Router
  EIPS/eip-6120.md
Labels: c-new, t-erc, s-review

#6103 Update EIP-725: Improvements
  EIPS/eip-725.md
  assets/eip-725/ERC725.sol
Labels: c-status, t-erc, s-draft

#6244 Update from last call to final
  EIPS/eip-5023.md
Labels: c-status, t-erc, s-final

#6253 3540,4750,5450: Rename data stack to operand stack
  EIPS/eip-3540.md
  EIPS/eip-4750.md
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#6221 Update EIP-6059: Move to Review
  EIPS/eip-6059.md
Labels: c-status, t-erc, s-review

#6219 Update EIP-6150: Move to Review
  EIPS/eip-6150.md
Labels: c-status, t-erc, s-review

#5982 Add EIP-5982: Role-based Access Control
  EIPS/eip-5982.md
Labels: c-new, t-erc, s-draft

#6257 minor typos on EIP 5573
  EIPS/eip-5573.md
Labels: c-update, t-erc, s-draft

#6234 Update EIP-4337: fix miscellaneous typos
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6251 3540: restrict number of code sections to 1024
  EIPS/eip-3540.md
Labels: c-update, t-core, a-review, s-review

#6262 another update to EIP-5630: only do ECDH
  EIPS/eip-5630.md
Labels: c-update, t-erc, s-draft

#6263 very small follow-up edits to EIP-5630
  EIPS/eip-5630.md
Labels: c-update, t-erc, s-draft

#6188 Add EIP-6188: Nonce Cap
  EIPS/eip-6188.md
Labels: c-new, t-core, s-draft, e-blocking

#6259 Update EIP-6120: more contents and token-transfer sub-action
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#6267 Added coauthor to EIP-5630 per discussion
  EIPS/eip-5630.md
Labels: c-update, t-erc, a-review, s-draft

#6270 Improvements for signature generation
  EIPS/eip-4973.md
  assets/eip-4973/ERC4973-flat.sol
  assets/eip-4973/package.json
  assets/eip-4973/sdk/src/index.mjs
  assets/eip-4973/sdk/test/index_test.mjs
Labels: c-update, t-erc, s-review

#6271 Clarify document ownership
  EIPS/eip-4973.md
Labels: c-update, t-erc, s-review

#6265 Update EIP-1459: unstagnate and add security consideration
  EIPS/eip-1459.md
Labels: c-status, t-networking, s-draft

#6255 CI: Only run label bot on PRs to master
  .github/workflows/auto-label-bot.yml
Labels: bug, r-ci

#5227 Update EIP-3267: Fix SPDX license identifier
  EIPS/eip-3267.md
  assets/eip-3267/contracts/BaseBidOnAddresses.sol
  assets/eip-3267/contracts/BaseLock.sol
  assets/eip-3267/contracts/BaseRestorableSalary.sol
  assets/eip-3267/contracts/BaseSalary.sol
  assets/eip-3267/contracts/BidOnAddresses.sol
  assets/eip-3267/contracts/DAOInterface.sol
  assets/eip-3267/contracts/DefaultDAOInterface.sol
  assets/eip-3267/contracts/ERC1155/ERC1155.sol
  assets/eip-3267/contracts/ERC1155/ERC1155TokenReceiver.sol
  assets/eip-3267/contracts/ERC1155/ERC1155WithTotals.sol
  assets/eip-3267/contracts/ERC1155/IERC1155.sol
  assets/eip-3267/contracts/ERC1155/IERC1155TokenReceiver.sol
  assets/eip-3267/contracts/Salary.sol
  assets/eip-3267/contracts/SalaryWithDAO.sol
Labels: a-review

#6274 Update EIP-2771: Fix markdownlint issues
  EIPS/eip-2771.md
Labels: c-update, t-erc, s-review

#6213 Update README: Update GitHub docs link
  README.md
Labels: r-website

#6275 Update CI: Fix EIP bot sometimes not triggering
  .github/workflows/auto-review-bot.yml
Labels: bug, r-ci

#6264 Update EIP-2771: Move to Last Call
  EIPS/eip-2771.md
Labels: c-status, t-erc

#6281 Update EIP-2771: Fix typo
  EIPS/eip-2771.md
Labels: c-update, t-erc

#6282 Update EIP-5507: Fix file names
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#6283 Update EIP-5507: Final changes before last call
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-draft

#6284 CI: Make @eth-bot run on every PR action
  .github/workflows/auto-review-trigger.yml
Labels: bug, r-ci

#6285 Update EIP-4834: Add changes to increase flexibility
  EIPS/eip-4834.md
  assets/eip-4834/IDomain.sol
  assets/eip-4834/IDomainAccessControl.sol
  assets/eip-4834/IDomainEnumerable.sol
  assets/eip-4834/OwnableDomain.sol
Labels: c-update, t-erc, w-ci, s-review

#6288 Update EIP-4834: Remove old links
  EIPS/eip-4834.md
Labels: c-update, t-erc, s-review

#6290 Update eip-2771.md: isTrustedForwarder gas limit
  EIPS/eip-2771.md
Labels: c-update, t-erc

#6291 Update EIP-5568: Micah's review
  EIPS/eip-5568.md
Labels: c-update, t-erc, s-review

#6289 Update EIP-5920: Prepare for Review
  EIPS/eip-5920.md
Labels: c-update, t-core, w-ci, s-draft

#6292 Update EIP-5920: Update abstract
  EIPS/eip-5920.md
Labels: c-update, t-core, s-draft

#6296 Update EIP-6188: Fix minor typo
  EIPS/eip-6188.md
Labels: c-update, t-core, s-draft

#6297 EIP-5267: Clarify use of extensions and add event
  EIPS/eip-5267.md
Labels: c-update, t-erc, s-review

#6298 more minor changes to 5630
  EIPS/eip-5630.md
Labels: c-update, t-erc, s-draft

#6302 Make signature of signature optional
  EIPS/eip-5570.md
Labels: c-update, t-erc, s-draft

#6249 EIP-3860: Change the failure to OOG
  EIPS/eip-3860.md
Labels: c-update, t-core, s-review

#6303 Update EIP-5570: Move to review
  EIPS/eip-5570.md
Labels: c-status, t-erc, s-review

#6238 clarify signed blob transaction hashing
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6241 change blob tx_hash to use serialize instead of hash_tree_root
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6287 Update EIP-4834: Move to Last Call
  EIPS/eip-4834.md
Labels: c-status, t-erc

#6186 Update EIP-5507: Move to review
  EIPS/eip-5507.md
Labels: c-status, t-erc, s-review

#6295 Update EIP-5920: Move to Review
  EIPS/eip-5920.md
Labels: c-status, t-core, s-review

#6189 Add EIP-6189: Alias Contracts
  EIPS/eip-6189.md
Labels: c-new, t-core, e-review, s-draft, e-blocking

#6147 Add EIP-6147: Guard of NFT/SBT, an Extension of EIP-721
  EIPS/eip-6147.md
Labels: c-new, t-erc, s-draft

#6300 Update EIP-5267: Move to Last Call
  EIPS/eip-5267.md
Labels: c-status, t-erc

#6307 Update EIP-5269 EIP/ERC Detection and Discovery
  EIPS/eip-5269.md
Labels: c-update, t-erc, s-draft

#6308 Update EIP-6150: Optimize and add more implementation
  EIPS/eip-6150.md
  assets/eip-6150/contracts/ERC6150.sol
  assets/eip-6150/contracts/ERC6150AccessControl.sol
  assets/eip-6150/contracts/ERC6150Burnable.sol
  assets/eip-6150/contracts/ERC6150Enumerable.sol
  assets/eip-6150/contracts/ERC6150ParentTransferable.sol
  assets/eip-6150/contracts/interfaces/IERC6150.sol
  assets/eip-6150/contracts/interfaces/IERC6150AccessControl.sol
  assets/eip-6150/contracts/interfaces/IERC6150Burnable.sol
  assets/eip-6150/contracts/interfaces/IERC6150Enumerable.sol
  assets/eip-6150/contracts/interfaces/IERC6150ParentTransferable.sol
Labels: c-update, t-erc, w-ci, s-review

#6313 Update EIP-6190: Rename to verkle-compatible SELFDESTRUCT
  EIPS/eip-6190.md
Labels: c-update, t-core, s-draft

#6312 Update EIP-5629 about DRAFT identifier
  EIPS/eip-5269.md
Labels: c-update, t-erc, w-ci, s-draft

#6316 Update EIP-5269
  EIPS/eip-5269.md
Labels: c-update, t-erc, s-draft

#6317 Add asset file for EIP-5269
  EIPS/eip-5269.md
  assets/eip-5269/contracts/ERC5269.sol
  assets/eip-5269/contracts/IERC5269.sol
  assets/eip-5269/contracts/testing/ERC721ForTesting.sol
  assets/eip-5269/test/TestERC5269.ts
Labels: c-update, t-erc, s-draft

#6318 Add asset file for EIP-5269
  EIPS/eip-5269.md
Labels: c-update, t-erc, s-draft

#6319 Update EIP-5269
  EIPS/eip-5269.md
Labels: c-update, t-erc, s-draft

#6321 Update design of eip-5564
  EIPS/eip-5564.md
  assets/eip-5564/minimal_poc.ipynb
Labels: c-update, t-erc, s-draft

#6320 Update EIP-5269
  EIPS/eip-5269.md
Labels: c-update, t-erc, s-draft

#5851 Add EIP-5851: On-Chain Verifiable Credentials
  EIPS/eip-5851.md
  assets/eip-5851/contracts/ERC5851Issuer.sol
  assets/eip-5851/contracts/ERC5851Verifier.sol
  assets/eip-5851/contracts/interfaces/IERC5851.sol
  assets/eip-5851/contracts/test.sol
  assets/eip-5851/script/offchainOperations.js
Labels: c-new, t-erc, s-draft

#6331 Update eip-6147.md
  EIPS/eip-6147.md
Labels: c-update, t-erc, s-draft

#6332 Update EIP-5920: Gas cost update and burning via zero address
  EIPS/eip-5920.md
Labels: c-update, t-core, s-review

#6333 Update EIP-6189: Add support for EIP-5920
  EIPS/eip-6189.md
Labels: c-update, t-core, s-draft

#6326 Update EIP-5269: Move to Review
  EIPS/eip-5269.md
Labels: c-status, t-erc, s-review

#6325 EIP-4895: CL-EL withdrawals harmonization: using units of Gwei
  EIPS/eip-4895.md
Labels: c-update, t-core, s-review

#6224 Add EIP-6224: Contracts Dependencies Registry
  EIPS/eip-6224.md
Labels: c-new, t-erc, s-draft

#6345 EIP-4844: Explicitly state sha256 is used
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#6348 Update EIP-4844: clarify datahash return value
  EIPS/eip-4844.md
Labels: c-update, t-core, s-draft

#5700 Add EIP-5700: Bindable Token Standard
  EIPS/eip-5700.md
  assets/eip-5700/erc1155/ERC1155.sol
  assets/eip-5700/erc1155/ERC1155Bindable.sol
  assets/eip-5700/erc1155/ERC1155Binder.sol
  assets/eip-5700/erc721/ERC721.sol
  assets/eip-5700/erc721/ERC721Bindable.sol
  assets/eip-5700/erc721/ERC721Binder.sol
  assets/eip-5700/interfaces/IERC1155Bindable.sol
  assets/eip-5700/interfaces/IERC1155BindableErrors.sol
  assets/eip-5700/interfaces/IERC1155Binder.sol
  assets/eip-5700/interfaces/IERC1155BinderErrors.sol
  assets/eip-5700/interfaces/IERC1155Errors.sol
  assets/eip-5700/interfaces/IERC721Bindable.sol
  assets/eip-5700/interfaces/IERC721BindableErrors.sol
  assets/eip-5700/interfaces/IERC721Binder.sol
  assets/eip-5700/interfaces/IERC721BinderErrors.sol
  assets/eip-5700/interfaces/IERC721Errors.sol
Labels: c-new, t-erc, w-stale, s-draft

#6349 Update EIP-5920: Reduce account creation gas
  EIPS/eip-5920.md
Labels: c-update, t-core, s-review

#6350 Update EIP-5920: Reference eip-2929 and massively reduce pay opcode price
  EIPS/eip-5920.md
Labels: c-update, t-core, s-review

#6352 Update EIP-6190: Remove axic as an author
  EIPS/eip-6190.md
Labels: c-update, t-core, s-draft

#6338 Update EIP-2135: Move to Last Call
  EIPS/eip-2135.md
Labels: c-status, t-erc

#6340 Update EIP-5982: Move to Review
  EIPS/eip-5982.md
Labels: c-status, t-erc, s-review

#6342 Update EIP-5604: Move to Review
  EIPS/eip-5604.md
Labels: c-status, t-erc, s-review

#6356 Update to EIP-5805
  EIPS/eip-5805.md
Labels: c-update, t-erc, s-draft

#6361 Update ERC5805 interface
  EIPS/eip-5805.md
Labels: c-update, t-erc, s-draft

#6343 Update EIP-5298: Move to Review
  EIPS/eip-5298.md
Labels: c-status, t-erc, s-review

#6220 Add EIP-6220: Propose Composable NFTs utilizing Equippable Parts
  EIPS/eip-6220.md
  assets/eip-6220/contracts/Catalog.sol
  assets/eip-6220/contracts/EquippableToken.sol
  assets/eip-6220/contracts/ICatalog.sol
  assets/eip-6220/contracts/IERC5773.sol
  assets/eip-6220/contracts/IERC6059.sol
  assets/eip-6220/contracts/IEquippable.sol
  assets/eip-6220/contracts/library/EquippableLib.sol
  assets/eip-6220/contracts/mocks/CatalogMock.sol
  assets/eip-6220/contracts/mocks/ERC721Mock.sol
  assets/eip-6220/contracts/mocks/ERC721ReceiverMock.sol
  assets/eip-6220/contracts/mocks/EquippableTokenMock.sol
  assets/eip-6220/contracts/mocks/NonReceiverMock.sol
  assets/eip-6220/contracts/security/ReentrancyGuard.sol
  assets/eip-6220/contracts/utils/EquipRenderUtils.sol
  assets/eip-6220/contracts/utils/MultiAssetRenderUtils.sol
  assets/eip-6220/hardhat.config.ts
  assets/eip-6220/package.json
  assets/eip-6220/test/catalog.ts
  assets/eip-6220/test/equippableFixedParts.ts
  assets/eip-6220/test/equippableSlotParts.ts
  assets/eip-6220/test/multiasset.ts
  assets/eip-6220/test/nestable.ts
  assets/eip-6220/test/renderUtils.ts
Labels: c-new, t-erc, s-draft

#6146 Update EIP-5164: Add chainId and naming
  EIPS/eip-5164.md
Labels: c-update, t-erc, a-review, s-review

#6363 Update EIP-4834: Move to Final
  EIPS/eip-4834.md
Labels: c-status, t-erc, s-final

#6362 Update EIP-2771: Move to Final
  EIPS/eip-2771.md
Labels: c-status, t-erc, s-final

#6368 EIP-4200: fix RJUMPI -> JUMPI
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#6347 EIP-3540: Add @lightclient as author
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6346 EIP-5450: Extend motivation of AOT/JIT compilation
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#6365 Update EIP-5646: Move to Final
  EIPS/eip-5646.md
Labels: c-status, t-erc, s-final

#6311 Update EIP-6150: Move to Last Call
  EIPS/eip-6150.md
Labels: c-status, t-erc

#6372 Add EIP-6372: Contract clock
  EIPS/eip-6372.md
Labels: c-new, t-erc, s-draft

#6309 Update EIP-1898: Move to Review
  EIPS/eip-1898.md
Labels: c-status, t-interface, s-review

#6329 Update EIP-4955: Move to Last Call
  EIPS/eip-4955.md
Labels: c-status, t-erc

#6304 Update EIP-4736: Move to Draft
  EIPS/eip-4736.md
Labels: c-status, t-interface, s-draft

#6369 Update EIP-6220: Purge of bloated assets
  EIPS/eip-6220.md
  assets/eip-6220/contracts/EquippableToken.sol
  assets/eip-6220/contracts/security/ReentrancyGuard.sol
Labels: c-update, t-erc, s-draft

#5576 Update EIP template: Add acceptable placeholders
  eip-template.md
  index.html
Labels: t-process, s-draft

#5927 Update README: Add friendlier introduction
  README.md
Labels: w-ci

#6382 Fix # of introduced instructions
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#6387 Update EIP-5085: Fix typos
  EIPS/eip-5805.md
Labels: c-update, t-erc, s-draft

#6378 EIP-6220: Update status to Review
  EIPS/eip-6220.md
Labels: c-status, t-erc, s-review

#6066 Add EIP-6066: Signature Validation Method for NFTs
  EIPS/eip-6066.md
Labels: c-new, t-erc, s-draft

#6122 Add EIP-6122: Forkid checks based on timestamps
  EIPS/eip-6122.md
Labels: c-new, t-networking, s-draft

#6157 Website: add an all.xml rss feed
  rss/all.xml
Labels: w-response, r-website

#6277 CI: Use environment files
  .github/workflows/auto-review-bot.yml
  .github/workflows/post-ci.yml
Labels: e-review, r-ci

#6402 added email address
  EIPS/eip-6384.md
Labels: c-update, t-erc, s-draft
