Repository ethereum/EIPs, pull requests merged in 2023-06, with the labels that each got.

#6970 Update EIP-1185: Move to Review
  EIPS/eip-1185.md
Labels: c-status, t-erc, e-review, s-review

#7062 Update EIP-4844: add `data_gas_used` to header
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#7100 Update EIP-4844: clarify to must be non-nil
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#6943 Update EIP-4824: start
  EIPS/eip-4824.md
Labels: c-update, t-erc, s-draft

#7124 Update EIP-6981: Update Account Instance Signatures section
  EIPS/eip-6981.md
Labels: c-update, t-erc, a-review, s-draft

#7073 Update EIP-6953: Move to Review
  EIPS/eip-6953.md
Labels: c-status, t-informational, e-review, s-review

#7015 Add EIP: NFT Creator Attribution
  EIPS/eip-7015.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6997 Add EIP: ERC-721 with transaction validation step.
  EIPS/eip-6997.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6909 Add EIP: Minimal Multi-Token Interface
  EIPS/eip-6909.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7095 Update EIP-4844: reduce size of `excess_data_gas` to 64 bit
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#6806 Add EIP: ERC-721 Holding Time Tracking
  EIPS/eip-6806.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7133 Update EIP-6093: Rename `ERC721InexistentToken` to `ERC721NonexistentToken`
  EIPS/eip-6093.md
Labels: c-update, t-erc, s-draft

#7134 Update EIP-6963: Editorial changes
  EIPS/eip-6963.md
Labels: c-update, t-interface, w-ci, s-draft

#7143 Update EIP-6963: [EIP-6963] remove walletId from spec
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7131 Update EIP-3540: EOF1 contracts can only DELEGATECALL EOF1 contracts
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#7069 Add EIP: Revamped CALL instructions
  EIPS/eip-7069.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7128 Update EIP-5169: Move to Final
  EIPS/eip-5169.md
Labels: c-status, t-erc, e-review, s-final

#7132 Update EIP-6963: Update Window Events section
  EIPS/eip-6963.md
Labels: c-update, t-interface, w-ci, a-review, s-draft

#7146 Update EIP-5564: ERC-5564 - remove staking and add indexed caller
  EIPS/eip-5564.md
Labels: c-update, t-erc, s-draft

#7145 Update EIP-6900: Spec changes regarding call mode and new hook types
  EIPS/eip-6900.md
  assets/eip-6900/MSCA_Shared_Components_Diagram.svg
  assets/eip-6900/MSCA_Two_Call_Paths_Diagram.svg
  assets/eip-modular-smart-contract-accounts-and-plugins/MSCA_Two_Call_Paths_Diagram.svg
Labels: c-update, t-erc, a-review, s-draft, e-consensus

#7147 Update EIP-6381: Add bulk actions and presigned emotes
  EIPS/eip-6381.md
  assets/eip-6381/contracts/EmotableRepository.sol
  assets/eip-6381/contracts/IERC6381.sol
  assets/eip-6381/test/emotableRepository.ts
Labels: c-update, t-erc

#7148 Update EIP-6381: Set new last call deadline
  EIPS/eip-6381.md
Labels: c-update, t-erc

#7152 Update EIP-6963: Update eip-6963.md
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7153 Update EIP-6551: Update eip-6551.md
  EIPS/eip-6551.md
Labels: c-update, t-erc, a-review, s-draft

#7154 Update EIP-4844: Increase Blob Throughput
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#7155 Update EIP-5656: update eip-5656 MCOPY opcode per cancun allocation
  EIPS/eip-5656.md
Labels: c-update, t-core, s-review

#7156 Update EIP-4844: Adjust Throughput Section
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#6960 Add EIP: Dual Layer Token
  EIPS/eip-6960.md
  assets/eip-6960/eip-6960-dual-layer-token-dlt.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6982 Add EIP: Efficient Default Lockable Tokens
  EIPS/eip-6982.md
  assets/eip-6982/.gitignore
  assets/eip-6982/README.md
  assets/eip-6982/contracts/ERC721Lockable.sol
  assets/eip-6982/contracts/IERC6982.sol
  assets/eip-6982/contracts/IERC721Lockable.sol
  assets/eip-6982/contracts/mocks/ERC721LockableMock.sol
  assets/eip-6982/contracts/mocks/MyLocker.sol
  assets/eip-6982/hardhat.config.js
  assets/eip-6982/package.json
  assets/eip-6982/test/Lockable.test.js
  assets/eip-6982/test/helpers.js
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7162 Update EIP-6492: Fix typo in eip-6492.md
  EIPS/eip-6492.md
Labels: c-update, t-erc, a-review, s-review

#7163 Update EIP-2015: Use sam's wording
  EIPS/eip-2015.md
Labels: c-update, t-interface, s-review

#7165 Update EIP-6963: Add walletId back into the design
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7166 Update EIP-6963: Revert "Update EIP-6963: Add walletId back into the design"
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7171 Update EIP-6900: Spec corrections
  EIPS/eip-6900.md
Labels: c-update, t-erc, a-review, s-draft

#7157 Update EIP-6093: Move to Last Call
  EIPS/eip-6093.md
Labels: c-status, t-erc, e-review

#7176 Update EIP-6239: Move to Review
  EIPS/eip-6239.md
Labels: c-status, t-erc, e-review, s-review

#7129 Update EIP-6997: Move to Review
  EIPS/eip-6997.md
Labels: c-status, t-erc, e-review, s-review

#7175 Update EIP-6963: Remove Object.freeze from Dapp implementation exampl…
  EIPS/eip-6963.md
Labels: c-update, t-interface, w-ci, s-draft

#7130 Update EIP-6900: More precise usage of words `account` and `wallet`
  EIPS/eip-6900.md
Labels: c-update, t-erc, a-review, s-draft

#7111 Update EIP-1: Add W3C as a permissible origin
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7117 Update EIP-1: Add WHATWG as a permissible origin
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7187 Update EIP-6093: Improve specification clarity
  EIPS/eip-6093.md
Labels: c-update, t-erc

#7113 Update EIP-1: Add IETF as a permissible origin
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6907 Update EIP-1: Update EIP-1 to allow link to BIPs
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6969 Add EIP: Contract Secured Revenue on an EVM based L2
  EIPS/eip-6968.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7007 Add EIP: Zero-Knowledge AI-Generated Content Token
  EIPS/eip-7007.md
  assets/eip-7007/.gitignore
  assets/eip-7007/README.md
  assets/eip-7007/contracts/ERC7007.sol
  assets/eip-7007/contracts/ERC7007Enumerable.sol
  assets/eip-7007/contracts/IERC7007.sol
  assets/eip-7007/contracts/IERC7007Enumerable.sol
  assets/eip-7007/contracts/IVerifier.sol
  assets/eip-7007/contracts/MockVerifier.sol
  assets/eip-7007/hardhat.config.js
  assets/eip-7007/package-lock.json
  assets/eip-7007/package.json
  assets/eip-7007/test/test.js
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7192 Update EIP-3076: Conform EIP-3076 to linting policy
  EIPS/eip-3076.md
Labels: c-update, t-interface

#7184 Update EIP-3076: Update EIP-3076 - Condition 5 to be consistent with Condition 2, tests and with some current client implementations
  EIPS/eip-3076.md
Labels: c-update, t-interface, a-review, e-consensus

#7207 Update EIP-7045: minor copy and link updates
  EIPS/eip-7045.md
Labels: c-update, t-core, s-draft

#7194 Update EIP-3076: Update eip-3076.md
  EIPS/eip-3076.md
Labels: c-update, t-interface, a-review

#7172 Update EIP-4844: Update precompile address for 4844
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#7201 Add EIP: Namespaced Storage Layout
  EIPS/eip-7201.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7144 Add EIP: ERC-20 with transaction validation step.
  EIPS/eip-7144.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7213 CI: Bump eipw to 0.4.7
  .github/workflows/ci.yml
Labels: e-consensus

#7215 Update EIP-7201: Fix typo
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7214 Update EIP-2537: update precompile addresses to avoid collision with latest precompile set
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-stagnant

#6696 Update EIP-4337: Correct EIP 4337 reputation specification
  EIPS/eip-4337.md
Labels: c-update, t-erc, a-review, s-draft

#7199 Add EIP: Linter Scope
  EIPS/eip-7199.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#7223 Update EIP-7201: Improve wording
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7224 CI: Update ci.yml
  .github/workflows/ci.yml
Labels: e-consensus

#7044 Add EIP: Perpetually Valid Signed Voluntary Exits
  EIPS/eip-7044.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7228 Update EIP-5564: update contract name
  EIPS/eip-5564.md
Labels: c-update, t-erc, s-draft

#6813 CI: Bump rakefile deps
  .github/workflows/ci.yml
  EIPS/eip-2535.md
  Gemfile
  Gemfile.lock
  README.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7232 Update EIP-6381: Add recalculated address and fix typos
  EIPS/eip-6381.md
Labels: c-update, t-erc

#7188 Update EIP-4907: remove Unix executable permissions from EIPs with wrong permissions
  EIPS/eip-4907.md
  EIPS/eip-5006.md
  EIPS/eip-5007.md
  EIPS/eip-5008.md
  EIPS/eip-5192.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7066 Add EIP: Lockable Extension for ERC-721
  EIPS/eip-7066.md
  assets/eip-7066/ERC7066.sol
  assets/eip-7066/IERC7066.sol
  assets/eip-7066/test/test.js
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7002 Add EIP: Execution layer triggerable exits
  EIPS/eip-7002.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7212 Add EIP: Precompiled for secp256r1 Curve Support
  EIPS/eip-7212.md
  assets/eip-7212/benchstat_compare_test
  assets/eip-7212/ecrecover_benchmark_test
  assets/eip-7212/p256Verify_benchmark_test
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7237 EIP-6110: add CL spec and extended DoS analysis
  EIPS/eip-6110.md
  assets/eip-6110/ws_period_analysis.md
Labels: c-update, t-core, s-draft

#7257 Update EIP-5656: fix eip-5656 test cases and add gas costs
  EIPS/eip-5656.md
Labels: c-update, t-core, s-review

#7218 Update EIP-7053: Move to Review
  EIPS/eip-7053.md
Labels: c-status, t-erc, e-review, s-review

#7203 Update EIP-6239: Move to Last Call
  EIPS/eip-6239.md
Labels: c-status, t-erc, e-review

#7258 Update EIP-6909: Author's github not being correctly rendered
  EIPS/eip-6909.md
Labels: c-update, t-erc, a-review, s-draft
