Repository ethereum/EIPs, pull requests merged in 2023-04, with the labels that each got.

#6810 Add EIP: Ex Post Facto Cascading Revert
  EIPS/eip-6810.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#3455 Add EIP: SUDO Opcode
  EIPS/eip-3455.md
Labels: c-new, t-core, w-ci, e-review, s-draft, e-consensus

#6818 Update EIP-6551: Add missing EIP-1271 signature validation to reference implementation
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6820 Update EIP-6059: Update security considerations
  EIPS/eip-6059.md
Labels: c-update, t-erc

#6822 Website: 💄 hide header/footer on print
  assets/css/style.scss
Labels: e-consensus

#6823 Add EIP: Token Mapping Slot Retrieval Extension
  EIPS/eip-6823.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6756 Update EIP-5006: Move to Final
  EIPS/eip-5006.md
Labels: c-status, t-erc, a-review, s-final

#6829 Update EIP-6381: Update EIP-6381 to be a public good repository
  EIPS/eip-6381.md
  assets/eip-6381/contracts/Emotable.sol
  assets/eip-6381/contracts/EmotableRepository.sol
  assets/eip-6381/contracts/IERC6381.sol
  assets/eip-6381/contracts/IEmotable.sol
  assets/eip-6381/contracts/mocks/ERC721EmotableMock.sol
  assets/eip-6381/contracts/mocks/ERC721Mock.sol
  assets/eip-6381/hardhat.config.ts
  assets/eip-6381/package.json
  assets/eip-6381/test/emotable.ts
  assets/eip-6381/test/emotableRepository.ts
Labels: c-update, t-erc, s-review

#6825 CI: Remove broken CI retrigger
  .github/workflows/ci-rerun-trigger.yml
Labels: e-consensus

#6777 Update EIP-5219: Move to Final
  EIPS/eip-5219.md
Labels: c-status, t-erc, e-review, s-final

#6828 Update EIP-6220: Move to Last Call
  EIPS/eip-6220.md
Labels: c-status, t-erc, e-review

#6672 Add EIP: Multi-redeemable NFTs
  EIPS/eip-6672.md
  assets/eip-6672/contracts/ERC6672.sol
  assets/eip-6672/contracts/interfaces/IERC6672.sol
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6740 Update EIP-6105: Move to Last Call
  EIPS/eip-6105.md
Labels: c-status, t-erc, e-review

#6652 Update EIP-5639: Move to Review
  EIPS/eip-5639.md
Labels: c-status, t-erc, e-review, s-review

#6592 Update EIP-6357: Move to Review
  EIPS/eip-6357.md
Labels: c-status, t-erc, e-review, s-review

#6600 Update EIP-3525: Revise information of some authors as well as modify the naming rules when referencing ERCs
  EIPS/eip-3525.md
Labels: c-update, t-erc, s-final, e-consensus

#6833 Update EIP-5564: update eip-5564 - add staking mechanism
  EIPS/eip-5564.md
Labels: c-update, t-erc, s-draft

#6824 Update EIP-1: Update EIP-1 to include wording about The Finalizing Pull Request
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6838 Update EIP-5773: Update EIP-5773s optional metadata specification
  EIPS/eip-5773.md
Labels: c-update, t-erc

#6839 Update EIP-6059: Update EIP-6059 to optimize interface size
  EIPS/eip-6059.md
  assets/eip-6059/contracts/IERC6059.sol
  assets/eip-6059/contracts/NestableToken.sol
Labels: c-update, t-erc

#6306 Update EIP-1: Permit links to Execution Specs
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6844 Update EIP-6381: Add testnet address
  EIPS/eip-6381.md
Labels: c-update, t-erc, s-review

#6837 Update EIP-3855: Move to Last Call
  EIPS/eip-3855.md
Labels: c-status, t-core, w-ci, a-review

#6835 Update EIP-3860: Move to Last Call
  EIPS/eip-3860.md
Labels: c-status, t-core, w-ci, a-review

#6836 Update EIP-4895: Move to Last Call
  EIPS/eip-4895.md
Labels: c-status, t-core, a-review

#6842 Update EIP-4844: check input length of the precompile
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#6832 Update EIP-4844: change blob transaction type to 0x03
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#6851 Update EIP-6551: Modified proxy implementation, registry arguments, and deployment method
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6857 Update EIP-6551: Update registry address to match deployment
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6327 Add EIP: Elastic Signature
  EIPS/eip-6327.md
  assets/eip-6327/zkpass-1.png
  assets/eip-6327/zkpass-2.png
  assets/eip-6327/zkpass-3.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6859 Update EIP-4788: Move to Draft
  EIPS/eip-4788.md
Labels: c-status, t-core, w-ci, e-review, s-draft

#6870 Update EIP-4788: minor nits for 4788
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#6871 Update EIP-5000: typo
  EIPS/eip-5000.md
Labels: c-update, t-core, a-review, s-draft

#6812 Update EIP-4881: Move to Review
  EIPS/eip-4881.md
Labels: c-status, t-interface, e-review, s-review

#6845 Update EIP-5773: Move to Final
  EIPS/eip-5773.md
Labels: c-status, t-erc, e-review, s-final

#6846 Update EIP-6059: Move to Final
  EIPS/eip-6059.md
Labels: c-status, t-erc, e-review, s-final

#6165 Update EIP-3690: Fix typo
  EIPS/eip-3690.md
Labels: c-update, t-core, a-review, s-stagnant

#6163 Update EIP-3267: Fixes typo
  assets/eip-3267/contracts/BaseLock.sol
  assets/eip-3267/contracts/BidOnAddresses.sol
Labels: a-review

#6164 Update EIP-1444: Fix typo
  EIPS/eip-1444.md
Labels: c-update, t-erc, a-review, s-stagnant

#6754 Update EIP-5008: Move to Review
  EIPS/eip-5008.md
Labels: c-status, t-erc, a-review, s-review

#6883 CI: Update eipw-lint-js to 0.4.3
  .github/workflows/ci.yml
Labels: e-consensus

#6892 CI: Fix renovate bug with jekyll-label-bot and eipw-action
  .github/renovate.json
  .github/workflows/jekyll-label-bot.yml
Labels: e-consensus

#6887 Update EIP-6672: Move to Review
  EIPS/eip-6672.md
  assets/eip-6672/contracts/ERC6672.sol
Labels: c-status, t-erc, e-review, s-review

#6895 Update EIP-6220: Move to Final
  EIPS/eip-6220.md
Labels: c-status, t-erc, e-review, s-final

#6896 Update EIP-6381: Move to Last Call
  EIPS/eip-6381.md
Labels: c-status, t-erc, e-review

#6556 Update EIP-5507: Move to Last Call
  EIPS/eip-5507.md
Labels: c-status, t-erc, e-review

#6893 Config: Add ethereum/eip-review-bot to renovate ignorelist
  .github/renovate.json
Labels: e-consensus

#6886 Update EIP-1185: Move to Draft
  EIPS/eip-1185.md
Labels: c-status, t-erc, e-review, s-draft

#6905 Update EIP-3860: Move to Final
  EIPS/eip-3860.md
Labels: c-status, t-core, a-review, s-final

#6902 Update EIP-4895: Move to Final
  EIPS/eip-4895.md
Labels: c-status, t-core, a-review, s-final

#6904 Update EIP-3855: Move to Final
  EIPS/eip-3855.md
Labels: c-status, t-core, w-ci, a-review, s-final

#6908 Update EIP-5639: update eip-5639 and eip-6551 author info. Fix typo in eip-6551
  EIPS/eip-5639.md
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft, s-review

#6903 Update EIP-3651: Move to Final
  EIPS/eip-3651.md
Labels: c-status, t-core, a-review, s-final

#6922 Update EIP-6454: Extend Security Considerations
  EIPS/eip-6454.md
Labels: c-update, t-erc, w-ci

#6924 Update EIP-6120: simplify the standard
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#6185 Update EIP-5615: Move to Last Call
  EIPS/eip-5615.md
Labels: c-status, t-erc, e-review

#6928 Update EIP-5615: Move last call deadline until a month+
  EIPS/eip-5615.md
Labels: c-update, t-erc

#6755 Update EIP-5007: update ERC5007Composable.sol
  EIPS/eip-5007.md
  assets/eip-5007/README.md
  assets/eip-5007/contracts/ERC5007Composable.sol
  assets/eip-5007/contracts/ERC5007ComposableTest.sol
  assets/eip-5007/contracts/IERC5007Composable.sol
  assets/eip-5007/test/test.js
Labels: c-update, t-erc, a-review

#6913 Add EIP: SETCODE instruction
  EIPS/eip-6913.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#6936 Update EIP-5564: Fix EIP-5564 typos
  EIPS/eip-5564.md
Labels: c-update, t-erc, a-review, s-draft

#6935 CI: Bump eipw to 0.4.5
  .github/workflows/ci.yml
Labels: e-consensus

#6925 Update EIP-5656: Move to Review
  EIPS/eip-5656.md
Labels: c-status, t-core, e-review, s-review

#6941 Update EIP-5639: Add missing forward slash
  EIPS/eip-5639.md
Labels: c-update, t-erc, a-review, s-review

#6954 Update EIP-5656: Fix typos
  EIPS/eip-5656.md
Labels: c-update, t-core, a-review, s-review

#6957 Update EIP-6551: Returned to using ERC-1167 proxies for account creation
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6945 Update EIP-6475: Add `0x01` prefix for `Some`
  EIPS/eip-6404.md
  EIPS/eip-6475.md
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6466/helpers/ssz_receipt_types.py
  assets/eip-6475/optional.py
  assets/eip-6475/tests.py
Labels: c-update, t-core, s-draft

#6947 Update EIP-6493: Move to Review
  EIPS/eip-6493.md
Labels: c-status, t-core, e-review, s-review

#6946 Update EIP-6475: Move to Review
  EIPS/eip-6475.md
Labels: c-status, t-core, e-review, s-review
