Repository ethereum/EIPs, pull requests merged in 2023-02, with the labels that each got.

#6410 Updated EIP-5164: Removed getMessageExecutorAddress function
  EIPS/eip-5164.md
Labels: c-update, t-erc, s-review

#6415 learn how to spell
  EIPS/eip-6049.md
Labels: c-update, t-meta, s-final

#6414 This proposal has been superceded by the EOF proposals.
  EIPS/eip-2315.md
Labels: c-status, t-core, w-ci, s-withdrawn

#6373 Update EIP-5289: Move to Review
  EIPS/eip-5289.md
Labels: c-status, t-erc, s-review

#6374 Update EIP-6188: Move to Review
  EIPS/eip-6188.md
Labels: c-status, t-core, s-review

#6413 Update ERC-4955: Move to Final
  EIPS/eip-4955.md
Labels: c-status, t-erc, s-final

#6417 Update new design for better compatibility
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#6418 lint: fenced code block
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#6421 Update EIP-6150: fix bugs on reference implementation.
  EIPS/eip-6150.md
  assets/eip-6150/contracts/ERC6150.sol
  assets/eip-6150/contracts/ERC6150ParentTransferable.sol
Labels: c-update, t-erc

#6422 Update: relayer data + events added
  EIPS/eip-6170.md
Labels: c-update, t-erc, s-draft

#6423 Fix: Typo fixes in EIP-6170
  EIPS/eip-6170.md
Labels: c-update, t-erc, s-draft

#6442 5114: Moves to review and removes dependency.
  EIPS/eip-5114.md
Labels: c-status, t-erc, s-review

#6407 update ux image
  EIPS/eip-6384.md
  assets/eip-6384/media/ZenGo-EIP-compliant-warning.png
  assets/eip-6384/media/ZenGo-EIP-compliant.png
Labels: c-update, t-erc, s-draft

#5273 Update EIP-1: Reference ERCs by ERC-X
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6353 Add EIP-6353: Charity token
  EIPS/eip-6353.md
  assets/eip-6353/contracts/CharityToken.sol
  assets/eip-6353/contracts/ERC20Charity.sol
  assets/eip-6353/contracts/graphs/charity graph4.svg
  assets/eip-6353/contracts/graphs/test graph3.svg
  assets/eip-6353/contracts/interfaces/IERC20charity.sol
  assets/eip-6353/test/.gitkeep
  assets/eip-6353/test/charity.js
Labels: c-new, t-erc, s-draft

#6444 Update: EIP-6093: improve wording
  EIPS/eip-6093.md
Labels: c-update, t-erc, s-draft

#6446 Update eip-5749.md
  EIPS/eip-5749.md
Labels: c-update, t-interface

#6065 Add EIP-6065: EIP Real Estate Standard Token
  EIPS/eip-6065.md
  assets/eip-6065/corporate-structure.png
Labels: c-new, t-erc, s-draft

#6453 Update EIP-6150: update implementation
  EIPS/eip-6150.md
  assets/eip-6150/contracts/ERC6150.sol
  assets/eip-6150/contracts/ERC6150AccessControl.sol
  assets/eip-6150/contracts/ERC6150Burnable.sol
  assets/eip-6150/contracts/ERC6150Enumerable.sol
  assets/eip-6150/contracts/ERC6150ParentTransferable.sol
Labels: c-update, t-erc

#6452 Update EIP-6147: Move to Review
  EIPS/eip-6147.md
Labels: c-status, t-erc, s-review

#6451 Update EIP-1328 from Stagnant to Review
  EIPS/eip-1328.md
Labels: c-status, t-erc, w-ci, s-review

#6447 Update EIP-4736: Move to Review
  EIPS/eip-4736.md
Labels: c-status, t-interface, s-review

#6454 Propose Minimalistic Souldbound Extension for Non-Fungible Tokens
  EIPS/eip-6454.md
  assets/eip-6454/contracts/ISoulbound.sol
  assets/eip-6454/contracts/mocks/ERC721SoulboundMock.sol
  assets/eip-6454/hardhat.config.ts
  assets/eip-6454/package.json
  assets/eip-6454/test/soulbound.ts
Labels: c-new, t-erc, s-draft

#6381 Propose Emotable Extension for Non-Fungible Tokens
  EIPS/eip-6381.md
  assets/eip-6381/contracts/Emotable.sol
  assets/eip-6381/contracts/IEmotable.sol
  assets/eip-6381/contracts/mocks/ERC721EmotableMock.sol
  assets/eip-6381/hardhat.config.ts
  assets/eip-6381/package.json
  assets/eip-6381/test/emotable.ts
Labels: c-new, t-erc, s-draft

#6456 Update EIP-4938: Move to Review
  EIPS/eip-4938.md
Labels: c-status, t-networking, s-review

#6030 Update EIP-4844: update to Review status
  EIPS/eip-4844.md
Labels: c-status, t-core, s-review

#6462 update eip-5585
  EIPS/eip-5585.md
Labels: c-update, t-erc, s-draft

#6364 Update eip-5585.md
  EIPS/eip-5585.md
Labels: c-update, t-erc, w-ci, s-draft

#6461 Update EIP-6150: Move to Final
  EIPS/eip-6150.md
Labels: c-status, t-erc, s-final

#6443 Update EIP-5018: Move to Review
  EIPS/eip-5018.md
Labels: c-status, t-erc, s-review

#6375 Update EIP-6189: Move to Review
  EIPS/eip-6189.md
Labels: c-status, t-core, w-ci, s-review

#6376 Update EIP-6190: Move to Review
  EIPS/eip-6190.md
Labels: c-status, t-core, w-ci, s-review

#6465 Add EIP-6465: SSZ withdrawals root
  EIPS/eip-6465.md
Labels: c-new, t-core, s-draft

#5508 CI: Upgrade EIP-Bot to eip-review-bot
  .github/workflows/auto-review-bot.yml
  config/eip-editors.yml
Labels: e-consensus

#6468 Update EIP-5219: Make small change to test something
  EIPS/eip-5219.md
Labels: c-update, t-erc, s-review

#5703 Adds @xinbenlv as an EIP Editor (#5502)
  config/eip-editors.yml
Labels: e-consensus

#6459 Update EIP-2255: Add myself as an author and move back to review
  EIPS/eip-2255.md
Labels: c-status, t-interface, s-review

#6395 Update EIP-5625: Move to Review
  EIPS/eip-5625.md
Labels: c-status, t-erc, w-ci, s-review

#6404 Add EIP: SSZ transactions root
  EIPS/eip-6404.md
Labels: c-new, t-core, s-draft

#6470 Update EIP-2255: Make a few minor grammatical fixes
  EIPS/eip-2255.md
Labels: c-update, t-interface, s-review

#6471 Update EIP-2255: Fix another issue
  EIPS/eip-2255.md
Labels: c-update, t-interface, s-review

#6472 Update EIP-2255: Fix a few more typos
  EIPS/eip-2255.md
Labels: c-update, t-interface, s-review

#6473 Update README: Reference correct bot
  README.md
Labels: w-ci

#6031 Update EIP-5793: update EIP to Review status (eth/68)
  EIPS/eip-5793.md
Labels: c-status, t-networking, s-review

#6476 EIP-6404: Use `CHAIN_ID_LEGACY` instead of `tx_subtype`
  EIPS/eip-6404.md
Labels: c-update, t-core, s-draft

#6481 Update EIP-5267: Move to Final status
  EIPS/eip-5267.md
Labels: c-status, t-erc, s-final

#6477 Add myself to EIP-1 list
  EIPS/eip-1.md
Labels: c-update, t-process, w-ci

#6486 Update EIP-6475: Add tests and implementation
  EIPS/eip-6475.md
  assets/eip-6475/optional.py
  assets/eip-6475/tests.py
Labels: c-update, t-core, s-draft

#6488 Update EIP-6454: Change name from Soulbound to Non-Transferrable
  EIPS/eip-6454.md
  assets/eip-6454/contracts/INonTransferrable.sol
  assets/eip-6454/contracts/ISoulbound.sol
  assets/eip-6454/contracts/mocks/ERC721NonTransferrableMock.sol
  assets/eip-6454/package.json
  assets/eip-6454/test/nonTransferrable.ts
Labels: c-update, t-erc, s-draft

#6490 Revive ERC-998
  EIPS/eip-998.md
Labels: c-status, t-erc, s-draft

#6467 Update EIP-5069: Minor changes & eip-review-bot update
  EIPS/eip-5069.md
Labels: c-update, t-process

#6494 Update EIP-6475: Cleanup and add Nim impl
  EIPS/eip-6475.md
Labels: c-update, t-core, s-draft

#6460 Update EIP-747: Add myself as an author and move back to Review
  EIPS/eip-747.md
Labels: c-status, t-interface, s-review

#6278 Update README: Fix formatting
  README.md
Labels: e-review, r-website

#6268 Add EIP-6268: Untransferability Indicator for EIP-1155
  EIPS/eip-6268.md
Labels: c-new, t-erc, s-draft

#6105 Add EIP-6105: Marketplace extension for EIP-721
  EIPS/eip-6105.md
Labels: c-new, t-erc, s-draft

#6279 CI: Rename auto label bot
  .github/workflows/jekyll-label-bot.yml
Labels: e-review, r-ci

#6397 EIP-6206: Simplify JUMPF validation
  EIPS/eip-6206.md
Labels: c-update, t-core, s-draft

#6466 Add EIP-6466: SSZ receipts root
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
Labels: c-new, c-update, t-core, s-draft

#6499 Update EIP-6465/6466/6404: Mention correct type for LC use case
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
Labels: c-update, t-core, s-draft

#6500 More sane limits on blobs per transactions
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#6502 Update EIP-6404: Opaque transaction signatures
  EIPS/eip-6404.md
Labels: c-update, t-core, w-ci, s-draft

#6505 Updates interface Id for EIP6381
  EIPS/eip-6381.md
  assets/eip-6381/test/emotable.ts
Labels: c-update, t-erc, w-ci, s-draft

#6507 Updates interface Id and renames EIP references to ERC.
  EIPS/eip-6059.md
Labels: c-update, t-erc, w-ci, s-review

#6512 Rename to Token-Bound NFT License and update the license terms
  EIPS/eip-5218.md
  assets/eip-5218/ic3license/ic3license.pdf
  assets/eip-5218/ic3license/ic3license.tex
Labels: c-update, t-erc, w-ci, s-draft

#6511 Update EIPs: Use my real name in authors field
  EIPS/eip-2255.md
  EIPS/eip-2771.md
  EIPS/eip-4834.md
  EIPS/eip-5069.md
  EIPS/eip-5219.md
  EIPS/eip-5289.md
  EIPS/eip-5380.md
  EIPS/eip-5507.md
  EIPS/eip-5568.md
  EIPS/eip-5615.md
  EIPS/eip-5920.md
  EIPS/eip-6188.md
  EIPS/eip-6189.md
  EIPS/eip-6190.md
  EIPS/eip-747.md
Labels: c-update, t-core, t-erc, t-interface, t-process, s-review, s-final

#6521 Update EIP-3770: Move to Review
  EIPS/eip-3770.md
Labels: c-status, t-erc, s-review

#6523 Update EIP-6404: Optimize SSZ layout, include `from` / `to`
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  EIPS/eip-6475.md
  assets/eip-6404/images/transaction.graffle
  assets/eip-6404/images/transaction.pdf
  assets/eip-6404/images/transaction.png
  assets/eip-6475/tests.py
Labels: c-update, t-core, s-draft

#6524 Update EIP-6404: Add network / storage comparison
  EIPS/eip-6404.md
  assets/eip-6404/images/transaction.graffle
  assets/eip-6404/images/transaction.pdf
  assets/eip-6404/images/transaction.png
  assets/eip-6404/tests/create_transactions.py
  assets/eip-6404/tests/eip2718_tx_types.py
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/sign_transaction.py
  assets/eip-6404/tests/union/convert_transactions.py
  assets/eip-6404/tests/union/ssz_tx_types.py
Labels: c-update, t-core, s-draft

#6526 Update EIP-6404: Add snappy metrics, rm `TransactionDetails`
  EIPS/eip-6404.md
  assets/eip-6404/images/transaction.graffle
  assets/eip-6404/images/transaction.pdf
  assets/eip-6404/images/transaction.png
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/union/convert_transactions.py
Labels: c-update, t-core, s-draft

#6520 Update eip-6147.md
  EIPS/eip-6147.md
Labels: c-update, t-erc, s-review

#6529 Update EIP-6404: Add SSZ proof creation tests
  EIPS/eip-6404.md
  assets/eip-6404/tests/create_transactions.py
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/create_proofs.py
  assets/eip-6404/tests/normalized/ssz_proof_types.py
  assets/eip-6404/tests/proof_helpers.py
  assets/eip-6404/tests/union/convert_transactions.py
  assets/eip-6404/tests/union/create_proofs.py
  assets/eip-6404/tests/union/ssz_proof_types.py
Labels: c-update, t-core, s-draft

#6528 Update EIP-1: Add name to EIP Editors
  EIPS/eip-1.md
Labels: c-update, t-process, w-ci

#6532 Update EIP-5773: Fix a typo
  EIPS/eip-5773.md
Labels: c-update, t-erc, s-review

#6533 Update 6381: Fix a typo
  EIPS/eip-6381.md
Labels: c-update, t-erc, s-draft

#6534 Update 6454: Fix typos in the EIP-6454
  EIPS/eip-6454.md
Labels: c-update, t-erc, s-draft

#6531 ERC-5114: Some wording changes regarding badge vs. token
  EIPS/eip-5114.md
Labels: c-update, t-erc, a-review, s-review

#6535 Update eip-5114.md
  EIPS/eip-5114.md
Labels: c-update, t-erc, s-review

#6530 Move to Last Call
  EIPS/eip-6147.md
Labels: c-status, t-erc

#6536 Update 6454: Upgrade EIP-6454 to review status
  EIPS/eip-6454.md
Labels: c-status, t-erc, s-review

#6484 Update EIP-5805: Refer to EIP-6372 for clock and move to Review
  EIPS/eip-5805.md
Labels: c-status, t-erc, s-review

#6449 Update EIP-4361: Move to Review
  EIPS/eip-4361.md
Labels: c-status, t-erc, s-review

#6261 EIP-4750: Change checks to asserts
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#6489 Update EIP-6381: Upgrade to Review status
  EIPS/eip-6381.md
Labels: c-status, t-erc, s-review

#6337 Update eip-4337.md
  EIPS/eip-4337.md
Labels: c-update, t-erc, w-ci, s-draft

#6315 Add EIP-6315: EIP-2771 Account Abstraction
  EIPS/eip-6315.md
Labels: c-new, t-erc, s-draft

#6455 Update eip-5564 - add address format and meta data
  EIPS/eip-5564.md
  assets/eip-5564/EllipticCurve.sol
  assets/eip-5564/gnosisSafeModule.sol
  assets/eip-5564/scheme_ids.md
Labels: c-update, t-erc, s-draft

#6416 Update eip-1418.md
  EIPS/eip-1418.md
Labels: c-update, t-core, s-draft

#6537 Update EIP-6404: Add proof verification requirements
  EIPS/eip-6404.md
  assets/eip-6404/tests/eip2718_tx_types.py
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/create_proofs.py
  assets/eip-6404/tests/normalized/ssz_proof_types.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/normalized/verify_proofs.py
  assets/eip-6404/tests/union/convert_transactions.py
  assets/eip-6404/tests/union/create_proofs.py
  assets/eip-6404/tests/union/ssz_proof_types.py
  assets/eip-6404/tests/union/verify_proofs.py
Labels: c-update, t-core, s-draft

#6366 Add EIP-6366: Permission Token
  EIPS/eip-6366.md
  assets/eip-6366/contracts/EIP6366Core.sol
  assets/eip-6366/contracts/EIP6366Meta.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Core.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Error.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Meta.sol
  assets/eip-6366/example/AEcosystem.sol
  assets/eip-6366/example/APermissionToken.sol
  assets/eip-6366/example/APermissioned.sol
Labels: c-new, t-erc, s-draft

#6539 Update EIP-5727: update compatibility
  EIPS/eip-5727.md
Labels: c-update, t-erc, s-draft

#6540 Eip 5773 event improvement
  EIPS/eip-5773.md
  assets/eip-5773/contracts/IMultiAsset.sol
  assets/eip-5773/contracts/MultiAssetToken.sol
  assets/eip-5773/contracts/library/MultiAssetLib.sol
  assets/eip-5773/contracts/mocks/MultiAssetTokenMock.sol
  assets/eip-5773/contracts/utils/MultiAssetRenderUtils.sol
  assets/eip-5773/hardhat.config.ts
  assets/eip-5773/test/multiasset.ts
  assets/eip-5773/test/renderUtils.ts
Labels: c-update, t-erc, s-review

#6541 Updates event from ERC5573
  EIPS/eip-6220.md
  assets/eip-6220/contracts/EquippableToken.sol
  assets/eip-6220/contracts/IERC5773.sol
  assets/eip-6220/hardhat.config.ts
  assets/eip-6220/test/catalog.ts
  assets/eip-6220/test/equippableFixedParts.ts
  assets/eip-6220/test/equippableSlotParts.ts
  assets/eip-6220/test/multiasset.ts
  assets/eip-6220/test/nestable.ts
  assets/eip-6220/test/renderUtils.ts
Labels: c-update, t-erc, s-review

#6548 Update EIP-5749: Move to Final
  EIPS/eip-5749.md
Labels: c-status, t-interface, s-final

#6550 Update EIP-5902: Smart Contract Event Hooks
  EIPS/eip-5902.md
Labels: c-update, t-erc, s-draft

#6463 Update EIP-5585: Remove staking functions and move to Review
  EIPS/eip-5585.md
Labels: c-status, t-erc, a-review, s-review

#6552 Update EIP-6315: Use real name in author list & fix walidator stuff
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#6553 Update EIP-5507: Add batch refunds
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-review

#6555 Update EIP-5615: Fill out security considerations
  EIPS/eip-5615.md
Labels: c-update, t-erc, s-review

#6559 Update EIP-5219: Add note in Rationale for implementers, and make language more formal
  EIPS/eip-5219.md
Labels: c-update, t-erc, s-review

#6564 Update EIP-2255: Add SSRF consideration
  EIPS/eip-2255.md
Labels: c-update, t-interface, s-review

#6565 Update EIP-5507: Improve Motivation and add refundFrom
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-review

#6566 Update EIP-5219: Add "none" to security considerations
  EIPS/eip-5219.md
Labels: c-update, t-erc, s-review

#6567 Update EIP-6315: Add Rationale section
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#6557 Update EIP-747: Move to Last Call
  EIPS/eip-747.md
Labels: c-status, t-interface

#6554 Update EIP-5380: Move to Last Call
  EIPS/eip-5380.md
Labels: c-status, t-erc

#6357 Add EIP-6357: Single-contract Multi-delegatecall
  EIPS/eip-6357.md
Labels: c-new, t-erc, s-draft

#6569 Update EIP-6404: Add embedded benchmarks
  EIPS/eip-6404.md
  assets/eip-6404/tests/eip2718_tx_types.py
  assets/eip-6404/tests/normalized/create_proofs.py
  assets/eip-6404/tests/normalized/ssz_proof_types.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/normalized/verify_proofs.c
  assets/eip-6404/tests/normalized/verify_proofs.py
  assets/eip-6404/tests/union/create_proofs.py
  assets/eip-6404/tests/union/ssz_proof_types.py
  assets/eip-6404/tests/union/verify_proofs.c
  assets/eip-6404/tests/union/verify_proofs.py
Labels: c-update, t-core, s-draft

#6571 Update EIP-5507: Fix small typo
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-review

#6572 Update EIP-5507: Expand on wallet prompt motivation
  EIPS/eip-5507.md
Labels: c-update, t-erc, s-review

#6551 Add EIP: Non-fungible Token Bound Accounts
  EIPS/eip-6551.md
  assets/eip-6551/diagram.png
Labels: c-new, t-erc, s-draft

#6573 Update EIP-1: Fix markdownlint and link checker error
  EIPS/eip-1.md
  config/mlc_config.json
Labels: c-update, t-process

#6538 Add Stealth Meta-Address Registry
  EIPS/eip-6538.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6492 Add EIP: Signature Validation for Pre-Deploy Contracts
  EIPS/eip-6492.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6047 Add EIP-6047: Extend ERC-721 to Support balance counting via Transfer event
  EIPS/eip-6047.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#5883 Add EIP-5883: Token Transfer by Social Recovery
  EIPS/eip-5883.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6411 Update EIP-4804: Move to Last Call
  EIPS/eip-4804.md
Labels: c-status, t-erc, e-review

#6576 Update EIP-747: Specify behavior in the case of an existing token
  EIPS/eip-747.md
Labels: c-update, t-interface

#6563 Update EIP-1046: Move back to Review and add myself as author
  EIPS/eip-1046.md
Labels: c-status, t-erc, a-review, s-review

#6578 Update EIP-1046: ERC-1155 Interoperability Extension
  EIPS/eip-1046.md
Labels: c-update, t-erc, s-review

#6580 Update EIP-1046: Change focus to interop
  EIPS/eip-1046.md
Labels: c-update, t-erc, s-review

#6582 Update EIP-747: Remove required image types
  EIPS/eip-747.md
Labels: c-update, t-interface

#6493 Add EIP-6493: SSZ Transaction Signature Scheme
  EIPS/eip-6493.md
  assets/eip-6493/security/collision.py
Labels: c-new, t-core, e-review, s-draft, e-consensus

#6586 Update eip-6105.md
  EIPS/eip-6105.md
Labels: c-update, t-erc, s-draft

#6587 Update eip-6105.md
  EIPS/eip-6105.md
Labels: c-update, t-erc, s-draft

#6585 CI: Fix w-response labeling issue
  .github/workflows/auto-review-trigger.yml
Labels: e-consensus

#6568 Update EIP-5725: Finalizing Draft
  EIPS/eip-5725.md
  assets/eip-5725/contracts/ERC5725.sol
  assets/eip-5725/contracts/IERC5725.sol
Labels: c-update, t-erc, s-draft

#6581 Update EIP-1046: Move to Last Call
  EIPS/eip-1046.md
Labels: c-status, t-erc, e-review, e-blocking

#6591 Update ERC-747: Re-add legacy ERC-20 type
  EIPS/eip-747.md
Labels: c-update, t-interface

#6595 Update: Interface upgrade
  EIPS/eip-6170.md
Labels: c-update, t-erc, s-draft
