Repository ethereum/EIPs, pull requests merged in 2023-12, with the labels that each got.

#7990 Update EIP-4844: Clarify blob retention window part
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#8011 Update EIP-3074: update 3074 MAGIC byte
  EIPS/eip-3074.md
Labels: c-update, t-core, a-review, s-review

#8017 Update EIP-7549: fix typo #8015
  EIPS/eip-7549.md
Labels: c-update, t-core, a-review, s-draft

#8018 Update EIP-7480: implicit zero-padding on out-of-bounds access
  EIPS/eip-7480.md
Labels: c-update, t-core, s-draft

#8021 Update EIP-4750: Rename CALLF's argument to target_section_index
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#8022 Update EIP-6206: rename JUMPF's argument to target_section_index
  EIPS/eip-6206.md
Labels: c-update, t-core, s-draft

#8006 Add EIP: Hardfork Meta - Dencun
  EIPS/eip-7569.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8008 Update EIP-6122: Move to Last Call
  EIPS/eip-6122.md
Labels: c-status, t-networking, a-review

#8009 Update EIP-6780: Move to Review
  EIPS/eip-6780.md
Labels: c-status, t-core, a-review, s-review

#8000 Update EIP-6953: Move to Last Call
  EIPS/eip-6953.md
Labels: c-status, t-informational, e-review

#8027 Update EIP-7569: Move to Review
  EIPS/eip-7569.md
Labels: c-status, t-meta, e-review, s-review

#7967 Update EIP-6475: simple typo fix in 6475
  EIPS/eip-6475.md
Labels: c-update, t-core, w-ci, a-review, s-draft

#8029 Update EIP-7545: clarify precompile interface
  EIPS/eip-7545.md
Labels: c-update, t-core, w-ci, s-draft

#7943 Add EIP: Inclusion lists
  EIPS/eip-7547.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8049 Update EIP-3074: fix misaligned memory description
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8050 Update EIP-3074: add nonce to auth msg to provide revocation
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#7946 Update EIP-6690: fix typo & linter error
  EIPS/eip-6690.md
Labels: c-update, t-core, w-ci, a-review, s-draft

#7947 Update EIP-5806: fix typo
  EIPS/eip-5806.md
Labels: c-update, t-core, a-review, s-draft

#8054 Update EIP-6493: Move to Review
  EIPS/eip-6493.md
Labels: c-status, t-core, e-review, s-review
