Repository ethereum/EIPs, pull requests merged in 2023-10, with the labels that each got.

#7803 Update EIP-7480: Change prices of DATALOAD and DATALOADN to be consistent with price of PUSH
  EIPS/eip-7480.md
Labels: c-update, t-core, s-draft

#7251 Add EIP: Increase the MAX_EFFECTIVE_BALANCE
  EIPS/eip-7251.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7423 Update EIP-1559: Clarify who pays gas fees
  EIPS/eip-1559.md
Labels: c-update, t-core, w-ci, s-final, e-consensus

#7505 Update EIP-820: Remove superfluous pre tag
  EIPS/eip-820.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7506 Update EIP-1820: Remove superfluous pre tag
  EIPS/eip-1820.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7790 Update EIP-6963: make icon requirement wording consistent
  EIPS/eip-6963.md
Labels: c-status, t-interface, a-review, s-review

#7804 Update EIP-7053: Move to Final
  EIPS/eip-7053.md
Labels: c-status, t-erc, e-review, s-final

#7739 Add EIP: General Intents for Smart Contract Wallets
  EIPS/eip-7521.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7821 Update EIP-7085: update EIP-7085
  EIPS/eip-7085.md
Labels: c-update, t-erc, s-draft

#7811 Update EIP-6808: Move to Final
  EIPS/eip-6808.md
Labels: c-status, t-erc, e-review, s-final

#7816 Update EIP-6963: Move to Final
  EIPS/eip-6963.md
Labels: c-status, t-interface, e-review, s-final

#7841 Update EIP-6110: fix typo
  EIPS/eip-6110.md
Labels: c-update, t-core, a-review, s-draft

#7813 Update EIP-7503: Move to Review
  EIPS/eip-7503.md
Labels: c-status, t-core, e-review, s-review

#7858 Update EIP-6315: Rewrite
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#7834 Update EIP-6956: Fix typos
  EIPS/eip-6956.md
  EIPS/eip-7092.md
  EIPS/eip-7160.md
  EIPS/eip-7508.md
Labels: c-update, t-erc, a-review, s-draft, s-review

#7860 Update EIP-6465: Fix typo
  EIPS/eip-6465.md
Labels: c-update, t-core, a-review, s-draft

#7862 Update EIP-6900: Spec Update 5
  EIPS/eip-6900.md
Labels: c-update, t-erc, a-review, s-draft

#7418 Add EIP: Token Converter
  EIPS/eip-7417.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7845 Update EIP-7015: allow arbitratry `TYPEHASH` and correponding fields for `structHash`
  EIPS/eip-7015.md
  assets/eip-7015/contracts/DelegatedErc721.sol
  assets/eip-7015/contracts/EIP7015.sol
  assets/eip-7015/js-test/abi.ts
  assets/eip-7015/js-test/delegatedErc721.test.ts
  assets/eip-7015/package.json
Labels: c-update, t-erc, a-review, s-draft

#7868 Update EIP-7503: fix typo
  EIPS/eip-7503.md
Labels: c-update, t-core, a-review, s-review

#7867 Update EIP-6956: fix a couple of typos
  EIPS/eip-6956.md
Labels: c-update, t-erc, a-review, s-draft

#6860 Add EIP: Web3 URL to EVM Call Message Translation
  EIPS/eip-6860.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7863 Update EIP-6963: fix typo
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-final, e-consensus

#7843 Update EIP-6492: fix typos
  EIPS/eip-6492.md
Labels: c-update, t-erc, s-final, e-consensus

#7840 Update EIP-6672: fix typos
  EIPS/eip-6672.md
Labels: c-update, t-erc, s-final, e-consensus

#7872 Update EIP-1046: Fix some issues
  EIPS/eip-1046.md
Labels: c-update, t-erc, s-final

#7484 Add EIP: Registries and Adapters for Smart Accounts
  EIPS/eip-7484.md
  assets/eip-7484/check-sequence.jpg
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7808 Add EIP: ETH (Native Asset) Address Convention
  EIPS/eip-7528.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7779 Update EIP-7201: Move to Last Call
  EIPS/eip-7201.md
Labels: c-status, t-erc, e-review

#6914 Add EIP: Reuse Withdrawn Validator Indices
  EIPS/eip-6914.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7887 Add EIP: eth/69 - available-blocks-extended protocol
  EIPS/eip-7542.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#7908 Update EIP-6493: Align list style with EIP-4844
  EIPS/eip-6493.md
Labels: c-update, t-core, s-draft

#7910 Update EIP-6093: Include error-decoded operations in the Security Considerations
  EIPS/eip-6093.md
Labels: c-update, t-erc

#6561 Update EIP-6315: Move to Review
  EIPS/eip-6315.md
Labels: c-status, t-erc, e-review, s-review

#6770 Update EIP-6366: Move to Review
  EIPS/eip-6366.md
  assets/eip-6366/contracts/EIP6366Meta.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Meta.sol
  assets/eip-6366/example/AEcosystem.sol
  assets/eip-6366/example/APermissionToken.sol
  assets/eip-6366/example/APermissioned.sol
Labels: c-status, t-erc, e-review, s-review

#7913 Update EIP-6493: Move `type` from `signature` to `payload`
  EIPS/eip-6493.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/transaction.png
  assets/eip-6493/tx_hashes.py
Labels: c-update, t-core, s-draft

#7647 Update EIP-5564: Move to Review
  EIPS/eip-5564.md
Labels: c-status, t-erc, e-review, s-review

#7917 Update EIP-6120: ERC-165 interface
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#7923 Config: update pr template with ercs moved notice
  .github/PULL_REQUEST_TEMPLATE.md
Labels: e-consensus

#7924 Update README: add notice about repo split in readme
  README.md
Labels: e-consensus

#7906 Update EIP-7542: Update EIP-7542 to reflect its alignment with EIP-4444
  EIPS/eip-7542.md
Labels: c-update, t-networking, e-review, s-draft, e-consensus

#7932 Update EIP-4844: fix typo on blob batch verification function name
  EIPS/eip-4844.md
Labels: c-update, t-core, w-ci, a-review, s-review

#7937 Update EIP-7495: Mention support for optional fields in motivation
  EIPS/eip-7495.md
Labels: c-update, t-core, w-ci, s-review
