Repository ethereum/EIPs, pull requests merged in 2023-03, with the labels that each got.

#6597 Update EIP-747: `Ethereum address` -> address
  EIPS/eip-747.md
Labels: c-update, t-interface

#6593 Update EIP-6066: Move to Review
  EIPS/eip-6066.md
Labels: c-status, t-erc, e-review, s-review

#6599 Update EIP-4804: Move to final
  EIPS/eip-4804.md
Labels: c-status, t-erc, e-review, s-final

#6543 Update EIP-1: Add option to use GitHub username and email at once
  EIPS/eip-1.md
Labels: c-update, t-process, w-ci, e-consensus

#6464 Add EIP-6464: Multi-operator, per-token ERC721 approval
  EIPS/eip-6464.md
  assets/eip-6464/contracts/IERC165.sol
  assets/eip-6464/contracts/IERC6464.sol
  assets/eip-6464/contracts/IERC721.sol
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6558 Update EIP-2255: Move to Last Call
  EIPS/eip-2255.md
Labels: c-status, t-interface, e-review

#6611 Update ERC-6551: Reference implementation bugfixes + deployment transaction
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6612 ERC-6551: Added event emission to reference implementation
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#6613 Update eip-6105.md
  EIPS/eip-6105.md
Labels: c-update, t-erc, s-draft

#6614 EIP-6120: add the UTR contract address
  EIPS/eip-6120.md
Labels: c-update, t-erc, w-ci, s-review

#6619 Adds Contract and Serial Number field to the schema
  EIPS/eip-5570.md
Labels: c-update, t-erc, s-review

#6358 Add EIP-6358: Omniverse Token Protocol
  EIPS/eip-6358.md
  assets/eip-6358/img/o-dlt.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6623 Update EIP-6147: Move to Final
  EIPS/eip-6147.md
Labels: c-status, t-erc, e-review, s-final

#6625 Update EIP-223: update the event specification code
  EIPS/eip-223.md
Labels: c-update, t-erc, s-draft

#6626 Update EIP-223: remove extra code from the example
  EIPS/eip-223.md
Labels: c-update, t-erc, s-draft

#6636 Update EIP-5773: Update interface
  EIPS/eip-5773.md
  assets/eip-5773/contracts/IERC5773.sol
  assets/eip-5773/contracts/MultiAssetToken.sol
  assets/eip-5773/test/multiasset.ts
Labels: c-update, t-erc, s-review

#6637 Update EIP-6059 interface
  EIPS/eip-6059.md
  assets/eip-6059/contracts/IERC6059.sol
  assets/eip-6059/contracts/NestableToken.sol
  assets/eip-6059/package.json
  assets/eip-6059/test/nestable.ts
Labels: c-update, t-erc, s-review

#6638 Update ERC-6220 interface
  EIPS/eip-6220.md
  assets/eip-6220/contracts/EquippableToken.sol
  assets/eip-6220/contracts/IERC6220.sol
  assets/eip-6220/package.json
  assets/eip-6220/test/equippableSlotParts.ts
Labels: c-update, t-erc, s-review

#6641 Update EIP-5727: Remove old token interface design
  EIPS/eip-5727.md
Labels: c-update, t-erc, s-draft

#6644 Update EIP-6492: add a verification method that doesn't require pre-deploying a singleton
  EIPS/eip-6492.md
Labels: c-update, t-erc, w-ci, s-draft

#6645 Update EIP-6492: more consistent wording
  EIPS/eip-6492.md
Labels: c-update, t-erc, s-draft

#6647 Update EIP-6492: apply feedback
  EIPS/eip-6492.md
Labels: c-update, t-erc, s-draft

#5457 Update EIP-712: Fix `eth_signTypedData` definition
  EIPS/eip-712.md
Labels: c-update, t-interface, w-ci, s-final, e-consensus

#6639 Update ERC-5773: Move to Last Call
  EIPS/eip-5773.md
Labels: c-status, t-erc, e-review

#6649 Update EIP-223: Add author email as allowed by EIP-1
  EIPS/eip-223.md
Labels: c-update, t-erc, s-draft

#6640 Update ERC-6059: Move to Last Call
  EIPS/eip-6059.md
Labels: c-status, t-erc, e-review

#6634 Change status to draft
  EIPS/eip-4944.md
Labels: c-status, t-erc, e-review, s-draft

#6655 Update EIP-6357: Add Rationale
  EIPS/eip-6357.md
Labels: c-update, t-erc, s-draft

#6656 Update EIP-5615: Add EIP-165 note
  EIPS/eip-5615.md
Labels: c-update, t-erc, s-review

#6657 Update EIP-5219: @SamWilsn's review
  EIPS/eip-5219.md
Labels: c-update, t-erc, s-review

#6658 Update EIP-6315: Restrict the usage of EIP-2771
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#6624 Update eip-6105: Move to Review
  EIPS/eip-6105.md
Labels: c-status, t-erc, e-review, s-review

#6659 Update EIP-5920: Explicitly state account creation cost
  EIPS/eip-5920.md
Labels: c-update, t-core, s-review

#6474 Update EIP-5827: add implementation
  EIPS/eip-5827.md
  assets/eip-5827/ERC5827.sol
  assets/eip-5827/IERC5827.sol
Labels: c-update, t-erc, s-draft

#6663 Update EIP-6404/6465/6466: rm typed receipt wrapper, align style
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  assets/eip-6465/helpers/convert_withdrawals.py
  assets/eip-6465/helpers/eip4895_withdrawal_types.py
  assets/eip-6465/helpers/recover_withdrawals.py
  assets/eip-6465/helpers/ssz_withdrawal_types.py
  assets/eip-6466/helpers/convert_receipts.py
  assets/eip-6466/helpers/eip2718_receipt_types.py
  assets/eip-6466/helpers/recover_receipts.py
  assets/eip-6466/helpers/ssz_receipt_types.py
Labels: c-update, t-core, s-draft

#6665 Update EIP-6404: rm `chain_id` from txs wrapper
  EIPS/eip-6404.md
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/create_proofs.py
  assets/eip-6404/tests/normalized/ssz_proof_types.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/normalized/verify_proofs.c
  assets/eip-6404/tests/normalized/verify_proofs.py
  assets/eip-6404/tests/union/create_proofs.py
  assets/eip-6404/tests/union/verify_proofs.c
Labels: c-update, t-core, s-draft

#6617 Add EIP-6617: Add a new bit based permission proposal
  EIPS/eip-6617.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6667 Update EIP-6492: add on-chain validation
  EIPS/eip-6492.md
Labels: c-update, t-erc, w-ci, s-draft

#6668 Update EIP-6492: move to Review
  EIPS/eip-6492.md
Labels: c-status, t-erc, e-review, s-review

#6673 set EIP-5252 into review
  EIPS/eip-5252.md
Labels: c-update, t-erc, w-ci, e-review, s-draft

#6560 Update EIP-5219: Move to Last Call
  EIPS/eip-5219.md
Labels: c-status, t-erc, e-review

#6671 Updating EIP-4910 Status to Last Call
  EIPS/eip-4910.md
Labels: c-status, t-erc, w-ci, e-review

#6684 Website: Fix MathJax
  _includes/head.html
Labels: e-consensus

#6603 Update EIP-1: Follow the style guide rules
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#6688 EIP-6617: Fix solidity constant code
  EIPS/eip-6617.md
Labels: c-update, t-erc, s-draft

#6618 Update the EIP-6366
  EIPS/eip-6366.md
  assets/eip-6366/contracts/EIP6366Core.sol
  assets/eip-6366/contracts/EIP6366Meta.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Core.sol
  assets/eip-6366/contracts/interfaces/IEIP6366Meta.sol
  assets/eip-6366/example/APermissionToken.sol
  assets/eip-6366/example/APermissioned.sol
Labels: c-update, t-erc, s-draft

#6681 Move EIP-3651 to Last Call
  EIPS/eip-3651.md
Labels: c-status, t-core, e-review

#6692 Audit-related changes (23-Feb-2023)
  EIPS/eip-4337.md
Labels: c-update, t-erc, w-ci, s-draft

#6693 missing type update.
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#6678 Change status to draft
  EIPS/eip-4950.md
Labels: c-status, t-erc, e-review, s-draft

#6694 Update EIP-6492: fix a mistake and clarify edge cases
  EIPS/eip-6492.md
Labels: c-update, t-erc, s-review

#6697 Update EIP-747: Add additional non-normative clarifications
  EIPS/eip-747.md
Labels: c-update, t-interface

#6698 Update EIP-1046: Add additional non-normative clarifications
  EIPS/eip-1046.md
Labels: c-update, t-erc

#6695 Update ERC-5606: Move to Final
  EIPS/eip-5606.md
Labels: c-status, t-erc, e-review, s-final

#6702 Update EIP-5380: Add metadata extension
  EIPS/eip-5380.md
Labels: c-update, t-erc

#6654 Updates EIP-5573: Reflect changes in CACAO and UCAN specs
  EIPS/eip-5573.md
Labels: c-update, t-erc, s-draft

#6661 Update ERC-6358: Slimming down and change the title
  EIPS/eip-6358.md
  assets/eip-6358/src/.gitignore
  assets/eip-6358/src/README.md
  assets/eip-6358/src/contracts/ERC20.sol
  assets/eip-6358/src/contracts/ERC6358FungibleExample.sol
  assets/eip-6358/src/contracts/ERC6358NonFungibleExample.sol
  assets/eip-6358/src/contracts/interfaces/IERC6358.sol
  assets/eip-6358/src/contracts/interfaces/IERC6358Application.sol
  assets/eip-6358/src/contracts/interfaces/IERC6358Fungible.sol
  assets/eip-6358/src/contracts/interfaces/IERC6358NonFungible.sol
  assets/eip-6358/src/contracts/libraries/OmniverseProtocolHelper.sol
  assets/eip-6358/src/migrations/2_deploy_contracts.js
  assets/eip-6358/src/package.json
  assets/eip-6358/src/test/.gitkeep
  assets/eip-6358/src/test/ERC6358Fungible.test.js
  assets/eip-6358/src/test/ERC6358NonFungible.test.js
  assets/eip-6358/src/test/utils.js
Labels: c-update, t-erc, s-draft, e-consensus

#6328 EIP-3540: Clarify nonce behavior for CREATE
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#6737 EIP-5485 Move from Stagnant to Draft
  EIPS/eip-5485.md
Labels: c-status, t-erc, s-draft

#6738 Update ERC-6357: Add security considerations
  EIPS/eip-6357.md
Labels: c-update, t-erc, s-draft

#6739 Update EIP-6315: Use even less ERC-2771
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#6506 Add EIP: P2P Escrowed Governance Incentives
  EIPS/eip-6506.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6744 Update EIP-747: Fix some old stuff and typos
  EIPS/eip-747.md
Labels: c-update, t-interface

#6675 Update EIP-5252: Move to review
  EIPS/eip-5252.md
Labels: c-status, t-erc, w-ci, e-review, s-review

#6747 Update EIP-747: Fix some typos and some ambiguities
  EIPS/eip-747.md
Labels: c-update, t-interface

#6748 Update EIP-6189: Add informative note
  EIPS/eip-6189.md
Labels: c-update, t-core, s-review

#6751 Update EIP-6189: Fix some typos
  EIPS/eip-6189.md
Labels: c-update, t-core, w-ci, s-review, e-consensus

#6783 Update EIP-5521: Move to Draft
  EIPS/eip-5521.md
Labels: c-status, t-erc, e-review, s-draft

#6733 Add EIP: Revert creation in case of collision
  EIPS/eip-684.md
Labels: c-new, t-core, e-review, s-final, e-consensus

#6779 Update EIP-6110: Fixed typo in eip-6110.md
  EIPS/eip-6110.md
Labels: c-update, t-core, a-review, s-draft

#6788 Update EIP-6110: Fixed typo in eip-6110.md"
  EIPS/eip-6110.md
Labels: c-update, t-core, s-draft

#6780 Add EIP: SELFDESTRUCT only in same transaction
  EIPS/eip-6780.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#6792 Update EIP-6358: Move to Review
  EIPS/eip-6358.md
Labels: c-status, t-erc, e-review, s-review

#6662 Add EIP: AA Account Metadata For Authentication
  EIPS/eip-6662.md
  assets/eip-6662/auth-flow.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6794 CI: Remove redundant approve and auto merge actions
  .github/workflows/auto-review-bot.yml
Labels: e-consensus

#6760 Config: Fix c-new labeling for numberless EIPs
  config/.jekyll-labels.yml
Labels: e-consensus

#6771 Update EIP-5169: Move to Draft
  EIPS/eip-5169.md
  assets/eip-5169/contract/ExampleContract.sol
  assets/eip-5169/tokenscript/ExampleScript.xml
Labels: c-status, t-erc, e-review, s-draft

#6795 Update EIP-5773: Modify specification to consume less gas
  EIPS/eip-5773.md
  assets/eip-5773/contracts/IERC5773.sol
  assets/eip-5773/contracts/MultiAssetToken.sol
  assets/eip-5773/contracts/utils/MultiAssetRenderUtils.sol
  assets/eip-5773/test/multiasset.ts
  assets/eip-5773/test/renderUtils.ts
Labels: c-update, t-erc

#6796 Update EIP-6059: Update ERC-6059 to extend the security considerations
  EIPS/eip-6059.md
Labels: c-update, t-erc

#6801 Update EIP-6315: Avoid potential collisions
  EIPS/eip-6315.md
Labels: c-update, t-erc, s-draft

#6803 Update EIP-4895: add `mainnet` timestamp for shanghai fork
  EIPS/eip-4895.md
Labels: c-update, t-core, s-review

#6742 Update EIP-5380: Move to Final
  EIPS/eip-5380.md
Labels: c-status, t-erc, e-review, s-final

#6802 Update EIP-4881: Move to Draft
  EIPS/eip-4881.md
  assets/eip-4881/deposit_tree_evolution.png
  assets/eip-4881/deposit_tree_evolution.svg
Labels: c-status, t-interface, e-review, s-draft
