Repository ethereum/EIPs, pull requests merged in 2023-05, with the labels that each got.

#6964 Update EIP-6454: Use overloaded methods
  EIPS/eip-6454.md
  assets/eip-6454/contracts/IERC6454.sol
  assets/eip-6454/contracts/INonTransferable.sol
  assets/eip-6454/contracts/mocks/ERC721TransferableMock.sol
  assets/eip-6454/package.json
  assets/eip-6454/test/transferable.ts
Labels: c-update, t-erc, w-ci

#6972 Update EIP-6065: Eip real estate standard token
  EIPS/eip-6065.md
  assets/eip-6065/ERC6065.sol
  assets/eip-6065/corporate-structure.png
Labels: c-update, t-erc, s-draft, e-consensus

#6975 Update EIP-5564: add metadata description to eip-5564
  EIPS/eip-5564.md
Labels: c-update, t-erc, w-ci, s-draft

#6949 Update EIP-6672: Move to Last Call
  EIPS/eip-6672.md
  assets/eip-6672/contracts/ERC6672.sol
  assets/eip-6672/contracts/interfaces/IERC6672.sol
Labels: c-status, t-erc, e-review

#6966 Update EIP-5570: Move to Last Call
  EIPS/eip-5570.md
Labels: c-status, t-erc, e-review

#6977 CI: Revert to old version of eip-review-bot
  .github/workflows/auto-review-bot.yml
Labels: e-consensus

#6953 Add EIP: Network Upgrade Activation Triggers
  EIPS/eip-6953.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#6808 Add EIP: Fungible Key Bound Token
  EIPS/eip-6808.md
  assets/eip-6808/.gitignore
  assets/eip-6808/Contract Interactions diagram.svg
  assets/eip-6808/README.md
  assets/eip-6808/contracts/IKBT20.sol
  assets/eip-6808/contracts/KBT20.sol
  assets/eip-6808/contracts/MyFirstKBT.sol
  assets/eip-6808/migrations/1_deploy_contracts.js
  assets/eip-6808/package.json
  assets/eip-6808/test/kbt20.js
  assets/eip-6808/truffle-config.js
Labels: c-new, t-erc, a-review, s-draft, e-consensus

#6809 Add EIP: Non-Fungible Key Bound Token
  EIPS/eip-6809.md
  assets/eip-6809/.gitignore
  assets/eip-6809/Contract Interactions diagram.svg
  assets/eip-6809/README.md
  assets/eip-6809/contracts/IKBT721.sol
  assets/eip-6809/contracts/KBT721.sol
  assets/eip-6809/contracts/MyFirstKBT.sol
  assets/eip-6809/migrations/1_deploy_contracts.js
  assets/eip-6809/package.json
  assets/eip-6809/test/kbt721.js
  assets/eip-6809/truffle-config.js
Labels: c-new, t-erc, a-review, s-draft, e-consensus

#6979 Update EIP-6493: Drop `DomainType`, `fork_version`, `genesis_hash`
  EIPS/eip-6493.md
Labels: c-update, t-core, s-review

#6983 Update EIP-6493: Add SigningRoot reference
  EIPS/eip-6493.md
Labels: c-update, t-core, s-review

#6980 Update EIP-4788: Update eip-4788.md
  EIPS/eip-4788.md
Labels: c-update, t-core, a-review, s-draft

#6938 Update EIP-5169: Move to Last Call
  EIPS/eip-5169.md
Labels: c-status, t-erc, e-review

#6986 Update EIP-6066: Added ERC165 support, fixed interface ID
  EIPS/eip-6066.md
Labels: c-update, t-erc, s-review

#6989 Update EIP-5564: add link to eip-6538
  EIPS/eip-5564.md
Labels: c-update, t-erc, s-draft

#6951 Update EIP-1271: Change `an` to `a` in ERC 1271, as it precedes `signed`
  EIPS/eip-1271.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#6821 Add EIP: Support ENS Name for Web3 URL
  EIPS/eip-6821.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6900 Add EIP: Modular Smart Contract Accounts and Plugins
  EIPS/eip-6900.md
  assets/eip-modular-smart-contract-accounts-and-plugins/MSCA_Shared_Components_Diagram.svg
  assets/eip-modular-smart-contract-accounts-and-plugins/MSCA_Two_Call_Paths_Diagram.svg
Labels: c-new, t-erc, e-review, a-review, s-draft, e-consensus

#6993 Update EIP-6120: update desc and abstract
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#6994 Update ERC-5727: update new implementation
  EIPS/eip-5727.md
  assets/eip-5727/ERC5727.sol
  assets/eip-5727/ERC5727Claimable.sol
  assets/eip-5727/ERC5727Delegate.sol
  assets/eip-5727/ERC5727Enumerable.sol
  assets/eip-5727/ERC5727Expirable.sol
  assets/eip-5727/ERC5727Governance.sol
  assets/eip-5727/ERC5727Recovery.sol
  assets/eip-5727/interfaces/IERC5727.sol
  assets/eip-5727/interfaces/IERC5727Claimable.sol
  assets/eip-5727/interfaces/IERC5727Delegate.sol
  assets/eip-5727/interfaces/IERC5727Enumerable.sol
  assets/eip-5727/interfaces/IERC5727Expirable.sol
  assets/eip-5727/interfaces/IERC5727Governance.sol
  assets/eip-5727/interfaces/IERC5727Metadata.sol
  assets/eip-5727/interfaces/IERC5727Recovery.sol
Labels: c-update, t-erc, s-draft

#6995 Update EIP-5656: add test cases including overlapping memory regions
  EIPS/eip-5656.md
Labels: c-status, t-core, s-draft

#6998 Update EIP-5007: change int64 to uint64
  EIPS/eip-5007.md
  assets/eip-5007/contracts/ERC5007.sol
  assets/eip-5007/contracts/ERC5007Composable.sol
  assets/eip-5007/contracts/ERC5007ComposableTest.sol
  assets/eip-5007/contracts/ERC5007Demo.sol
  assets/eip-5007/contracts/IERC5007.sol
  assets/eip-5007/contracts/IERC5007Composable.sol
  assets/eip-5007/test/test.js
Labels: c-update, t-erc, a-review

#5717 Update EIP-1155: Fix arg order for balanceOf
  EIPS/eip-1155.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7000 Update EIP-5573: ERC-5573 update
  EIPS/eip-5573.md
Labels: c-update, t-erc, s-draft

#6546 Update EIP-4200: Allow `RJUMPV` table sizes of up to 256
  EIPS/eip-4200.md
Labels: c-update, t-core, a-review, s-review

#6930 Update EIP-5008: Move to Last Call
  EIPS/eip-5008.md
Labels: c-status, t-erc, a-review

#7008 Update EIP-4844: amend inconsistency in calc_data_fee
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#6811 Add EIP: To The Moon—10 Minute Blocks
  EIPS/eip-6811.md
Labels: c-new, t-core, w-ci, e-review, s-draft, e-consensus

#7026 Update EIP-6454: Update EIP-6454 with note about approvals
  EIPS/eip-6454.md
Labels: c-update, t-erc

#7005 Update EIP-4788: Fix typo
  EIPS/eip-4788.md
Labels: c-update, t-core, a-review, s-draft

#6458 Update EIP-2015: Move to Review
  EIPS/eip-2015.md
Labels: c-status, t-interface, a-review, s-review

#7033 CI: Bump eipw to 0.4.6
  .github/workflows/ci.yml
Labels: e-consensus

#6963 Add EIP: Multi Injected Provider Discovery
  EIPS/eip-6963.md
Labels: c-new, t-interface, w-ci, e-review, s-draft, e-consensus

#7030 Update EIP-107: Use standardized markdown formatting
  EIPS/eip-107.md
Labels: c-update, t-interface, w-ci, a-review, s-stagnant

#6985 Update EIP-4844: de-sszify spec
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#7001 Update EIP-4844: change op to `BLOBHASH`
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#6940 Update EIP-6105: Move to Final
  EIPS/eip-6105.md
Labels: c-status, t-erc, e-review, s-final

#7029 Update EIP-6672: Move to Final
  EIPS/eip-6672.md
Labels: c-status, t-erc, e-review, s-final

#7022 Update EIP-5615: Move to Final
  EIPS/eip-5615.md
Labels: c-status, t-erc, e-review, s-final

#7021 Update EIP-5507: Move to Final
  EIPS/eip-5507.md
Labels: c-status, t-erc, e-review, s-final

#7035 Update EIP-6551: Removed accidentally included SPDX license identifier
  EIPS/eip-6551.md
Labels: c-update, t-erc, s-draft

#7036 Update EIP-5700: Simplifies EIP-5700 after a year of review
  EIPS/eip-5700.md
  assets/eip-5700/erc1155/ERC1155Bindable.sol
  assets/eip-5700/erc1155/ERC1155Binder.sol
  assets/eip-5700/erc721/ERC721Bindable.sol
  assets/eip-5700/erc721/ERC721Binder.sol
  assets/eip-5700/interfaces/IBindableErrors.sol
  assets/eip-5700/interfaces/IERC1155BindableErrors.sol
  assets/eip-5700/interfaces/IERC1155Binder.sol
  assets/eip-5700/interfaces/IERC1155BinderErrors.sol
  assets/eip-5700/interfaces/IERC721Bindable.sol
  assets/eip-5700/interfaces/IERC721BindableErrors.sol
  assets/eip-5700/interfaces/IERC721Binder.sol
  assets/eip-5700/interfaces/IERC721BinderErrors.sol
Labels: c-update, t-erc, w-ci, s-draft

#6937 Update EIP-4955: Update eip-4955.md
  EIPS/eip-4955.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#6901 Update EIP-6454: Move to Final
  EIPS/eip-6454.md
Labels: c-update, t-erc, e-review

#7037 Update EIP-4788: send current slot from CL to avoid timestamp conversions
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7040 Update EIP-4844: Update eip-4844.md, fix typo
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#6847 Update EIP-5202: Move to Last Call
  EIPS/eip-5202.md
Labels: c-status, t-erc, e-review

#7046 Update EIP-6093: EIP6093 Corrections for ERC721
  EIPS/eip-6093.md
Labels: c-update, t-erc, s-draft

#6786 Add EIP: Registry for royalties payment for NFTs
  EIPS/eip-6786.md
  assets/eip-6786/README.md
  assets/eip-6786/contracts/ERC6786.sol
  assets/eip-6786/contracts/IERC6786.sol
  assets/eip-6786/contracts/token/ERC721Royalty.sol
  assets/eip-6786/contracts/utils/IERC2981.sol
  assets/eip-6786/test/ERC6786.test.js
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6865 Add EIP: On-Chain EIP-712 Visualization
  EIPS/eip-6865.md
  assets/eip-6865/contracts/IEIP712Visualizer.sol
  assets/eip-6865/contracts/SeaPortEIP712Visualizer.sol
  assets/eip-6865/current-EIP-712-signature-wallet-interface.png
  assets/eip-6865/vision-EIP-712-signature-wallet-interface.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6973 Update EIP-6065: Move to Review
  EIPS/eip-6065.md
  assets/eip-6065/Implementation.sol
  assets/eip-6065/corporate-structure.png
Labels: c-status, t-erc, e-review, s-review

#6956 Add EIP: Asset-bound Non-Fungible Tokens
  EIPS/eip-6956.md
  assets/eip-6956/.gitignore
  assets/eip-6956/LICENSE.md
  assets/eip-6956/README.md
  assets/eip-6956/contracts/ERC6956.sol
  assets/eip-6956/contracts/ERC6956Full.sol
  assets/eip-6956/contracts/IERC6956.sol
  assets/eip-6956/contracts/IERC6956AttestationLimited.sol
  assets/eip-6956/contracts/IERC6956Floatable.sol
  assets/eip-6956/contracts/IERC6956ValidAnchors.sol
  assets/eip-6956/img/erc6956_concept.svg
  assets/eip-6956/test/ERC6956.ts
  assets/eip-6956/test/ERC6956Full.ts
  assets/eip-6956/test/commons.ts
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7059 EIP-6093 Adjustment to ERC155 error
  EIPS/eip-6093.md
Labels: c-update, t-erc, s-draft

#6787 Add EIP: Order Book DEX with Two Phase Withdrawal
  EIPS/eip-6787.md
  assets/eip-6787/image1.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7065 Update EIP-4788: favor stateful precompile over opcode
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7070 Update EIP-6913: Setcode Opcode to 0xfc
  EIPS/eip-6913.md
Labels: c-update, t-core, s-draft

#7076 Update EIP-6963: Remove self as author of eip-6963.md
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7074 Update EIP-1153: EIP-1153 - Change TLOAD/TSTORE opcodes
  EIPS/eip-1153.md
Labels: c-update, t-core, a-review

#7080 Update EIP-6913: Clarify Parent Execution Scopes, and add to Rationale
  EIPS/eip-6913.md
Labels: c-update, t-core, s-draft

#7081 Update EIP-6913: Remove Deferral and Clarify Staticcall
  EIPS/eip-6913.md
Labels: c-update, t-core, s-draft

#7082 Update EIP-5920: Fix inconsistencies
  EIPS/eip-5920.md
Labels: c-update, t-core, s-review

#6583 Update EIP-4844: Refactor Validity Conditions
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#7088 Update EIP-6454: Move to Final
  EIPS/eip-6454.md
Labels: c-status, t-erc, e-review, s-final

#7068 Update EIP-5570: Move to Final
  EIPS/eip-5570.md
Labels: c-status, t-erc, e-review, s-final

#7078 Update EIP-6808: Move to Review
  EIPS/eip-6808.md
Labels: c-status, t-erc, e-review, s-review

#7079 Update EIP-6809: Move to Review
  EIPS/eip-6809.md
Labels: c-status, t-erc, e-review, s-review

#6239 Add EIP: Semantic Soulbound Tokens
  EIPS/eip-6239.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7045 Add EIP: Increase max attestation inclusion slot
  EIPS/eip-7045.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7089 Update EIP-5007: Move to Final
  EIPS/eip-5007.md
Labels: c-status, t-erc, a-review, s-final

#7094 Update EIP-6122: Move to Review
  EIPS/eip-6122.md
Labels: c-status, t-networking, e-review, s-review

#6830 Add EIP: Token Mapping Slot Retrieval Extension
  EIPS/eip-6823.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6944 Add EIP: ERC-5219 Resolve Mode
  EIPS/eip-6944.md
Labels: c-new, t-erc, w-ci, e-review, s-draft, e-consensus

#6981 Add EIP: Reserved Ownership Accounts
  EIPS/eip-6981.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7107 Update EIP-4788: key beacon roots by root
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft
