Repository ethereum/EIPs, pull requests merged in 2023-08, with the labels that each got.

#7445 Update EIP-4788: Mention genesis block with no existing beacon block root case
  EIPS/eip-4788.md
Labels: c-update, t-core, a-review, s-draft

#7446 Update EIP-5806: Fix typo in EIP-5806
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#7448 Update EIP-2135: Fix errors from EIPWalidator
  EIPS/eip-2135.md
Labels: c-update, t-erc, e-review

#7339 Update EIP-223: Move to Review
  EIPS/eip-223.md
Labels: c-status, t-erc, e-review, s-review

#7450 Update EIP-2135: Move to Final
  EIPS/eip-2135.md
Labels: c-status, t-erc, e-review, s-final

#7453 Update EIP-6963: use data URI for icon value in Wallet Provider implementation example
  EIPS/eip-6963.md
Labels: c-update, t-interface, a-review, s-review

#7181 Update EIP-6492: Move to Last Call
  EIPS/eip-6492.md
Labels: c-status, t-erc, e-review

#7444 Add EIP: Time Locks Maturity
  EIPS/eip-7444.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6898 Update EIP-5131: update authors
  EIPS/eip-5131.md
Labels: c-update, t-erc, w-ci, e-review, s-stagnant

#7447 Update EIP-1271: Update eip-1271.md
  EIPS/eip-1271.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7421 Update EIP-6982: Move to Review
  EIPS/eip-6982.md
Labels: c-status, t-erc, e-review, s-review

#7239 Update EIP-7144: Move to Review
  EIPS/eip-7144.md
Labels: c-status, t-erc, e-review, s-review

#7437 Update EIP-6551: Move to Review
  EIPS/eip-6551.md
Labels: c-status, t-erc, e-review, s-review

#7233 Update EIP-5793: change size type to prevent leading zeros
  EIPS/eip-5793.md
Labels: c-update, t-networking, s-review

#7231 Add EIP: Identity aggregated NFT
  EIPS/eip-7231.md
  assets/eip-7231/contracts/ERC7231.sol
  assets/eip-7231/contracts/interfaces/IERC7231.sol
  assets/eip-7231/contracts/mocks/ERC7231Mock.sol
  assets/eip-7231/img/Identity-aggregated-NFT-flow.png
  assets/eip-7231/test/erc7231.ts
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7303 Add EIP: Token-Controlled Token Circulation
  EIPS/eip-7303.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7463 Update EIP-7201: eip-7201.md
  EIPS/eip-7201.md
Labels: c-update, t-erc, a-review, s-draft

#7465 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc, s-review

#7467 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc, s-review

#7470 Update EIP-7329: Move to Review
  EIPS/eip-7329.md
Labels: c-status, t-meta, s-review

#7471 Update EIP-6492: fix a bug in sample code
  EIPS/eip-6492.md
Labels: c-update, t-erc

#7473 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc, s-review

#7485 Update EIP-5521: Move to Draft
  EIPS/eip-5521.md
Labels: c-update, t-erc, s-draft

#7490 Update EIP-7444: Replace broken mathematic equation with images
  EIPS/eip-7444.md
  assets/eip-7444/equation.png
Labels: c-update, t-erc, s-draft

#7489 Update EIP-4881: Move to Last Call
  EIPS/eip-4881.md
Labels: c-status, t-interface, e-review

#7493 Update EIP-6909: update eip-6909
  EIPS/eip-6909.md
Labels: c-update, t-erc, a-review, s-draft

#7496 Update EIP-5793: update for change to types
  EIPS/eip-5793.md
Labels: c-update, t-networking, a-review, s-review

#7494 Update EIP-6909: fix spelling mistakes
  EIPS/eip-6909.md
Labels: c-update, t-erc, a-review, s-draft

#7499 Update EIP-6909: Update reference implementation to specification
  EIPS/eip-6909.md
Labels: c-update, t-erc, s-draft

#7483 Update EIP-223: Move to Last Call
  EIPS/eip-223.md
Labels: c-status, t-erc, e-review

#7504 Update EIP-6120: Update ERC-6120
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#7397 Update EIP-820: Fix accidental tag
  EIPS/eip-820.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7398 Update EIP-1820: Fix same tagging issue
  EIPS/eip-1820.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7405 Add EIP: Portable Smart Contract Accounts
  EIPS/eip-7405.md
  assets/eip-7405/overview-diagram.jpg
Labels: c-new, t-erc, w-ci, e-review, s-draft, e-consensus

#7497 Update EIP-4844: Remove unused constants
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#7347 CI: Single-workflow auto-review-bot
  .github/workflows/auto-review-bot.yml
  .github/workflows/auto-review-trigger.yml
Labels: e-consensus

#7414 Update EIP-7401: Move to Review
  EIPS/eip-7401.md
Labels: c-status, t-erc, e-review, s-review, e-consensus

#7435 Update EIP-1822: remove unnecessary toc
  EIPS/eip-1822.md
Labels: c-update, t-erc, e-review, s-stagnant

#7409 Add EIP: Public Non-Fungible Tokens Emote Repository
  EIPS/eip-7409.md
  assets/eip-7409/contracts/EmotableRepository.sol
  assets/eip-7409/contracts/IERC7409.sol
  assets/eip-7409/contracts/mocks/ERC721Mock.sol
  assets/eip-7409/hardhat.config.ts
  assets/eip-7409/package.json
  assets/eip-7409/test/emotableRepository.ts
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7006 Update EIP-3026: Move to Draft
  EIPS/eip-3026.md
Labels: c-status, t-core, w-ci, a-review, s-draft

#7432 Add EIP: Non-Fungible Token Roles
  EIPS/eip-7432.md
  assets/eip-7432/ERC7432.sol
  assets/eip-7432/interfaces/IERC7432.sol
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7468 Update EIP-5069: Replace handbook with charter
  EIPS/eip-5069.md
Labels: c-update, t-process

#7412 Add EIP: On-Demand Off-Chain Data Retrieval
  EIPS/eip-7412.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7514 Update EIP-7432: Move to Review
  EIPS/eip-7432.md
Labels: c-status, t-erc, e-review, s-review

#7516 Update EIP-6900: Spec update 3
  EIPS/eip-6900.md
  assets/eip-6900/MSCA_Shared_Components_Diagram.svg
Labels: c-update, t-erc, a-review, s-draft

#7520 Update EIP-6120: Update to payload interface
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#7456 Update EIP-4788: initial stab at v2
  EIPS/eip-4788.md
Labels: c-update, t-core, a-review, s-draft

#7388 Update EIP-1: Add numbering guidelines
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7524 Update EIP-7303: Update eip-7303.md
  EIPS/eip-7303.md
Labels: c-update, t-erc, s-draft

#7495 Add EIP: SSZ PartialContainer
  EIPS/eip-7495.md
  assets/eip-7495/partial_container.py
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7527 Update EIP-7495: Extend tests and add deserialization to impl
  EIPS/eip-7495.md
  assets/eip-7495/partial_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-draft

#7529 Update EIP-7201: Update EIP-7201
  EIPS/eip-7201.md
Labels: c-update, t-erc, e-review, s-draft

#7531 Update EIP-7412: Rename Parts of Interface
  EIPS/eip-7412.md
Labels: c-update, t-erc, s-draft

#7509 Update EIP-6493: Use `PartialContainer`
  EIPS/eip-6493.md
  assets/eip-6493/security/collision.py
  assets/eip-6493/transaction.png
Labels: c-update, t-core, s-draft

#7532 Update EIP-4788: 4788 cleanups
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7536 Update EIP-6493: Define receipt format
  EIPS/eip-6493.md
  assets/eip-6493/receipt.png
Labels: c-update, t-core, s-draft

#7180 Update EIP-5725: Move to Last Call
  EIPS/eip-5725.md
  assets/eip-5725/README.md
  assets/eip-5725/contracts/ERC5725.sol
  assets/eip-5725/contracts/IERC5725.sol
  assets/eip-5725/contracts/mocks/ERC20Mock.sol
  assets/eip-5725/contracts/reference/LinearVestingNFT.sol
  assets/eip-5725/contracts/reference/VestingNFT.sol
  assets/eip-5725/test/LinearVestingNFT.test.ts
  assets/eip-5725/test/VestingNFT.test.ts
  assets/eip-5725/test/helpers/time.ts
Labels: c-status, t-erc, e-review

#7537 Update EIP-6493: Add RLP to SSZ conversion implementation
  EIPS/eip-6493.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/rlp_types.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/tx_hashes.py
Labels: c-update, t-core, w-ci, s-draft

#7538 Update EIP-6120: add Native Token Transfer section
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#7540 Update EIP-6493: Define `PooledTransaction` wrapper for gossip
  EIPS/eip-6493.md
Labels: c-update, t-core, w-ci, s-draft

#7544 Update EIP-6404: Switch to EIP-6493 `SignedTransaction` / `Receipt`
  EIPS/eip-6404.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
  assets/eip-6404/tests/create_transactions.py
  assets/eip-6404/tests/eip2718_tx_types.py
  assets/eip-6404/tests/normalized/convert_transactions.py
  assets/eip-6404/tests/normalized/create_proofs.py
  assets/eip-6404/tests/normalized/ssz_proof_types.py
  assets/eip-6404/tests/normalized/ssz_tx_types.py
  assets/eip-6404/tests/normalized/verify_proofs.c
  assets/eip-6404/tests/normalized/verify_proofs.py
  assets/eip-6404/tests/proof_helpers.py
  assets/eip-6404/tests/sign_transaction.py
  assets/eip-6404/tests/union/convert_transactions.py
  assets/eip-6404/tests/union/create_proofs.py
  assets/eip-6404/tests/union/ssz_proof_types.py
  assets/eip-6404/tests/union/ssz_tx_types.py
  assets/eip-6404/tests/union/verify_proofs.c
  assets/eip-6404/tests/union/verify_proofs.py
  assets/eip-6466/helpers/convert_receipts.py
  assets/eip-6466/helpers/eip2718_receipt_types.py
  assets/eip-6466/helpers/recover_receipts.py
  assets/eip-6466/helpers/ssz_receipt_types.py
Labels: c-update, t-core, s-draft

#7546 Update EIP-6465: Define typed withdrawal envelope for networking
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6493.md
  assets/eip-6465/helpers/convert_withdrawals.py
  assets/eip-6465/helpers/eip4895_withdrawal_types.py
  assets/eip-6465/helpers/recover_withdrawals.py
  assets/eip-6465/helpers/ssz_withdrawal_types.py
Labels: c-update, t-core, s-draft

#7512 CI: New `eipw` version
  .github/workflows/ci.yml
Labels: e-consensus

#7548 Update EIP-7495: Move to Review
  EIPS/eip-7495.md
Labels: c-status, t-core, e-review, s-review
