Repository ethereum/EIPs, pull requests merged in 2023-11, with the labels that each got.

#7884 Update EIP-1: Allow links to the yellow paper
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7788 Update EIP-6780: say "target" instead of "caller"
  EIPS/eip-6780.md
Labels: c-update, t-core, a-review, s-draft

#7944 Add EIP: Move committee index outside Attestation
  EIPS/eip-7549.md
Labels: c-new, t-core, e-review, s-review, e-consensus

#7952 Update EIP-1153: fix typo
  EIPS/eip-1153.md
Labels: c-update, t-core, a-review

#7959 Update EIP-7480: fix typo
  EIPS/eip-7480.md
Labels: c-update, t-core, a-review, s-draft

#7926 Add EIP: Verkle proof verification precompile
  EIPS/eip-7545.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7929 Update EIP-6916: Move to Review
  EIPS/eip-6916.md
Labels: c-status, t-core, e-review, s-review

#7963 Update EIP-7549: fix typo
  EIPS/eip-7549.md
Labels: c-update, t-core, a-review, s-review

#7225 Update EIP-7199: Move to Withdrawn
  EIPS/eip-7199.md
Labels: c-status, t-meta, w-stale, a-review, s-withdrawn

#7741 Config: Add g11tech to governance group
  config/eip-editors.yml
Labels: e-consensus

#7745 Config: Add xinbenlv (myself) to governance group
  config/eip-editors.yml
Labels: e-consensus

#7938 Update EIP-7495: Add `Variant[S]` / `OneOf[S]` type safety layer
  EIPS/eip-7495.md
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review, e-consensus

#7939 Update EIP-6493: Use `Variant[S]` for type safety
  EIPS/eip-6493.md
  assets/eip-6493/convert.py
  assets/eip-6493/rlp_types.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/tx_hashes.py
Labels: c-update, t-core, s-draft, e-consensus

#7992 Update EIP-4788: Move to Review
  EIPS/eip-4788.md
Labels: c-status, t-core, e-review, s-review

#7991 Update EIP-3074: Move to Review
  EIPS/eip-3074.md
Labels: c-status, t-core, w-ci, s-review

#7985 Update EIP-7516: Move to Review
  EIPS/eip-7516.md
Labels: c-status, t-core, e-review, s-review

#7936 Update EIP-7495: Allow setting properties in `StableContainer` impl
  assets/eip-7495/stable_container.py
Labels: e-consensus

#7998 Update EIP-7549: Move to Draft
  EIPS/eip-7549.md
Labels: c-status, t-core, s-draft
