Repository ethereum/EIPs, pull requests merged in 2023-07, with the labels that each got.

#7061 Update EIP-6066: Move to Last Call
  EIPS/eip-6066.md
Labels: c-status, t-erc, e-review

#7250 Update EIP-4337: Some ERC-4337 changes
  EIPS/eip-4337.md
Labels: c-update, t-erc, a-review, s-draft

#7267 Update EIP-4337: Fix accidentally missed commit in ERC-4337 changes
  EIPS/eip-4337.md
Labels: c-update, t-erc, s-draft

#7270 Update EIP-3607: Fix typo in eip-3607.md
  EIPS/eip-3607.md
Labels: c-update, t-core, w-ci, s-final, e-consensus

#7240 Update EIP-6381: Move to Final
  EIPS/eip-6381.md
Labels: c-status, t-erc, e-review, s-final

#7164 Update EIP-3643: Move to Draft
  EIPS/eip-3643.md
  assets/eip-3643/ONCHAINID/IClaimIssuer.sol
  assets/eip-3643/ONCHAINID/IERC734.sol
  assets/eip-3643/ONCHAINID/IERC735.sol
  assets/eip-3643/ONCHAINID/IIdentity.sol
  assets/eip-3643/interfaces/IClaimTopicsRegistry.sol
  assets/eip-3643/interfaces/ICompliance.sol
  assets/eip-3643/interfaces/IERC3643.sol
  assets/eip-3643/interfaces/IIdentityRegistry.sol
  assets/eip-3643/interfaces/IIdentityRegistryStorage.sol
  assets/eip-3643/interfaces/ITrustedIssuersRegistry.sol
Labels: c-status, t-erc, e-review, s-draft

#7234 Update EIP-6093: Replace ERC1155 approval error
  EIPS/eip-6093.md
Labels: c-update, t-erc

#7247 Update EIP-6900: Spec update 2
  EIPS/eip-6900.md
  assets/eip-6900/MSCA_Two_Call_Paths_Diagram.svg
Labels: c-update, t-erc, a-review, s-draft

#7093 Add EIP: Social Recovery Interface
  EIPS/eip-7093.md
  assets/eip-7093/social-recovery-flow.svg
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7178 Update EIP-4788: Bound precompile storage
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft, e-consensus

#7282 Update EIP-5173: Update EIP-5173
  EIPS/eip-5173.md
Labels: c-update, t-erc, s-draft

#7283 Update EIP-7015: Add discussed updates
  EIPS/eip-7015.md
Labels: c-update, t-erc, w-ci, s-draft

#7287 Update EIP-7201: Make Solidity example compile
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7288 Update EIP-7201: Simplify Solidity reference implementation
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7296 Update EIP-4844: Clarify header fields
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#7297 Update EIP-4788: explicitly specify header schema for 4788
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7299 Update EIP-7201: Add note about Solidity compiler version
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7284 Update EIP-6492: Handle non-ready deployed wallet
  EIPS/eip-6492.md
Labels: c-update, t-erc, s-review

#7307 Update EIP-4361: Various Updates to EIP-4361 - Sign-In with Ethereum
  EIPS/eip-4361.md
Labels: c-update, t-erc, s-review

#7219 Update EIP-725: Remove overloading from ERC725
  EIPS/eip-725.md
  assets/eip-725/ERC725.sol
Labels: c-update, t-erc, a-review, s-draft

#7271 Update EIP-3643: Move to Review
  EIPS/eip-3643.md
Labels: c-status, t-erc, e-review, s-review

#7309 Update EIP-6066: Move to Final
  EIPS/eip-6066.md
Labels: c-status, t-erc, e-review, s-final

#7298 Update EIP-5202: Move to Final
  EIPS/eip-5202.md
Labels: c-status, t-erc, e-review, s-final

#7275 Update EIP-6239: Move to Final
  EIPS/eip-6239.md
Labels: c-status, t-erc, e-review, s-final

#7277 Update EIP-7212: Move to Review
  EIPS/eip-7212.md
Labels: c-status, t-core, e-review, s-review

#7160 Add EIP: ERC-721 Multi-Metadata Extension
  EIPS/eip-7160.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7320 Update EIP-5585: Add a new interface 'transferUserRights()'
  EIPS/eip-5585.md
Labels: c-update, t-erc, a-review, s-review

#7323 Update EIP-5564: update contract name and scheme id
  EIPS/eip-5564.md
Labels: c-update, t-erc, s-draft

#6843 Update EIP-4910: Move to Final
  EIPS/eip-4910.md
Labels: c-status, t-erc, w-ci, e-review, s-final

#7326 Update EIP-7044: Move to Review
  EIPS/eip-7044.md
Labels: c-status, t-core, e-review, s-review

#7327 Update EIP-6206: Clarify JUMPF specification
  EIPS/eip-6206.md
Labels: c-update, t-core, s-draft

#7313 Update EIP-4750: Update opcodes for CALLF and RETF
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#7314 Update EIP-6206: Update opcode for JUMPF
  EIPS/eip-6206.md
Labels: c-update, t-core, s-draft

#7329 Add EIP: ERC/EIP Repository split
  EIPS/eip-7329.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#7338 Update EIP-7329: update discussion-to, tweak words.
  EIPS/eip-7329.md
Labels: c-update, t-meta, w-ci, s-draft

#7349 Update EIP-7329: Move to Last Call
  EIPS/eip-7329.md
Labels: c-status, t-meta, e-review

#7256 Update EIP-6963: Update rDNS and icon properties and improve security considerations
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-draft

#7360 Update EIP-6475: Move to Draft
  EIPS/eip-6475.md
  EIPS/eip-6493.md
Labels: c-status, t-core, s-draft

#7364 Update EIP-223: description
  EIPS/eip-223.md
Labels: c-update, t-erc, s-draft

#7352 Update EIP-6963: Move to Review
  EIPS/eip-6963.md
Labels: c-status, t-interface, e-review, s-review

#7266 Add EIP: Remove BLAKE2 compression precompile
  EIPS/eip-7266.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7365 Update EIP-7045: Move to Review
  EIPS/eip-7045.md
Labels: c-status, t-core, e-review, s-review

#7374 Update EIP-1613: You guessed it, more absolute paths that need fixing
  EIPS/eip-1613.md
Labels: c-update, t-erc, s-stagnant

#7376 Update EIP-6968: Update eip-6968.md
  EIPS/eip-6968.md
Labels: c-update, t-core, w-ci, s-draft

#7387 Update EIP-5806: refactor motivations
  EIPS/eip-5806.md
Labels: c-update, t-core, w-ci, s-draft

#7358 Update EIP-4520: The typo double-whammy!
  EIPS/eip-4520.md
Labels: c-update, t-core, w-ci, a-review, s-stagnant

#7371 Update EIP-777: Small fix - add end tag
  EIPS/eip-777.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7372 Update EIP-1175: Fix absolute pathing
  EIPS/eip-1175.md
Labels: c-update, t-erc, w-ci, a-review, s-stagnant

#7375 Update EIP-2025: More. Absolute. Paths.
  EIPS/eip-2025.md
Labels: c-update, t-core, w-ci, s-withdrawn, e-consensus

#7370 Update EIP-210: Make it not crash my build system
  EIPS/eip-210.md
Labels: c-update, t-core, a-review, s-stagnant

#7354 Update EIP-4844: Rename "data gas" to "blob gas"
  EIPS/eip-4844.md
Labels: c-update, t-core, s-review

#7359 Update EIP-7329: Remove unnecesary link and elaborate
  EIPS/eip-7329.md
Labels: c-update, t-meta, a-review

#7295 Update EIP-5169: Fix uncompilable memory in event
  EIPS/eip-5169.md
Labels: c-update, t-erc, s-final, e-consensus

#7183 Update EIP-2612: Make consistent indents in json
  EIPS/eip-2612.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7391 Update EIP-7093: Change definition of policy and add RecoveryModule
  EIPS/eip-7093.md
  assets/eip-7093/social-recovery-flow.svg
Labels: c-update, t-erc, s-draft

#7392 Update EIP-6551: Minor typo fix
  EIPS/eip-6551.md
Labels: c-update, t-erc, a-review, s-draft

#7092 Add EIP: Financial Bonds
  EIPS/eip-7092.md
  assets/eip-7092/BondStorage.sol
  assets/eip-7092/ERC7092.sol
  assets/eip-7092/IERC7092.sol
  assets/eip-7092/coupons/CouponMath.sol
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7399 Update EIP-3156: github handle
  EIPS/eip-3156.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7377 Add EIP: Migration Transaction
  EIPS/eip-7377.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7039 Add EIP: Scheme-Handler Discovery Option for Wallets
  EIPS/eip-7039.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#7363 Add modified WS script to eip-6110 assets
  assets/eip-6110/eth2_ws_calc.py
  assets/eip-6110/ws_period_analysis.md
Labels: w-ci

#7415 Update EIP-7377: fix typo
  EIPS/eip-7377.md
Labels: c-update, t-core, s-draft

#7285 Update EIP-7015: eip 7015
  EIPS/eip-7015.md
Labels: c-update, t-erc, w-ci, s-draft

#7419 Update EIP-7377: Fix some nits
  EIPS/eip-7377.md
Labels: c-update, t-core, a-review, s-draft

#6682 Add EIP: NFT Flashloans
  EIPS/eip-6682.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7424 Update EIP-7377: EIP-7377 updates
  EIPS/eip-7377.md
Labels: c-update, t-core, s-draft

#7353 Update EIP-7066: Move to Review
  EIPS/eip-7066.md
Labels: c-status, t-erc, e-review, s-review, e-consensus

#7428 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc, s-draft

#7429 Update EIP-4844: Align names and fix `KZGCommitment` description
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review
