Repository ethereum/EIPs, pull requests merged in 2023-09, with the labels that each got.

#7551 CI: Fix stagnant bot
  .github/renovate.json
  .github/workflows/auto-stagnate-bot.yml
Labels: e-consensus

#7553 Update EIP-7495: Rename to `PartialContainer` to `StableContainer`
  EIPS/eip-6493.md
  EIPS/eip-7495.md
  assets/eip-6493/convert.py
  assets/eip-6493/ssz_types.py
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-draft, s-review

#7624 Update EIP-5568: Use interface
  EIPS/eip-5568.md
Labels: c-update, t-erc, s-review

#7623 Update EIP-5289: Add disclaimer
  EIPS/eip-5289.md
Labels: c-update, t-erc, s-review

#7625 Update EIP-6188: Fix typo
  EIPS/eip-6188.md
Labels: c-update, t-core, s-review

#7626 Update EIP-6189: Add transaction validity section
  EIPS/eip-6189.md
Labels: c-update, t-core, s-review

#7627 Update EIP-5791: Update eip-5791.md (adding contributor)
  EIPS/eip-5791.md
Labels: c-update, t-erc, w-ci, s-draft

#7629 Update EIP-7495: Remove the need for a wrapper type
  EIPS/eip-6493.md
  EIPS/eip-7495.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/ssz_types.py
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-draft, s-review

#7631 Update EIP-6900: Fix parameter types
  EIPS/eip-6900.md
Labels: c-update, t-erc, a-review, s-draft

#7633 Update EIP-5115: Update to conform to new EIP validator rules
  EIPS/eip-5115.md
Labels: c-update, t-erc, s-draft

#7636 Update EIP-3670: Improve wording
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#7522 Add EIP: Zero-Knowledge Wormholes
  EIPS/eip-7503.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7643 Update EIP-7401: Restructure Superseed message
  EIPS/eip-7401.md
Labels: c-update, t-erc, s-review

#7644 Update EIP-7409: Minor cosmetic fix
  EIPS/eip-7409.md
Labels: c-update, t-erc, s-draft

#7640 Update EIP-6492: Move to Final
  EIPS/eip-6492.md
Labels: c-status, t-erc, e-review, s-final

#7189 Update EIP-1: remove legacy note about the interfaces repo
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7645 Update EIP-7401: Move to Last Call
  EIPS/eip-7401.md
Labels: c-status, t-erc, e-review

#7517 Update EIP-7329: Move to Last Call
  EIPS/eip-7329.md
Labels: c-status, t-meta, e-review

#7427 Add EIP: Tokenized Reserve
  EIPS/eip-7425.md
Labels: c-new, t-erc, w-ci, e-review, s-draft, e-consensus

#7635 Add EIP: Dynamic On-Chain Token Attributes Repository
  EIPS/eip-7508.md
  assets/eip-7508/contracts/AttributesRepository.sol
  assets/eip-7508/contracts/IERC7508.sol
  assets/eip-7508/contracts/mocks/OwnableMintableERC721Mock.sol
  assets/eip-7508/hardhat.config.ts
  assets/eip-7508/package.json
  assets/eip-7508/test/attributesRepository.ts
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7534 Update EIP-7160: Move to Review
  EIPS/eip-7160.md
Labels: c-status, t-erc, e-review, s-review

#7649 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc

#7648 Update EIP-5725: Move to Final
  EIPS/eip-5725.md
Labels: c-status, t-erc, e-review, s-final

#7653 Update EIP-4883: Update eip-4883.md to use onchain
  EIPS/eip-4883.md
Labels: c-update, t-erc, s-draft

#7642 Update EIP-3026: Update addresses table
  EIPS/eip-3026.md
Labels: c-update, t-core, s-draft

#7657 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc

#7658 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc

#7659 Update EIP-223: Update eip-223.md
  EIPS/eip-223.md
Labels: c-update, t-erc

#7661 Update EIP-5069: Update eip-5069.md
  EIPS/eip-5069.md
Labels: c-update, t-process

#7660 Update EIP-223: Move to Final
  EIPS/eip-223.md
Labels: c-status, t-erc, e-review, s-final

#7662 Update EIP-6900: Correct phrasing
  EIPS/eip-6900.md
Labels: c-update, t-erc, a-review, s-draft

#7663 Update EIP-7412: Remove `oracleQuery` from `fulfillOracleQuery` function signature
  EIPS/eip-7412.md
Labels: c-update, t-erc, s-draft

#7664 Website: Support a dark mode (closes ethereum#7549)
  _includes/head.html
  assets/css/override.css
Labels: e-consensus

#7666 Update EIP-6551: Update eip-6551.md to fix typo
  EIPS/eip-6551.md
Labels: c-update, t-erc, a-review, s-review

#7542 Update EIP-1: Allow links to CVEs
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#7669 Update EIP-7508: Refine description
  EIPS/eip-7508.md
Labels: c-update, t-erc, s-draft

#7670 Update EIP-7053: Move to Last Call
  EIPS/eip-7053.md
Labels: c-status, t-erc, e-review

#7639 Add EIP: Minimal Proxy Contract with PUSH0
  EIPS/eip-7511.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7674 Update EIP-7432: Add Approval Interface
  EIPS/eip-7432.md
  assets/eip-7432/ERC7432.sol
  assets/eip-7432/interfaces/IERC7432.sol
Labels: c-update, t-erc, s-review

#7675 Update EIP-7512: Fix Author
  EIPS/eip-7512.md
Labels: c-update, t-erc, s-draft

#7671 Update EIP-7015: Eip 7015
  EIPS/eip-7015.md
Labels: c-update, t-erc, s-draft, e-consensus

#7308 Update EIP-6780: Add clarifications to EIP-6780
  EIPS/eip-6780.md
Labels: c-update, t-core, a-review, s-draft

#7681 Update EIP-6900: add missing members to IPlugin structs, correct install step statement
  EIPS/eip-6900.md
Labels: c-update, t-erc, s-draft

#7680 Update EIP-2535: Fixed typo
  EIPS/eip-2535.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7686 Update EIP-6809: Move to Last Call
  EIPS/eip-6809.md
Labels: c-status, t-erc, e-review

#7687 Update EIP-7231: Move to Review
  EIPS/eip-7231.md
Labels: c-status, t-erc, e-review, s-review

#7689 Update EIP-7432: Move to Last Call
  EIPS/eip-7432.md
Labels: c-status, t-erc, e-review

#7679 Update EIP-5585: Move to Last Call
  EIPS/eip-5585.md
Labels: c-status, t-erc, a-review

#7690 Update EIP-5453: Move to Review
  EIPS/eip-5453.md
Labels: c-status, t-erc, s-review

#7692 Update EIP-5247: Move to Review
  EIPS/eip-5247.md
Labels: c-status, t-erc, s-review

#7694 Update EIP-5269: Move to Review
  EIPS/eip-5269.md
Labels: c-status, t-erc, s-review

#7695 Update EIP-5982: Move to Review
  EIPS/eip-5982.md
Labels: c-status, t-erc, s-review

#7668 Add EIP: Add Max Epoch Churn Limit
  EIPS/eip-7514.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7697 Update EIP-5450: Move to Review
  EIPS/eip-5450.md
Labels: c-status, t-core, e-review, s-review

#7693 Update EIP-5453: Move to Last Call
  EIPS/eip-5453.md
Labels: c-status, t-erc, e-review

#6527 Update EIP-721: Spell collectible consistently
  EIPS/eip-721.md
Labels: c-update, t-erc, w-ci, s-final, e-consensus

#7701 Update EIP-7516: BLOBBASEFEE opcode
  EIPS/eip-7516.md
Labels: c-update, t-core, e-review, s-draft, e-consensus

#6604 Add EIP: Abstract Token
  EIPS/eip-6604.md
  assets/eip-6604/README.md
  assets/eip-6604/contracts/AbstractERC20.sol
  assets/eip-6604/contracts/AbstractToken.sol
  assets/eip-6604/contracts/GenericEIP712.sol
  assets/eip-6604/contracts/IAbstractToken.sol
Labels: c-new, t-erc, w-stale, e-review, s-draft, e-consensus

#6664 Update EIP-4337: Update eip-4337.md
  EIPS/eip-4337.md
Labels: c-update, t-erc, w-ci, a-review, s-draft

#6690 Add EIP: EVM Modular Arithmetic Extensions (EVMMAX)
  EIPS/eip-6690.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#6734 Add EIP: L2 Token List
  EIPS/eip-6734.md
Labels: c-new, t-erc, w-ci, e-review, s-draft, e-consensus

#6773 Config: Disable maximum concurrent dependency PRs
  .github/renovate.json
Labels: e-consensus

#6775 Update EIP-6617: Move to Review
  EIPS/eip-6617.md
  assets/eip-6617/contracts/EIP6617.sol
  assets/eip-6617/contracts/interfaces/IEIP6617.sol
  assets/eip-6617/contracts/interfaces/IEIP6617Meta.sol
Labels: c-status, t-erc, e-review, s-review

#6797 Update EIP-6170: Update eip-6170.md
  EIPS/eip-6170.md
Labels: c-update, t-erc, a-review, s-draft

#6687 Update EIP-4337: Update eip-4337.md
  EIPS/eip-4337.md
Labels: c-update, t-erc, w-stale, a-review, s-draft

#7715 Update EIP-7514: Update eip-7514.md
  EIPS/eip-7514.md
Labels: c-update, t-core, s-draft

#7714 Update EIP-7516: update `BLOBBASEFEE` opcode value so it does not clash with `BLOBHASH`'s opcode value
  EIPS/eip-7516.md
Labels: c-update, t-core, a-review, s-draft

#7716 Update EIP-7516: removes remaning references to 0x49
  EIPS/eip-7516.md
Labels: c-update, t-core, s-draft

#7717 Update EIP-7514: Update eip-7514 constant name
  EIPS/eip-7514.md
Labels: c-update, t-core, s-draft

#7713 Update EIP-6982: Minor Improvements EIP6982
  EIPS/eip-6982.md
Labels: c-update, t-erc, s-review

#6491 Update EIP-3091: Move to Draft
  EIPS/eip-3091.md
Labels: c-status, t-interface, a-review, s-draft

#7729 Update EIP-6963: Update eip-6963.md to fix typos
  EIPS/eip-6963.md
Labels: c-update, t-interface, a-review, s-review

#6457 Update EIP-3085: Move to Review
  EIPS/eip-3085.md
Labels: c-status, t-interface, w-ci, a-review, s-review

#6864 Add EIP: Upgradable Fungible Token
  EIPS/eip-6864.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#6873 Add EIP: Preimage retention
  EIPS/eip-6873.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#6916 Add EIP: Automatically Reset Tesnet
  EIPS/eip-6916.md
Labels: c-new, t-core, w-ci, e-review, s-draft, e-consensus

#7734 Update EIP-7508: Add repository address
  EIPS/eip-7508.md
  assets/eip-7508/contracts/AttributesRepository.sol
Labels: c-update, t-erc, s-draft

#7725 Add EIP: Atomic Storage Operations SCREDIT and SDEBIT
  EIPS/eip-7519.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7738 Update EIP-2645: Update eip-2645.md (TYPO Fix)
  EIPS/eip-2645.md
Labels: c-update, t-erc, w-ci, e-review, s-stagnant

#7735 Update EIP-7401: Move to Final
  EIPS/eip-7401.md
Labels: c-status, t-erc, e-review, s-final

#7731 Update EIP-4881: Move to Final
  EIPS/eip-4881.md
Labels: c-status, t-interface, e-review, s-final

#7718 Update EIP-7329: Move to Final
  EIPS/eip-7329.md
Labels: c-status, t-meta, e-review, s-final

#7072 Update EIP-5920: expand the motivation a bit
  EIPS/eip-5920.md
Labels: c-update, t-core, a-review, s-review

#7740 Update EIP-7514: Move to Review
  EIPS/eip-7514.md
Labels: c-status, t-core, e-review, s-review

#6965 Update EIP-1191: Fix Implementation Table
  EIPS/eip-1191.md
Labels: c-update, t-erc, w-ci, a-review

#7746 Update EIP-7432: Move to Review
  EIPS/eip-7432.md
  assets/eip-7432/ERC7432.sol
  assets/eip-7432/interfaces/IERC7432.sol
Labels: c-status, t-erc, s-review

#7634 Add EIP: Multi-User NFT Extension
  EIPS/eip-7507.md
  assets/eip-7507/contracts/ERC7507.sol
  assets/eip-7507/contracts/IERC7507.sol
  assets/eip-7507/hardhat.config.ts
  assets/eip-7507/package.json
  assets/eip-7507/test/ERC7507.test.ts
  assets/eip-7507/tsconfig.json
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7744 Add EIP: Empty accounts deprecation
  EIPS/eip-7523.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7749 Update EIP-7378: Fix typos
  EIPS/eip-7378.md
Labels: c-update, t-core, s-draft

#7757 Update EIP-7519: Fix typos
  EIPS/eip-7519.md
Labels: c-update, t-core, a-review, s-draft

#7085 Add EIP: NFT Relationship Enhancement
  EIPS/eip-7085.md
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7756 Update EIP-7514: Fix typos
  EIPS/eip-7514.md
Labels: c-update, t-core, a-review, s-review

#7755 Update EIP-7512: Fix typos
  EIPS/eip-7512.md
Labels: c-update, t-erc, a-review, s-draft

#7754 Update EIP-7508: Fix typos
  EIPS/eip-7508.md
Labels: c-update, t-erc, a-review, s-draft

#7753 Update EIP-7503: Fix typo
  EIPS/eip-7503.md
Labels: c-update, t-core, a-review, s-draft

#7752 Update EIP-7444: Fix typo
  EIPS/eip-7444.md
Labels: c-update, t-erc, a-review, s-draft

#7751 Update EIP-7425: Fix typos
  EIPS/eip-7425.md
Labels: c-update, t-erc, w-ci, a-review, s-draft

#7750 Update EIP-7409: Fix typos
  EIPS/eip-7409.md
Labels: c-update, t-erc, a-review

#7748 Update EIP-7401: Fix typos
  EIPS/eip-7401.md
Labels: c-update, t-erc, s-final, e-consensus

#7758 Update EIP-6120: update
  EIPS/eip-6120.md
Labels: c-update, t-erc, s-review

#7315 Update EIP-663: Update opcodes for SWAPN and DUPN
  EIPS/eip-663.md
Labels: c-update, t-core, a-review, s-review

#7241 Update EIP-663: Replace runtime stack checks with EOF validation rules
  EIPS/eip-663.md
Labels: c-update, t-core, a-review, s-review

#7220 Update EIP-7069: Add charge for value-bearing calls
  EIPS/eip-7069.md
Labels: c-update, t-core, s-draft

#7330 Update EIP-6206: Add non-returning functions specification
  EIPS/eip-6206.md
Labels: c-update, t-core, s-draft

#7480 Add EIP: EOF - Data section access instructions
  EIPS/eip-7480.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7760 Update EIP-7201: Explain possibility to use different formulas
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-draft

#7763 Update EIP-7201: Move to Review
  EIPS/eip-7201.md
Labels: c-status, t-erc, e-review, s-review

#7743 Add EIP: OIDC ZK Verifier for AA Account
  EIPS/eip-7522.md
  assets/eip-7522/workflow.png
Labels: c-new, t-erc, e-review, s-draft, e-consensus

#7774 Update EIP-6909: Update Transfer Event To Log Caller
  EIPS/eip-6909.md
Labels: c-update, t-erc, s-draft

#7777 Update EIP-7512: Fix authors
  EIPS/eip-7512.md
Labels: c-update, t-erc, s-draft

#7464 Update EIP-6963: Add RDNS section for motivation and requirements
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-review

#6800 Add EIP: Ethereum state using a unified verkle tree
  EIPS/eip-6800.md
  assets/eip-6800/tree_structure.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7672 Update EIP-4788: post audit tweaks
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7786 Update EIP-4788: update ring buffer size rationale for new ring buffer size
  EIPS/eip-4788.md
Labels: c-update, t-core, s-draft

#7394 Update EIP-6963: updates for object.freeze and other recommendations
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-review

#7780 Update EIP-6963: Move to Last Call
  EIPS/eip-6963.md
Labels: c-status, t-interface, e-review

#7793 Update EIP-6780: remove mention of verkle tree behavior
  EIPS/eip-6780.md
Labels: c-update, t-core, s-draft

#7794 Update EIP-7201: Updates to wording
  EIPS/eip-7201.md
Labels: c-update, t-erc, s-review

#7796 Update EIP-6900: Spec Update 4
  EIPS/eip-6900.md
  assets/eip-6900/MSCA_Two_Call_Paths_Diagram.svg
  assets/eip-6900/Modular_Account_Call_Flow.svg
  assets/eip-6900/Plugin_Execution_Flow.svg
Labels: c-update, t-erc, a-review, s-draft
