Repository ethereum/EIPs, pull requests merged in 2024-02, with the labels that each got.

#8074 Add EIP: Reserve Precompile Address Range for RIPs
  EIPS/eip-7587.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#7765 Update EIP-7516: Use "instruction" term
  EIPS/eip-7516.md
Labels: c-update, t-core, w-stale, a-review, s-draft

#8165 Update EIP-4788: Use "blob" term consistent with EIP-4844
  EIPS/eip-4788.md
Labels: c-update, t-core, a-review

#8168 Update EIP-5806: Update EIP-5806
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8164 Update EIP-7587: Move to Review
  EIPS/eip-7587.md
Labels: c-status, t-informational, e-review, s-review

#8154 Update EIP-7480: match to EOF Megaspec
  EIPS/eip-7480.md
Labels: c-update, t-core, a-review, s-draft

#8173 Update EIP-7569: Add Dencun mainnet epoch & time
  EIPS/eip-7569.md
Labels: c-update, t-meta, s-review

#8153 Update EIP-5656: Move to Last Call
  EIPS/eip-5656.md
Labels: c-status, t-core, a-review, e-consensus

#8172 Update EIP-7568: Move to Last Call
  EIPS/eip-7568.md
Labels: c-status, t-meta, e-review

#8131 Update EIP-7569: Move to Last Call
  EIPS/eip-7569.md
Labels: c-status, t-meta, w-ci, e-review

#8170 Update EIP-6122: Fix typo in EIP-6122
  EIPS/eip-6122.md
Labels: c-update, t-networking, s-final, e-consensus

#8171 Config: match `tree` along with `blob` for Github repos.
  config/eipw.toml
Labels: e-consensus

#8095 Update EIP-4844: Rename gasPrice to baseFee
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#8185 Update EIP-7587: Moves 7587 from info to meta type
  EIPS/eip-7587.md
Labels: c-update, t-meta, s-review

#8202 Update EIP-7039: Update eip-7039.md
  EIPS/eip-7039.md
Labels: c-update, t-interface, s-draft

#8028 Update EIP-2070: Move to Withdrawn
  EIPS/eip-2070.md
Labels: c-status, t-meta, a-review, s-withdrawn

#8210 Update EIP-7568: Mention 2070 in 7568
  EIPS/eip-7568.md
Labels: c-update, t-meta

#8218 Add EIP: Increase calldata cost
  EIPS/eip-7623.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8159 Add EIP: Hardfork Meta - Osaka
  EIPS/eip-7607.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8158 Add EIP: Decrease base cost of TLOAD/TSTORE
  EIPS/eip-7609.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8226 Update EIP-7600: Mark 2537 as Included
  EIPS/eip-7600.md
Labels: c-update, t-meta, e-review, s-draft

#8231 Update EIP-5806: Restrict SSTORE and CREATE
  EIPS/eip-5806.md
Labels: c-update, t-core, w-ci, s-draft

#8216 Update EIP-6206: Move to Review
  EIPS/eip-6206.md
Labels: c-status, t-core, e-review, s-review

#8233 Update EIP-5656: fix test in eip-5656
  EIPS/eip-5656.md
Labels: c-update, t-core

#8234 Update EIP-5806: Add restriction to create2 and selfdestruct/deactivate
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8235 Update EIP-5806: remove mention of DEACTIVATE
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8237 Update EIP-7623: Change Naming of Constants
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8238 Update EIP-7623: remove strange whitespces
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8239 Update EIP-7623: remove formating error
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8240 Update EIP-5806: Modify create2 to remove restriction
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8217 Update EIP-3540: Move to Review
  EIPS/eip-3540.md
Labels: c-status, t-core, e-review, s-review

#8215 Update EIP-7480: Move to Review
  EIPS/eip-7480.md
Labels: c-status, t-core, w-ci, e-review, s-review

#8227 Website: Small fix for mobile navigation
  assets/css/override.css
Labels: e-consensus

#8224 Update EIP-7523: Move to Review
  EIPS/eip-7523.md
Labels: c-status, t-core, e-review, s-review

#8209 Add EIP: EOF Contract Creation
  EIPS/eip-7620.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#7941 Update EIP-4844: Fix typo in EIP-4844
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review

#8249 Update EIP-5806: Disable create2 following pushback
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8244 Update EIP-5920: change gas costs
  EIPS/eip-5920.md
Labels: c-update, t-core, w-ci, a-review, s-review

#8252 Update EIP-2537: Move to Review
  EIPS/eip-2537.md
Labels: c-status, t-core, a-review, s-review

#8264 Update EIP-7623: EIP-7623 - Incorporate Init Code
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8265 Update EIP-7623: EIP-7623 - Move CREATE inside max
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8262 Update EIP-2537: Editorial updates eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8270 Update EIP-2537: Update eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core, s-review

#8272 Update EIP-7609: reduce SLOPE coefficient in eip-7609
  EIPS/eip-7609.md
Labels: c-update, t-core, s-draft

#8248 Config: Allow yellow paper
  config/eipw.toml
Labels: e-consensus
