Repository ethereum/EIPs, pull requests merged in 2024-07, with the labels that each got.

#8694 Update EIP-4750: ensure visibility of non-returning functions
  EIPS/eip-4750.md
Labels: c-update, t-core, a-review, s-review

#8693 Update EIP-7620: Remove initcode/runtime container definitions
  EIPS/eip-7620.md
  EIPS/eip-7698.md
Labels: c-update, t-core, s-review

#8714 Update EIP-7620: Disallow referencing by both RETURNCONTRACT and EOFCREATE
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#8711 Add EIP: Enshrined Proposer-Builder Separation
  EIPS/eip-7732.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8721 Update EIP-663: Fix markdown rendering
  EIPS/eip-663.md
Labels: c-update, t-core, a-review, s-review

#8719 Update EIP-3540: Ensure num_container_sections is correct
  EIPS/eip-3540.md
Labels: c-update, t-core, a-review, s-review

#8662 Add EIP: Network Upgrade Inclusion Stages
  EIPS/eip-7723.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8563 Add EIP: Incentivize Access List Provisioning
  EIPS/eip-7707.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8725 Update EIP-663: Fix markdown rendering 2
  EIPS/eip-663.md
Labels: a-review

#8677 Update EIP-7702: add delegation designation
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8729 Update EIP-7636: Move to Final
  EIPS/eip-7636.md
Labels: e-review

#8614 Update EIP-7688: Move to Review
  EIPS/eip-7688.md
Labels: c-status, t-core, w-ci, e-review, s-review

#8684 Add EIP: EVM Transaction Bundles
  EIPS/eip-7727.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8733 Update EIP-7251: fix typos
  EIPS/eip-7251.md
Labels: a-review

#8735 Add EIP: Uncouple blob count between CL and EL
  EIPS/eip-7742.md
Labels: e-review, e-consensus

#8698 Update EIP-2935: use 4788 method + future-proofiness warning
  EIPS/eip-2935.md
Labels: c-update, t-core, s-review

#8590 Update EIP-4788: specify the timestamp for 4788
  EIPS/eip-4788.md
Labels: c-update, t-core, s-final, e-consensus

#8724 Add EIP: Leaf-level state expiry in verkle trees
  EIPS/eip-7736.md
Labels: e-review, e-consensus

#8738 Update EIP-7610: Point to correct EIP-161
  EIPS/eip-7610.md
Labels: a-review

#8747 Update EIP-3540: remove duplicate size constraints
  EIPS/eip-3540.md
Labels: a-review

#8750 Update EIP-7610: Move to Review
  EIPS/eip-7610.md
Labels: a-review

#8732 Update EIP-2294: Move to Review
  EIPS/eip-2294.md
Labels: e-review

#8748 Update EIP-7251: fix typos and correct get_excess_consolidation_reque…
  EIPS/eip-7251.md
Labels: a-review

#8755 Update EIP-7702: fix delegation designator prefix in Abstract
  EIPS/eip-7702.md
Labels: a-review

#8742 CI: Update jekyll-label-bot.yml
  .github/workflows/jekyll-label-bot.yml
Labels: e-consensus

#8752 Add EIP: State conversion to Verkle Tree
  EIPS/eip-7748.md
Labels: c-new, t-core, e-review, s-draft, e-consensus
