Repository ethereum/EIPs, pull requests merged in 2024-04, with the labels that each got.

#8366 Add EIP: EVM-ify the identity precompile
  EIPS/eip-7651.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8376 Add EIP: EVM-ify the identity precompile
  EIPS/eip-7666.md
Labels: a-review, e-consensus

#8367 Add EIP: Raise gas costs of hash functions
  EIPS/eip-7667.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8380 Update EIP-7667: Update eip-7667.md
  EIPS/eip-7667.md
Labels: c-update, t-core, s-draft

#8381 Update EIP-7623: Adjust Token from 16 to 12
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8384 Update EIP-5792: Fix typo
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-draft

#8383 Update EIP-7620: Update InitcodeTransaciton validation
  EIPS/eip-7620.md
Labels: c-update, t-core, a-review, s-review

#8391 Update EIP-7002: Fix typo on link to CL specs
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-draft

#8393 Update EIP-2537: Rename multiexponentiation to MSM
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8392 Update EIP-5792: Add showCallsStatus
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-draft

#8387 Update EIP-5792: Editorial updates to EIP-5792
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review, s-draft

#8395 Update EIP-5792: revert 5792 editorial changes
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-draft

#8120 Update EIP-6913: Move to Draft
  EIPS/eip-6913.md
Labels: c-status, t-core, e-review, s-draft

#8290 Update EIP-1193: author username
  EIPS/eip-1193.md
Labels: c-update, t-interface, w-ci, s-final, e-consensus

#8357 Add EIP: Access-Key opcode
  EIPS/eip-7664.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8405 Update EIP-3074: Update eip-3074.md
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8397 Update EIP-7587: Move to Last Call
  EIPS/eip-7587.md
Labels: c-status, t-meta, e-review

#8340 Add EIP: Sync committee slashings
  EIPS/eip-7657.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8331 Update EIP-1015: Fix typo
  EIPS/eip-1015.md
Labels: c-update, t-core, w-ci, e-review, s-stagnant

#8373 Update EIP-1011: remove repetitive words
  EIPS/eip-1011.md
  EIPS/eip-1057.md
  EIPS/eip-161.md
  EIPS/eip-1706.md
  EIPS/eip-1930.md
  EIPS/eip-2539.md
  EIPS/eip-3026.md
  EIPS/eip-4396.md
  EIPS/eip-6690.md
  EIPS/eip-6916.md
Labels: c-update, t-core, w-ci, s-draft, s-review, s-final, s-withdrawn, s-stagnant, e-consensus

#8257 wrong word check
  _config.yml
Labels: e-consensus

#8256 Update EIP-1052: fix typo
  EIPS/eip-1052.md
Labels: c-update, t-core, w-ci, s-final, e-consensus

#8254 Update EIP-2026: Fix typo in eip-2026
  EIPS/eip-2026.md
Labels: c-update, t-core, w-ci, a-review, s-stagnant

#8024 Update EIP-6690: fix typo
  EIPS/eip-6690.md
Labels: c-update, t-core, a-review, s-draft

#8025 Update EIP-7523: fix typo
  EIPS/eip-7523.md
Labels: c-update, t-core, a-review, s-draft

#8412 Update EIP-3074: Update eip-3074.md
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8417 Update EIP-3074: Fix typos and grammar
  EIPS/eip-3074.md
Labels: c-update, t-core, a-review, s-review

#7904 Add EIP: EVM decimal math
  EIPS/eip-7543.md
  assets/eip-7543/BlackScholes.yul
  assets/eip-7543/Neuron.yul
  assets/eip-7543/decimal_float.go
  assets/eip-7543/decimal_float_test.go
  assets/eip-7543/gasEVMPlusEmulate.go
  assets/eip-7543/uint256_wrapped.go
Labels: c-new, t-core, w-stale, e-review, s-draft, e-consensus

#8428 Update EIP-3074: explain `nonce` and `chainId` in rationale
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8430 Update EIP-3074: fail if account has code
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8429 Update EIP-3074: update diagrams, add delegate use case
  EIPS/eip-3074.md
  assets/eip-3074/auth-msg-delegate.png
  assets/eip-3074/auth-msg-multi-call.png
  assets/eip-3074/auth-msg.png
Labels: c-update, t-core, s-review

#8434 Update EIP-3074: Update eip-3074.md
  EIPS/eip-3074.md
Labels: c-update, t-core, a-review, s-review

#8414 Update EIP-2537: Fix conflicting gas formula
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8436 Update EIP-7495: Compact serialization for `Variant[S]`
  EIPS/eip-7495.md
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review

#8437 Update EIP-2537: Rollback and fix formula
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8388 Update EIP-5450: Align with EOF megaspec
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#8152 Update EIP-3540: Move to Review
  EIPS/eip-3540.md
Labels: c-update, t-core, a-review, s-review

#8432 Add EIP: General purpose execution layer requests
  EIPS/eip-7685.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8266 Add EIP: Cease serving history before PoS
  EIPS/eip-7639.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#8341 Add EIP: Light client data backfill
  EIPS/eip-7658.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8408 Add EIP: Return deposits for distinct credentials
  EIPS/eip-7684.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8449 Update EIP-2537: EIP-2537 update test vectors
  EIPS/eip-2537.md
  assets/eip-2537/add_G1_bls.json
  assets/eip-2537/add_G2_bls.json
  assets/eip-2537/map_fp2_to_G2_bls.json
  assets/eip-2537/mul_G1_bls.json
  assets/eip-2537/mul_G2_bls.json
  assets/eip-2537/multiexp_G2_bls.json
  assets/eip-2537/pairing_check_bls.json
  assets/eip-2537/test-vectors.md
Labels: c-update, t-core, s-review

#8396 Update EIP-5792: Fine-tune the "capability" rhetoric of EIP-5792 (plus non-normative wordsmithing as a bonus)
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review, s-draft

#8450 Update EIP-5792: Move to Review
  EIPS/eip-5792.md
Labels: c-status, t-interface, e-review, s-review

#8451 Update EIP-7685: simplify cl behavior
  EIPS/eip-7685.md
Labels: c-update, t-core, s-draft

#8455 Update EIP-2537: Update eip-2537.md - minor change in Field to curve mapping
  EIPS/eip-2537.md
Labels: c-update, t-core, s-review

#8358 Update EIP-7620: Expand the Rationale section & clarifications
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#7954 chore(config): Update _config.yml to reflect repo split
  _config.yml
Labels: w-stale, e-consensus

#8435 Add EIP: Linear EVM memory limits
  EIPS/eip-7686.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8466 Update EIP-7685: General purpose execution layer requests
  EIPS/eip-7685.md
Labels: c-update, t-core, e-review, s-draft, e-consensus

#8471 Update EIP-7623: Add further clarification
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8473 Update EIP-6110: put deposits into request struct, take 2
  EIPS/eip-6110.md
Labels: c-update, t-core, s-draft

#8474 Update EIP-6110: get rid of Deposit struct definition
  EIPS/eip-6110.md
Labels: c-update, t-core, s-draft

#8406 Update EIP-7002: add support for partial withdrawals, rename exits
  EIPS/eip-7002.md
Labels: c-update, t-core, s-draft

#8469 Update EIP-7002: convert to use 7685 requests
  EIPS/eip-7002.md
Labels: c-update, t-core, s-draft

#8166 Update EIP-2935: Move to Draft
  EIPS/eip-2935.md
Labels: c-status, t-core, a-review, s-draft

#8476 Update EIP-7002: Fix after renaming fields (exit->count)
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-draft

#8477 Update EIP-7002: inhibit early use of queue
  EIPS/eip-7002.md
Labels: c-update, t-core, s-draft

#8480 Update EIP-5000: Fix abstract for 0 special case
  EIPS/eip-5000.md
Labels: c-update, t-core, a-review, s-stagnant

#8472 Update EIP-698: fix comment
  EIPS/eip-698.md
Labels: c-update, t-core, e-review, s-stagnant

#8463 Config: Disable renovate
  .github/renovate.json
Labels: e-consensus

#8487 Update EIP-2935: replace MOD with AND
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-draft

#8497 Update EIP-2537: Finalizing test vectors for EIP-2537
  EIPS/eip-2537.md
  assets/eip-2537/add_G1_bls.json
  assets/eip-2537/add_G2_bls.json
  assets/eip-2537/fail-add_G1_bls.json
  assets/eip-2537/fail-add_G2_bls.json
  assets/eip-2537/fail-map_fp2_to_G2_bls.json
  assets/eip-2537/fail-map_fp_to_G1_bls.json
  assets/eip-2537/fail-mul_G1_bls.json
  assets/eip-2537/fail-mul_G2_bls.json
  assets/eip-2537/fail-multiexp_G1_bls.json
  assets/eip-2537/fail-multiexp_G2_bls.json
  assets/eip-2537/fail-pairing_check_bls.json
  assets/eip-2537/test-vectors.md
Labels: c-update, t-core, s-review

#8156 Update EIP-5749: Fix typo EIP-5749 typo
  EIPS/eip-5749.md
Labels: c-update, t-interface, s-final, e-consensus

#8119 Update EIP-6963: fix typo
  EIPS/eip-6963.md
Labels: c-update, t-interface, s-final, e-consensus

#8394 Update EIP-2982: Fix typos
  EIPS/eip-2982.md
Labels: c-update, t-informational, s-final, e-consensus

#8501 Update EIP-7685: clarify intra-type ordering
  EIPS/eip-7685.md
Labels: c-update, t-core, s-draft

#8502 Update EIP-7002: make 7685 ordering explicit
  EIPS/eip-7002.md
Labels: c-update, t-core, s-draft

#8500 Update EIP-7600: Move to Review
  EIPS/eip-7600.md
Labels: c-update, t-meta, w-ci, e-review, s-draft

#8385 Add EIP: EOF - Prepare for Address Space Extension
  EIPS/eip-7676.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8507 Update EIP-3074: clarify handling of incorrect nonce
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review
