Repository ethereum/EIPs, pull requests merged in 2024-05, with the labels that each got.

#8498 Add EIP: EOF - Creation transaction
  EIPS/eip-7698.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8511 Update EIP-7495: Add `Variant[S]` to abstract
  EIPS/eip-7495.md
Labels: c-update, t-core, s-review

#8512 Update EIP-7658: Only extends state, no security implications
  EIPS/eip-7658.md
Labels: c-update, t-core, s-draft

#8513 Update EIP-7658: Move to Review
  EIPS/eip-7658.md
Labels: c-status, t-core, e-review, s-review

#8016 Update EIP-101: fix typo
  EIPS/eip-101.md
Labels: c-update, t-core, w-ci, w-stale, a-review, s-stagnant

#8510 Update EIP-1: it's -> its
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#8514 Update EIP-2935: restrict contract input to 8 bytes to prevent overflow in checks
  EIPS/eip-2935.md
Labels: c-update, t-core, s-draft

#8515 Update EIP-2935: fix the input validation as 32 byte calldataload
  EIPS/eip-2935.md
Labels: c-update, t-core, s-draft

#8036 Update EIP-5283: few grammatical corrections
  EIPS/eip-5283.md
Labels: c-update, t-core, w-stale, a-review, s-stagnant

#8516 Add EIP: Native Account Abstraction with EOF
  EIPS/eip-7701.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8439 Add EIP: Forward compatible consensus data structures
  EIPS/eip-7688.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8199 Update EIP-1901: outdated links
  EIPS/eip-1901.md
  EIPS/eip-3155.md
  EIPS/eip-615.md
Labels: c-update, t-core, t-interface, w-ci, w-stale, a-review, s-stagnant

#8506 Update EIP-7069: Extend rationale about gas costs
  EIPS/eip-7069.md
Labels: c-update, t-core, s-draft

#8527 Add EIP: Set EOA account code for one transaction
  EIPS/eip-7702.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8534 Update EIP-7664: Move to Withdrawn
  EIPS/eip-7664.md
Labels: c-status, t-core, s-withdrawn

#8535 Update EIP-7069: EIP-7069 - Add Address Space Extension check
  EIPS/eip-7069.md
Labels: c-update, t-core, s-draft

#8448 Add EIP: EVM Object Format (EOFv1) Meta
  EIPS/eip-7692.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8138 Update EIP-4762: Move to Draft
  EIPS/eip-4762.md
Labels: c-status, t-core, e-review, s-draft

#8162 Add EIP: Verkle state transition via an overlay tree
  EIPS/eip-7612.md
Labels: c-new, t-core, w-stale, e-review, s-draft, e-consensus

#8544 Update EIP-7600: Update eip-7600.md
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-draft

#8545 Update EIP-7702: Warm Signers
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-draft

#8481 Update EIP-6206: adjust for new stack validation algorithm
  EIPS/eip-6206.md
Labels: c-update, t-core, s-review

#8105 Add EIP: PeerDAS - Peer Data Availability Sampling
  EIPS/eip-7594.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#8551 Update EIP-6206: fix discrepancy in stack height check JUMPF
  EIPS/eip-6206.md
Labels: c-update, t-core, a-review, s-review

#8522 Update EIP-7620: Remove TXCREATE, InitcodeTransaction and the Creator Contract
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#8548 Update EIP-6493: Add `chain_id` and move tx `type` to start
  EIPS/eip-6493.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/transaction.png
  assets/eip-6493/tx_hashes.py
Labels: c-update, t-core, s-review

#8557 Update EIP-7543: Add "arbitrary precision" to title
  EIPS/eip-7543.md
Labels: c-update, t-core, s-draft

#8553 Update EIP-7688: Include EIP-7549 attestation data structure changes
  EIPS/eip-7688.md
Labels: c-update, t-core, s-draft

#8389 Add EIP: Retroactively Included EIPs
  EIPS/eip-7675.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8558 Update EIP-7495: Rename `Variant` -> `MerkleizeAs` and improve rationale
  EIPS/eip-7495.md
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review

#8560 Update EIP-2935: typo in eip-2935
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-draft

#8566 Update EIP-6404: `SignedTransaction` --> `Transaction` rename
  EIPS/eip-6404.md
Labels: c-update, t-core, s-review

#8567 Update EIP-7688: Adopt `Profile`, and match EIP-7549 `Atetstation` order
  EIPS/eip-7688.md
Labels: c-update, t-core, s-draft

#8562 Update EIP-7495: simplify design, renaming, formatting
  EIPS/eip-7495.md
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review

#8570 Update EIP-7623: Fix typo in gas cost 16 to 12
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8571 Update EIP-7623: Fix gas cost typo
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8574 Update EIP-7623: Reduce floor price
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8577 Update EIP-2935: update for Prague devnet1
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-draft

#8559 Update EIP-7069: clarify EOF vs 7069 interactions
  EIPS/eip-7069.md
Labels: c-update, t-core, a-review, s-draft

#8581 Update EIP-7685: two typos in eip-7685.md
  EIPS/eip-7685.md
Labels: c-update, t-core, a-review, s-draft

#8584 Update EIP-5450: Fix indentation and numbering
  EIPS/eip-5450.md
Labels: c-update, t-core, a-review, s-review

#8537 Update EIP-1474: Update eip-1474.md Fixing the net_version usage example (adding missed comma and deleting the excess onse)
  EIPS/eip-1474.md
Labels: c-update, t-interface, w-ci, a-review, s-stagnant

#7961 Update EIP-1380: fix typo in EIP 1380
  EIPS/eip-1380.md
Labels: c-update, t-core, w-stale, a-review, s-stagnant

#8588 Update EIP-5450: fix typo
  EIPS/eip-5450.md
Labels: c-update, t-core, a-review, s-review

#8579 Update EIP-6493: Switch to vector based fees (EIP-7706 w/o calldata fee)
  EIPS/eip-6493.md
  EIPS/eip-7495.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/transaction.png
  assets/eip-6493/tx_hashes.py
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review, e-consensus

#8595 Update EIP-4200: Fix validation test cases
  EIPS/eip-4200.md
Labels: c-update, t-core, s-review

#8603 Update EIP-6493: Define engine API for SSZ `Transaction`
  EIPS/eip-6493.md
Labels: c-update, t-core, s-review

#8604 Update EIP-7636: Add additional security message about data reliabilty.
  EIPS/eip-7636.md
Labels: c-update, t-networking, s-review

#8277 Add EIP: History accumulator for pre-PoS data
  EIPS/eip-7643.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8543 Add EIP: NONREENTRANT and REENTRANT opcodes
  EIPS/eip-7705.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8606 Update EIP-1057: Fix typos in 37 files.
  EIPS/eip-1057.md
  EIPS/eip-107.md
  EIPS/eip-1109.md
  EIPS/eip-1965.md
  EIPS/eip-2015.md
  EIPS/eip-2315.md
  EIPS/eip-2515.md
  EIPS/eip-2711.md
  EIPS/eip-2733.md
  EIPS/eip-2780.md
  EIPS/eip-2935.md
  EIPS/eip-2976.md
  EIPS/eip-3540.md
  EIPS/eip-3779.md
  EIPS/eip-3788.md
  EIPS/eip-5027.md
  EIPS/eip-5450.md
  EIPS/eip-5792.md
  EIPS/eip-5806.md
  EIPS/eip-6206.md
  EIPS/eip-663.md
  EIPS/eip-6800.md
  EIPS/eip-6888.md
  EIPS/eip-6916.md
  EIPS/eip-6953.md
  EIPS/eip-7002.md
  EIPS/eip-7480.md
  EIPS/eip-7495.md
  EIPS/eip-7543.md
  EIPS/eip-7612.md
  EIPS/eip-7620.md
  EIPS/eip-7636.md
  EIPS/eip-7639.md
  EIPS/eip-7642.md
  EIPS/eip-7676.md
  EIPS/eip-908.md
  assets/eip-3267/contracts/BaseLock.sol
Labels: c-update, t-core, t-informational, t-interface, t-networking, w-ci, s-draft, s-review, s-final, s-withdrawn, s-stagnant, e-consensus

#8578 Add EIP: Read BLOCKHASH from storage and update cost
  EIPS/eip-7709.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8591 Update EIP-7600: Add 7702, remove 3074
  EIPS/eip-7600.md
Labels: c-update, t-meta, w-ci, s-draft

#8605 Update EIP-7688: Document types considered immutable
  EIPS/eip-7688.md
Labels: c-update, t-core, s-draft

#8586 Update EIP-7620: Initcode mode validation
  EIPS/eip-7620.md
  EIPS/eip-7698.md
Labels: c-update, t-core, s-draft, s-review
