Repository ethereum/EIPs, pull requests merged in 2024-08, with the labels that each got.

#8261 Add EIP: Optimize EOA EXTCODEHASH
  EIPS/eip-7637.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8788 Update EIP-7732: Links to consensus repo
  EIPS/eip-7732.md
Labels: c-update, t-core, s-draft

#8771 Update EIP-5792: multi-chain wallet_sendCalls
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review, s-review

#8790 Update EIP-7702: Switch order of authority warm access
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8624 Update EIP-5792: add CAIP-25 normref to eip-5792
  EIPS/eip-5792.md
Labels: c-status, t-interface, a-review, e-consensus

#8746 Update EIP-7702: Add decoding limits for AuthList items
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8776 Update EIP-7702: add more security considerations
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8795 Update EIP-7702: add a few clarifications
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8798 Update EIP-3155: Move to Draft
  EIPS/eip-3155.md
Labels: c-status, t-interface, a-review, s-draft

#8792 Update EIP-7637: Move to Review
  EIPS/eip-7637.md
Labels: c-status, t-core, e-review, s-review

#8740 Add EIP: Two dimensional log filter data structure
  EIPS/eip-7745.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8813 Update EIP-5792: Move to Last Call
  EIPS/eip-5792.md
Labels: c-status, t-interface, e-review

#8780 Update EIP-7748: fix namings
  EIPS/eip-7748.md
Labels: c-update, t-core, s-draft

#8814 Update EIP-2537: Update eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8815 Update EIP-7251: typo in the code
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#8802 Update EIP-3155: Move to Review
  EIPS/eip-3155.md
Labels: c-status, t-interface, a-review, s-review

#8774 Add EIP: Add wallet_signIntendedValidatorData method
  EIPS/eip-7749.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#8390 Update EIP-152: Fix reference test
  EIPS/eip-152.md
Labels: c-update, t-core, w-ci, w-stale, s-final, e-consensus

#8818 Update EIP-7251: remove custom ceilings prose
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#8779 Update EIP-7600: Delete EIPS/eip-7212.md
  EIPS/eip-7212.md
  EIPS/eip-7600.md
  assets/eip-7212/benchstat_compare_test
  assets/eip-7212/ecrecover_benchmark_test
  assets/eip-7212/p256Verify_benchmark_test
Labels: c-update, t-meta, a-review, s-review, e-consensus

#8690 Update EIP-7702: Small clarification fix
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8816 Update EIP-2935: update mechanism via system call
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-review

#8820 CI: Change to six months with one week warning.
  .github/workflows/stale.yml
Labels: e-consensus

#8799 Add EIP: EOF/EVM Trace Specification
  EIPS/eip-7756.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#8822 Update EIP-7742: Uncouple blob count between CL and EL
  EIPS/eip-7742.md
Labels: c-update, t-core, e-review, s-draft, e-consensus

#8749 Update EIP-7675: Move to Review
  EIPS/eip-7675.md
Labels: c-status, t-meta, w-ci, e-review, s-review

#8830 Update EIP-663: Modify specification section for EIP-663
  EIPS/eip-663.md
Labels: c-update, t-core, a-review, s-review

#8834 Update EIP-5792: Move to Review
  EIPS/eip-5792.md
Labels: c-status, t-interface, s-review

#8840 Update EIP-7702: adjust tx validity
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8841 Update EIP-6800: remove text around SELFDESTRUCT deprecation
  EIPS/eip-6800.md
Labels: c-update, t-core, a-review, s-draft

#8842 Update EIP-6493: Fix `Optional` specification for signature profile
  EIPS/eip-6493.md
  assets/eip-6493/ssz_types.py
Labels: c-update, t-core, s-review

#8827 Update EIP-7607: Update eip-7607 with Fusaka name
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft
