Repository ethereum/EIPs, pull requests merged in 2024-01, with the labels that each got.

#8061 Update EIP-684: Fix typo
  EIPS/eip-684.md
Labels: c-update, t-core, s-final, e-consensus

#8038 Update EIP-225: Update eip-225.md to fix typo "singer"
  EIPS/eip-225.md
Labels: c-update, t-core, w-ci, s-final, e-consensus

#8083 Update EIP-3540: Remove mention of terminating instruction requirement
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#8053 Update EIP-4844: Clarify type for better readability
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review, s-review

#8051 Update EIP-7569: Add Testnet times
  EIPS/eip-7569.md
Labels: c-update, t-meta, s-review

#8099 Update EIP-6404/6465/6466/6493: Remove placeholder TBD sections
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
Labels: c-update, t-core, s-draft, s-review

#8071 Update EIP-6404: Move to Review
  EIPS/eip-6404.md
Labels: c-status, t-core, e-review, s-review

#8116 Update EIP-7002: Fix typos
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-draft

#8060 Update EIP-6916: fix typo
  EIPS/eip-6916.md
Labels: c-update, t-core, a-review, s-review

#8128 Update EIP-5806: Update EIP-5806
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8129 Update EIP-5806: use TX_TYPE for signature generation
  EIPS/eip-5806.md
Labels: c-update, t-core, s-draft

#8124 Update EIP-4762: fix some syntax issues
  EIPS/eip-4762.md
Labels: c-update, t-core, e-review, s-stagnant

#8134 Update EIP-7514: Move to Last Call
  EIPS/eip-7514.md
Labels: c-status, t-core, e-review

#8122 Update EIP-6466: Move to Review
  EIPS/eip-6466.md
Labels: c-status, t-core, e-review, s-review

#8072 Update EIP-6465: Move to Review
  EIPS/eip-6465.md
Labels: c-status, t-core, e-review, s-review

#8133 Update EIP-6122: Move to Final
  EIPS/eip-6122.md
Labels: c-status, t-networking, a-review, s-final

#8132 Update EIP-6953: Move to Final
  EIPS/eip-6953.md
Labels: c-status, t-informational, w-ci, e-review, s-final

#8141 Update EIP-4788: Move to Last Call
  EIPS/eip-4788.md
Labels: c-status, t-core, e-review

#8148 Update EIP-4938: Move to Last Call
  EIPS/eip-4938.md
Labels: c-status, t-networking, a-review

#8147 Update EIP-5793: Move to Last Call
  EIPS/eip-5793.md
Labels: c-status, t-networking, w-ci, a-review

#8146 Update EIP-4844: Move to Last Call
  EIPS/eip-4844.md
Labels: c-status, t-core, e-review

#8150 Update EIP-7251: Fix typo EIP-7251 typo
  EIPS/eip-7251.md
Labels: c-update, t-core, s-draft

#8143 Update EIP-7516: Move to Last Call
  EIPS/eip-7516.md
Labels: c-status, t-core, e-review

#8144 Update EIP-7044: Move to Last Call
  EIPS/eip-7044.md
Labels: c-status, t-core, w-ci, e-review

#8139 Update EIP-7045: Move to Last Call
  EIPS/eip-7045.md
Labels: c-status, t-core, e-review

#8140 Update EIP-6780: Move to Last Call
  EIPS/eip-6780.md
Labels: c-status, t-core, w-ci, e-review
