Repository ethereum/EIPs, pull requests merged in 2024-06, with the labels that each got.

#8617 Update EIP-7069: Padding oob behavior of RETURNDATA*
  EIPS/eip-7069.md
Labels: c-update, t-core, a-review, s-draft

#8619 Update EIP-7495: Cleanup reference implementation and tests
  EIPS/eip-7495.md
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review, e-consensus

#8621 Update EIP-3540: Clarify EXTDELEGATECALL to "legacy"
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#8034 Add EIP: Versioning Scheme for EIPs
  EIPS/eip-7577.md
  assets/eip-7577/semver.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#8561 Update EIP-7702: refine based on discussions
  EIPS/eip-7702.md
Labels: c-update, t-core, s-draft

#8633 Update EIP-7643: Fix MAX_HISTORICAL_EPOCHS for provided root
  EIPS/eip-7643.md
Labels: c-update, t-core, s-draft

#8635 Update EIP-2537: Fix some nits
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8596 Update EIP-2935: Update EVM bytecode to add the system set update op
  EIPS/eip-2935.md
Labels: c-update, t-core, s-draft

#8640 Update EIP-7549: Update eip-7549 with latest version
  EIPS/eip-7549.md
Labels: c-update, t-core, s-draft

#8641 Update EIP-2935: Cleanup references and add some blockhash opcode clarifications
  EIPS/eip-2935.md
Labels: c-update, t-core, s-draft

#8642 Update EIP-2935: Further cleanup of the text
  EIPS/eip-2935.md
Labels: c-update, t-core, s-draft

#8632 Update EIP-7600: Update EIP-7600 required header
  EIPS/eip-7600.md
Labels: c-update, t-meta, a-review, s-draft

#8625 Update EIP-7251: Add EL triggered consolidations
  EIPS/eip-7251.md
Labels: c-update, t-core, s-draft

#8646 Update EIP-7549: Move to Review
  EIPS/eip-7549.md
Labels: c-status, t-core, e-review, s-review

#8645 Add some additional tests
  assets/eip-2537/multiexp_G1_bls.json
  assets/eip-2537/multiexp_G2_bls.json
  assets/eip-2537/test-vectors.md
Labels: e-consensus

#8575 Add EIP: ETH transfers emit a log
  EIPS/eip-7708.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8598 Add EIP: Anti-correlation attestation penalties
  EIPS/eip-7716.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8102 Add EIP: BLS signed transactions
  EIPS/eip-7591.md
Labels: c-new, t-core, w-stale, e-review, s-draft, e-consensus

#8529 Add EIP: Increase calldata cost
  EIPS/eip-7703.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8648 Update EIP-7591: fix eip 7591 typo
  EIPS/eip-7591.md
Labels: c-update, t-core, a-review, s-draft

#8315 Update EIP-5806: grammar correction
  EIPS/eip-5806.md
Labels: c-update, t-core, w-stale, a-review, s-draft

#8650 Update EIP-6493: Cleanups for latest `StableContainer` specs
  EIPS/eip-6493.md
  assets/eip-6493/convert.py
  assets/eip-6493/convert_tests.py
  assets/eip-6493/ssz_types.py
  assets/eip-6493/tx_hashes.py
Labels: c-update, t-core, s-review

#8665 Update EIP-7495: Remove redundant `is_active_field` helper
  EIPS/eip-7495.md
Labels: c-update, t-core, s-review

#8649 Update EIP-7600: Add PeerDAS
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-draft

#8654 Update EIP-7002: Move to Review
  EIPS/eip-7002.md
Labels: c-status, t-core, w-ci, a-review, s-review

#8647 Update EIP-7251: Move to Review
  EIPS/eip-7251.md
Labels: c-status, t-core, w-ci, e-review, s-review

#8660 Update EIP-7698: Move to Review
  EIPS/eip-7698.md
Labels: c-status, t-core, a-review, s-review

#8661 Update EIP-7547: Move to Review
  EIPS/eip-7547.md
Labels: c-status, t-core, a-review, s-review

#8658 Update EIP-7692: Move to Review
  EIPS/eip-7692.md
Labels: c-status, t-meta, w-ci, a-review, s-review

#8657 Update EIP-7702: Move to Review
  EIPS/eip-7702.md
Labels: c-status, t-core, a-review, s-review

#8653 Update EIP-6110: Move to Review
  EIPS/eip-6110.md
Labels: c-status, t-core, a-review, s-review

#8652 Update EIP-2935: Move to Review
  EIPS/eip-2935.md
Labels: c-status, t-core, a-review, s-review

#8671 Update EIP-7594: Move to Review
  EIPS/eip-7594.md
Labels: c-status, t-networking, a-review, s-review

#8672 7623: move to review
  EIPS/eip-7623.md
Labels: c-status, t-core, s-review

#8674 Update EIP-7716: fix typos
  EIPS/eip-7716.md
Labels: c-update, t-core, a-review, s-draft

#8675 Update EIP-7698: Clarify relation to 3541
  EIPS/eip-7698.md
Labels: c-status, t-core, s-draft

#8607 Update EIP-2982: fix table displaying error
  EIPS/eip-2982.md
Labels: c-update, t-informational, w-ci, s-final, e-consensus

#8309 Update EIP-2537: rename PAIRING to PAIRING_CHECK; introduce PAIRING_PRODUCT precomiple
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8670 Update EIP-3540: align with recent clarifications and updates
  EIPS/eip-3540.md
Labels: c-update, t-core, a-review, s-review

#8503 Update EIP-1: Document EEST
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#8679 Update EIP-7702: Reorder authorization fields for authority recovery
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8686 Update EIP-7702: note tx is invalid if nonce is not formatted correctly
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8669 Update EIP-7636: Move to Last Call
  EIPS/eip-7636.md
Labels: c-status, t-networking, e-review

#8688 Update EIP-7620: remove obsolete Rationale paragraph
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#8692 Update EIP-5792: Push last call date back
  EIPS/eip-5792.md
Labels: c-update, t-interface

#8550 Update EIP-4762: reworked gas schedule from interop
  EIPS/eip-4762.md
  EIPS/eip-6800.md
Labels: c-update, t-core, s-draft

#8700 Update EIP-4762: Cleanup/refactor the text as per clarifications
  EIPS/eip-4762.md
Labels: c-update, t-core, w-ci, s-draft
