Repository ethereum/EIPs, pull requests merged in 2024-09, with the labels that each got.

#8847 Update EIP-7620: Fix typo, formatting, and add EIP references
  EIPS/eip-7620.md
Labels: c-update, t-core, a-review, s-review

#8843 Update EIP-7723: Move to Review
  EIPS/eip-7723.md
Labels: c-status, t-meta, e-review, s-review

#8817 Update EIP-712: Fix typo
  EIPS/eip-712.md
Labels: c-update, t-interface, w-ci, s-final, e-consensus

#8858 Update EIP-7745: Fix reverse_transform
  EIPS/eip-7745.md
Labels: c-update, t-core, s-draft

#8859 Update EIP-7723: MUST -> SHOULD
  EIPS/eip-7723.md
Labels: c-update, t-meta, s-review

#8837 Update EIP-7742: Move to Review
  EIPS/eip-7742.md
Labels: c-status, t-core, e-review, s-review

#8863 Update EIP-7620: Clarify EOFCREATE in static mode
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#8870 Website: Remove polyfill.
  _includes/head.html
Labels: e-consensus

#8871 Update EIP-7702: Remove reference to post-tx code deletion
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8838 Add EIP: HASCODE instruction
  EIPS/eip-7761.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8867 Update EIP-4762: unconditionnal account write during contract init
  EIPS/eip-4762.md
Labels: c-update, t-core, s-draft

#8875 Update EIP-7761: reference 3540 explicitly
  EIPS/eip-7761.md
Labels: c-update, t-core, s-draft

#8876 Update EIP-2537: fix typo
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8879 Update EIP-6404: Move to Draft
  EIPS/eip-6404.md
Labels: c-status, t-core, s-draft

#8880 Update EIP-6493: Move to Draft
  EIPS/eip-6493.md
Labels: c-status, t-core, s-draft

#8845 Update EIP-7702: 7702 validity
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8873 Update EIP-7623: homogenize calculation examples
  EIPS/eip-7623.md
Labels: c-update, t-core, a-review, s-review

#8886 Update EIP-6404: Rename `from` signature fields
  EIPS/eip-6404.md
  EIPS/eip-6493.md
  assets/eip-6404/convert.py
  assets/eip-6404/ssz_types.py
  assets/eip-6404/transaction.png
  assets/eip-6404/tx_hashes.py
Labels: c-update, t-core, s-draft

#8889 Update EIP-7251: update byte code with logging
  EIPS/eip-7251.md
Labels: c-update, t-core, s-review

#8890 Update EIP-7002: add logging to system contract
  EIPS/eip-7002.md
Labels: c-update, t-core, s-review

#8707 Update EIP-4762: Add clarifications for the system contracts
  EIPS/eip-4762.md
Labels: c-update, t-core, s-draft

#8894 Update EIP-7688: Adjustments for `v1.5.0-alpha.6` specs
  EIPS/eip-7688.md
Labels: c-update, t-core, s-review

#8904 Update EIP-7761: Fill Endgame AA's Rationale section
  EIPS/eip-7761.md
Labels: c-update, t-core, s-draft

#8901 Update EIP-7069: Remove stale TODOs
  EIPS/eip-7069.md
Labels: c-update, t-core, s-review

#8722 Update EIP-712: Fix incorrect byte counts
  EIPS/eip-712.md
Labels: w-ci, e-consensus

#8849 Add EIP: Increase MIN_BASE_FEE_PER_BLOB_GAS
  EIPS/eip-7762.md
  assets/eip-7762/base_fee_1.png
  assets/eip-7762/base_fee_225.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8854 Update EIP-7685: change requests hash to flat hash
  EIPS/eip-7685.md
Labels: c-update, t-core, a-review, s-review

#8857 Update EIP-7251: change request to flat encoding
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#8855 Update EIP-7002: change request to flat encoding
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#8903 Update EIP-7702: some copy edits
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8907 Update EIP-7685: fix stale function name
  EIPS/eip-7685.md
Labels: c-update, t-core, s-review

#8912 Update EIP-7762: Move to Review
  EIPS/eip-7762.md
Labels: c-status, t-core, a-review, s-review

#8911 Add EIP: Hardfork Meta - Amsterdam
  EIPS/eip-7600.md
  EIPS/eip-7607.md
  EIPS/eip-7773.md
Labels: c-new, c-update, t-meta, e-review, s-draft, s-review, e-consensus
