Repository ethereum/EIPs, pull requests merged in 2024-10, with the labels that each got.

#8856 Update EIP-6110: change request to flat encoding
  EIPS/eip-6110.md
Labels: c-update, t-core, a-review, s-review

#8917 Update EIP-6110: Update deposit request list encoding
  EIPS/eip-6110.md
Labels: c-update, t-core, s-review

#8921 Update EIP-7623: Provide further clarification on implementation
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#8922 Update EIP-7495: Extend tests and detect errors when coercing profiles
  EIPS/eip-7495.md
  assets/eip-7495/remerkleable.diff
  assets/eip-7495/stable_container.py
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review

#8897 Update EIP-6404: Add support for SetCode transactions
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
  assets/eip-6404/convert.py
  assets/eip-6404/convert_tests.py
  assets/eip-6404/rlp_types.py
  assets/eip-6404/ssz_types.py
  assets/eip-6404/transaction.png
  assets/eip-6404/tx_hashes.py
Labels: c-update, t-core, s-draft

#8918 Add EIP: Prevent Block Gas Smuggling
  EIPS/eip-7778.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8934 Update EIP-7002: add updated excess inhibitor logic
  EIPS/eip-7002.md
  EIPS/eip-7251.md
Labels: c-update, t-core, s-review

#8924 Update EIP-7685: group requests into request-data
  EIPS/eip-7685.md
Labels: c-update, t-core, s-review

#8936 Update EIP-7685: fix typo
  EIPS/eip-7685.md
Labels: c-update, t-core, s-review

#8938 Update EIP-7702: 8905 copy
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8940 Update EIP-7702: 8906 copy
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8943 Update EIP-7691: Update EIP-7691 with information on ongoing analysis
  EIPS/eip-7691.md
Labels: c-update, t-core, s-draft

#8929 Update EIP-7702: restrict field sizes
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8944 Update EIP-2537: Replace "multiexponentiation"
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8948 Update EIP-7702: fixup gas costs and empty code hash
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8931 Add EIP: Reduce Slot Time for Lower Peak Bandwidth
  EIPS/eip-7782.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8942 Update EIP-4762: value-bearing clarification
  EIPS/eip-4762.md
Labels: c-update, t-core, s-draft

#8950 Update EIP-7702: add s value check
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8949 Update EIP-6110: harmonize request eips with 7685 changes
  EIPS/eip-6110.md
  EIPS/eip-7002.md
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#8946 Update EIP-7495: Rename `PendingBalanceDeposit` > `PendingDeposit`
  EIPS/eip-7495.md
  EIPS/eip-7688.md
  assets/eip-7495/remerkleable.patch
  assets/eip-7495/tests.py
Labels: c-update, t-core, s-review

#8951 Update EIP-4762: add clarification regarding OOG behavior
  EIPS/eip-4762.md
Labels: c-update, t-core, s-draft

#8963 CI: Upgrade to eipw 0.9
  .github/workflows/ci.yml
  config/eipw.toml
Labels: e-consensus

#8964 Update EIP-7002: move ssz serialization into system call
  EIPS/eip-7002.md
  EIPS/eip-7251.md
Labels: c-update, t-core, s-review

#8797 Update EIP-7600: Remove "for one transaction" from 7702 description
  EIPS/eip-7600.md
Labels: c-update, t-meta, a-review, s-review

#8966 Update EIP-7702: update description
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8933 Add EIP: Add Controlled Gas Limit Increase Strategy
  EIPS/eip-7783.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#8909 Update EIP-7702: Remove old note about universal cross-chain deployment
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#8970 Update EIP-6913: Move to Withdrawn
  EIPS/eip-6913.md
Labels: c-status, t-core, s-withdrawn

#8971 CI: Bump setup-ruby to v1.196.0
  .github/workflows/ci.yml
  .github/workflows/jekyll.yml
Labels: e-consensus

#8977 Update EIP-7251: [EIP-7251] Update CONSOLIDATION_REQUEST_PREDEPLOY_ADDRESS
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#8939 Update EIP-6404: Add `from`, `authorities`, and drop `logs_bloom`
  EIPS/eip-6404.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
  assets/eip-6404/convert.py
  assets/eip-6404/convert_tests.py
  assets/eip-6404/ssz_types.py
  assets/eip-6466/receipt.png
Labels: c-update, t-core, s-draft

#8976 Update EIP-7002: [EIP-7002] Updated WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#8941 Update EIP-7701: EIP-7701 update
  EIPS/eip-7701.md
Labels: c-update, t-core, w-ci, s-draft

#8914 Add EIP: BURN opcode
  EIPS/eip-7775.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8935 Add EIP: GETCONTRACT opcode
  EIPS/eip-7784.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8984 Add EIP: Verifiable logs
  EIPS/eip-7792.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8990 Update EIP-7069: emphasis - `value` rules are EXTCALL only
  EIPS/eip-7069.md
Labels: c-update, t-core, a-review, s-review

#8974 Add EIP: Controlled Gas Limit Increase Guidelines
  EIPS/eip-7790.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#8996 Update EIP-7600: Update eip-7600.md
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-review

#9002 Add EIP: System logs
  EIPS/eip-7799.md
Labels: c-new, t-core, e-review, s-draft, e-consensus
