Repository ethereum/EIPs, pull requests merged in 2024-03, with the labels that each got.

#8275 Update EIP-7623: Improve phrasing
  EIPS/eip-7623.md
Labels: c-update, t-core, s-draft

#8278 Update EIP-3074: allow only current nonce in auth msg
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8279 Update EIP-3074: typo
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8286 Update EIP-6800: refer to eip 4762 for the state access costs
  EIPS/eip-6800.md
Labels: c-update, t-core, s-draft

#7819 Update EIP-663: Move to Draft
  EIPS/eip-663.md
Labels: c-update, t-core, a-review, s-review

#8288 Update EIP-7620: Rename and update
  EIPS/eip-7620.md
Labels: c-update, t-core, e-review, s-draft

#8291 Update EIP-2537: Update to reflect timestamp-based forking and tightly pack precompile address range
  EIPS/eip-2537.md
Labels: c-update, t-core, s-review

#8260 Add EIP: Extension of EIP-778 for "client" ENR Entry
  EIPS/eip-7636.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#7836 Update EIP-6800: pedersen hash endianness and group to field fixes
  EIPS/eip-6800.md
Labels: c-update, t-core, a-review, s-draft

#7951 Update EIP-6110: add pubkey2index cache analysis by @naviechan
  EIPS/eip-6110.md
  assets/eip-6110/pubkey_to_index_cache_analysis.md
Labels: c-update, t-core, s-draft, e-consensus

#8274 Update EIP-2537: Editorial
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8305 Update EIP-3670: Align with EOF Megaspec and other EIPs
  EIPS/eip-3670.md
Labels: c-update, t-core, a-review, s-review

#8306 Update EIP-7620: Move to Review
  EIPS/eip-7620.md
Labels: c-status, t-core, e-review, s-review

#8303 Update EIP-7569: Update eip-7569.md
  EIPS/eip-7569.md
Labels: c-update, t-meta, a-review

#8300 Add EIP: Programmable access lists
  EIPS/eip-7650.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8285 Website: Fixes ECH discord link
  index.html
Labels: e-consensus

#8283 Add EIP: Alias ORIGIN to SENDER
  EIPS/eip-7645.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8271 Add EIP: eth/69 - Drop pre-merge fields
  EIPS/eip-7642.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#8280 Update EIP-1: add exec spec tests to allowed links
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#8310 Update EIP-2537: Update eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core, s-review

#8313 Update EIP-2537: adding test vectors
  EIPS/eip-2537.md
  assets/eip-2537/add_G1_bls.json
  assets/eip-2537/add_G2_bls.json
  assets/eip-2537/map_fp2_to_G2_bls.json
  assets/eip-2537/map_fp_to_G1_bls.json
  assets/eip-2537/mul_G1_bls.json
  assets/eip-2537/mul_G2_bls.json
  assets/eip-2537/multiexp_G1_bls.json
  assets/eip-2537/multiexp_G2_bls.json
  assets/eip-2537/test-vectors.md
Labels: c-update, t-core, s-review

#8251 Update EIP-7523: Move to Last Call
  EIPS/eip-7523.md
Labels: c-status, t-core, a-review

#8318 Update EIP-4788: Move to Final
  EIPS/eip-4788.md
Labels: c-status, t-core, e-review, s-final

#8319 Update EIP-7377: Move to Draft
  EIPS/eip-7377.md
Labels: c-status, t-core, s-draft

#8324 Update EIP-7547: Change modification to payload attribute SSE event
  EIPS/eip-7547.md
Labels: c-update, t-core, a-review, s-draft

#8323 Update EIP-7620: minor fixes and clarifications in the spec
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#8329 Update EIP-3074: allow authorized to send value
  EIPS/eip-3074.md
Labels: c-update, t-core, s-review

#8338 Update EIP-1: fix typo in exec spec tests link
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#8344 Update EIP-7600: Add MaxEB + ILs
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-draft

#8347 Update EIP-7609: update security considerations with reference points
  EIPS/eip-7609.md
Labels: c-update, t-core, s-draft

#8287 Update EIP-7069: Rename and update semantics
  EIPS/eip-7069.md
Labels: c-update, t-core, a-review, s-draft

#8228 Update EIP-7002: convert to system contract
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-draft

#8349 Config: Allow links to execution-spec-tests
  config/eipw.toml
Labels: e-consensus

#8346 Update EIP-5656: Move to Final
  EIPS/eip-5656.md
Labels: c-status, t-core, a-review, s-final

#8316 Update EIP-4844: Update blob base fee to base fee per blob gas
  EIPS/eip-4844.md
Labels: c-update, t-core, a-review

#8345 Update EIP-7044: Move to Final
  EIPS/eip-7044.md
  EIPS/eip-7514.md
Labels: c-status, c-update, t-core, a-review, s-final

#8335 Update EIP-4844: Move to Final
  EIPS/eip-4844.md
  EIPS/eip-4938.md
  EIPS/eip-5793.md
Labels: c-status, t-core, t-networking, a-review, s-final

#8337 Update EIP-7045: Move to Final
  EIPS/eip-7045.md
Labels: c-status, t-core, a-review, s-final

#8336 Update EIP-6780: Move to Final
  EIPS/eip-6780.md
Labels: c-status, t-core, a-review, s-final

#8333 Update EIP-1153: Move to Final
  EIPS/eip-1153.md
  EIPS/eip-7516.md
  EIPS/eip-7568.md
Labels: c-status, t-core, t-meta, a-review, s-final

#8362 Update EIP-7044: Move to Final
  EIPS/eip-7044.md
Labels: c-status, t-core, a-review, s-final

#8334 Update EIP-7569: Move to Final
  EIPS/eip-7569.md
Labels: c-status, t-meta, e-review, s-final
