Repository ethereum/EIPs, pull requests merged in 2024-11, with the labels that each got.

#9007 Update EIP-7742: Rename *_blob_count to *_blobs_per_block
  EIPS/eip-7742.md
Labels: c-update, t-core, a-review, s-review

#8995 Add EIP: Double speed for hash_tree_root
  EIPS/eip-7797.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9016 Update EIP-7745: improve hashing scheme, simplify proving process
  EIPS/eip-7745.md
Labels: c-update, t-core, s-draft

#8991 Config: Fixes ethereum/eipw#113
  config/eipw.toml
Labels: e-consensus

#9021 Update EIP-7610: Move to Last Call
  EIPS/eip-7610.md
Labels: c-status, t-core, a-review

#8969 Update EIP-7702: Remove delegation behavior of EXTCODE*
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#9010 Add EIP: Fork-choice enforced Inclusion Lists (FOCIL)
  EIPS/eip-7805.md
  assets/eip-FOCIL/diagram_FOCIL.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9027 Update EIP-7749: Add Test Cases section
  EIPS/eip-7749.md
Labels: c-update, t-interface, s-draft

#9030 Update EIP-7792: Change `LogEntry` to number + tx index
  EIPS/eip-7792.md
Labels: c-update, t-core, s-draft

#9031 Update EIP-6404: Align title lettercase across SSZ EIPs
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
Labels: c-update, t-core, s-draft

#9017 Add EIP: SSZ execution blocks
  EIPS/eip-7807.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9019 Update EIP-7587: Move to Final
  EIPS/eip-7587.md
Labels: c-status, t-meta, e-review, s-final

#9004 Add EIP: eth/70 - Sharded Blocks Protocol
  EIPS/eip-7801.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#9020 Add EIP: Reserve Tx-Type Range for RIPs
  EIPS/eip-7808.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#9040 Update EIP-7002: add excess inhibitor logic
  EIPS/eip-7002.md
  EIPS/eip-7251.md
Labels: c-update, t-core, s-review

#9043 Update EIP-7702: Update eip-7702.md
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#9042 Add EIP: Create delegate
  EIPS/eip-7819.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#8989 Update EIP-7685: exclude empty requests data in commitment
  EIPS/eip-7685.md
Labels: c-update, t-core, a-review, s-review

#9033 Update EIP-6888: Move to Draft
  EIPS/eip-6888.md
Labels: c-status, t-core, e-review, s-draft

#9055 Update EIP-6206: clarify wording on JUMPF (EOF)
  EIPS/eip-6206.md
Labels: c-update, t-core, a-review, s-review

#9046 Add EIP: Set upper bounds for MODEXP
  EIPS/eip-7823.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9024 Update EIP-7002: return fee from getter and add usage example
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#9063 Update EIP-4803: Move to Review
  EIPS/eip-4803.md
Labels: c-status, t-core, s-review
