Repository ethereum/EIPs, pull requests merged in 2024-12, with the labels that each got.

#9078 Update EIP-3670: Move to Review
  EIPS/eip-3670.md
Labels: c-status, t-core, s-review

#9077 Update EIP-4200: Update discussion URL in 4200
  EIPS/eip-4200.md
Labels: c-update, t-core, w-ci, s-review

#9079 Update EIP-7480: Fix rendering of instruction list
  EIPS/eip-7480.md
Labels: c-update, t-core, s-review

#9074 Add EIP: Contract size limit increase for EOF
  EIPS/eip-7830.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9049 Add EIP: Transaction Gas Limit Cap
  EIPS/eip-7825.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9061 Update EIP-6690: Move to Draft
  EIPS/eip-6690.md
Labels: c-status, t-core, e-review, s-draft, e-consensus

#9005 Add EIP: Withdrawal Credential Update Request
  EIPS/eip-7804.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9086 Update EIP-7623: Update EIP-7762 with additional security considerations
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#9087 Update EIP-7639: format as new eth wire protocol
  EIPS/eip-7639.md
Labels: c-update, t-networking, s-draft

#9088 Update EIP-7623: add additional backwards compatibility considerations
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#9090 Update EIP-7762: add excess gas reset
  EIPS/eip-7762.md
Labels: c-update, t-core, a-review, s-review

#9060 Update EIP-7691: add update fraction specification
  EIPS/eip-7691.md
Labels: c-update, t-core, a-review, s-draft

#9058 Update EIP-7801: Eip 7801 bitmask
  EIPS/eip-7801.md
Labels: c-update, t-networking, a-review, s-draft

#9056 Update EIP-7723: Add "Declined for Inclusion"
  EIPS/eip-7723.md
Labels: c-update, t-meta, s-review

#9091 Update EIP-7639: Fix rendering of 7639 specification
  EIPS/eip-7639.md
Labels: c-update, t-networking, a-review, s-draft

#9101 Update EIP-7639: protocol version should be 70
  EIPS/eip-7639.md
Labels: c-update, t-networking, s-draft

#9104 Update EIP-7756: Cleanup
  EIPS/eip-7756.md
Labels: c-update, t-interface, s-draft

#9107 Update EIP-7623: Clarify and polish text
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#9117 Update EIP-5450: EIP-5450 - Speling corrections and on editorial change
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#9118 Update EIP-7251: fix CONSOLIDATION_REQUEST_PREDEPLOY_ADDRES
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#9119 Update EIP-7002: fix WITHDRAWAL_REQUEST_PREDEPLOY_ADDRESS
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#9120 Update EIP-7251: replace check_fee with get_fee check
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#9122 Update EIP-7742: use parent target blob count for excess blob gas calculation
  EIPS/eip-7742.md
Labels: c-update, t-core, s-review

#9123 Update EIP-7623: Remove duplicated paragraph
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#9099 Update EIP-7801: Update eip-7801.md
  EIPS/eip-7801.md
Labels: c-update, t-networking, s-draft

#9127 Update EIP-7251: Set MAX_CONSOLIDATIONS=2
  EIPS/eip-7251.md
Labels: c-update, t-core, s-review

#9110 Update EIP-7756: Eip7756/table layout
  EIPS/eip-7756.md
Labels: c-update, t-interface, s-draft

#9136 Update EIP-7702: Add security consideration about use of storage
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#9142 Update EIP-7805: Add explicit references to `MAX_BYTES_PER_INCLUSION_LIST`
  EIPS/eip-7805.md
Labels: c-update, t-core, s-draft

#9132 Update EIP-6916: Move to Last Call
  EIPS/eip-6916.md
Labels: c-status, t-core, e-review

#9093 Update EIP-7542: Move to Withdrawn
  EIPS/eip-7542.md
Labels: c-status, t-networking, e-review, s-withdrawn

#9096 Add EIP: Scheduled function calls
  EIPS/eip-7833.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9100 Add EIP: Separate Metadata Section for EOF
  EIPS/eip-7834.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9097 Update EIP-2537: Gas pricing MAP, MUL and ADD operations
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9098 Update EIP-2537: Gas pricing pairing operations
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9116 Update EIP-2537: MSM gas repricing
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#8987 Update EIP-712: Update eip-712.md
  EIPS/eip-712.md
Labels: c-update, t-interface, w-ci, s-final, e-consensus

#9140 Update EIP-1015: Fix Typographical Errors
  EIPS/eip-1015.md
  EIPS/eip-1186.md
  EIPS/eip-1470.md
Labels: c-update, t-core, t-informational, t-interface, s-stagnant, e-consensus

#9095 Update EIP-7691: Move to Review
  EIPS/eip-7691.md
Labels: c-status, t-core, a-review, s-review

#9094 Update EIP-7600: Add EIPs 7623 & 7691
  EIPS/eip-7600.md
Labels: c-update, t-meta, w-ci, s-review

#9092 Update EIP-7675: Add EIP-4803 to EIP-7675
  EIPS/eip-7675.md
Labels: c-update, t-meta, a-review, s-review

#9126 Update EIP-7723: CFI/SFI & Devnets
  EIPS/eip-7723.md
Labels: c-update, t-meta, s-review

#9159 Update EIP-7251: Update eip-7251.md
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#9160 Update EIP-7691: Update eip-7691.md
  EIPS/eip-7691.md
Labels: c-update, t-core, a-review, s-review

#9157 Update EIP-6110: Update eip-6110.md
  EIPS/eip-6110.md
Labels: c-update, t-core, a-review, s-review

#9158 Update EIP-7002: Update eip-7002.md
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#9143 Update EIP-7702: make chain id u256
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#8945 Update EIP-2537: Remove redundant MUL precompiles
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9156 Update EIP-2935: Update eip-2935.md
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-review

#9080 Update EIP-7503: Move to Draft
  EIPS/eip-7503.md
Labels: c-status, t-core, w-ci, a-review, s-draft

#9163 Update EIP-7607: Add EIP-7666 (EVM-ify the identity precompile) to proposed-for-inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9133 Update EIP-7642: don't remove NewBlock(Hashes)
  EIPS/eip-7642.md
Labels: c-update, t-networking, a-review, s-draft

#9155 Update EIP-2537: Update eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9167 Update EIP-7808: Move to Review
  EIPS/eip-7808.md
Labels: c-status, t-meta, e-review, s-review

#9141 Add EIP: SLOT precompile
  EIPS/eip-7843.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9184 Update EIP-7691: fix typos
  EIPS/eip-7691.md
Labels: c-update, t-core, a-review, s-review

#8888 Add EIP: No-Ether transactions with free-for-all tips
  EIPS/eip-7768.md
Labels: c-new, t-meta, w-ci, e-review, s-draft, e-consensus

#9191 Update EIP-4762: fix typo
  EIPS/eip-4762.md
Labels: c-update, t-core, a-review, s-draft

#9197 Update EIP-7723: Escape Latex
  EIPS/eip-7723.md
Labels: c-update, t-meta, s-review

#9206 Update EIP-7691: Typo Fix
  EIPS/eip-7691.md
Labels: c-update, t-core, s-review
