Repository ethereum/EIPs, pull requests merged in 2025-04, with the labels that each got.

#9569 Update EIP-7873: Align TXCREATE stack argument order with EOFCREATE
  EIPS/eip-7873.md
Labels: c-update, t-core, s-draft

#9508 Update EIP-7002: Add system call gas aspects and directive for handling failures
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review

#9430 Update EIP-1015: Update eip-1015.md
  EIPS/eip-1015.md
Labels: c-update, t-core, w-ci, e-review, s-stagnant

#9548 Add EIP: Skip `JUMPDEST` immediate argument check
  EIPS/eip-7921.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9428 Add EIP: Block-level Warming with fair cost savings
  EIPS/eip-7557.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9570 Adding additional test vectors (EIP-2537)
  assets/eip-2537/add_G1_bls.json
  assets/eip-2537/add_G2_bls.json
  assets/eip-2537/fail-add_G1_bls.json
  assets/eip-2537/fail-add_G2_bls.json
  assets/eip-2537/fail-msm_G1_bls.json
  assets/eip-2537/fail-msm_G2_bls.json
  assets/eip-2537/fail-mul_G1_bls.json
  assets/eip-2537/fail-mul_G2_bls.json
  assets/eip-2537/fail-pairing_check_bls.json
  assets/eip-2537/msm_G1_bls.json
Labels: e-consensus

#9378 Update EIP-7594: include cell proofs in network wrapper of blob txs
  EIPS/eip-7594.md
Labels: c-update, t-networking, e-review, s-stagnant

#9331 Update EIP-7801: Update 7801 to accomodate era1 file format storage and serving
  EIPS/eip-7801.md
Labels: c-update, t-networking, s-draft

#9582 Update EIP-7251: Add system call properties and directive for failure cases
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review

#9584 Update EIP-4750: Fix the definition of 0th code section type
  EIPS/eip-4750.md
Labels: c-update, t-core, s-review

#9490 Update EIP-7873: TXCREATE hashing scheme to EOFCREATE with ASE
  EIPS/eip-7873.md
Labels: c-update, t-core, s-draft

#9560 Update EIP-7600: Pectra Tentative Mainnet Activation Time
  EIPS/eip-7600.md
Labels: c-update, t-meta

#9592 Update EIP-6206: Ban the EOF-only opcodes in legacy
  EIPS/eip-6206.md
  EIPS/eip-7620.md
  EIPS/eip-7873.md
Labels: c-update, t-core, a-review, s-draft, s-review

#9587 Update EIP-7594: Move to Review
  EIPS/eip-7594.md
Labels: c-status, t-networking, a-review, s-review

#9595 Update EIP-7600: Add Hoodi
  EIPS/eip-7600.md
Labels: c-update, t-meta

#9598 Update EIP-5450: Metion SPIR-V, fix typos.
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#9599 Update EIP-5450: Expand on block ordering
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#9529 Update EIP-5792: Propose changes to EIP-5792 atomicity
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review, s-review

#9608 Update EIP-7251: Fix typos in EIP-7251 (from author no farming)
  EIPS/eip-7251.md
Labels: c-update, t-core

#9610 Update EIP-7761: Move to Review
  EIPS/eip-7761.md
Labels: c-status, t-core, e-review, s-review

#9612 Update EIP-7873: Move to Review
  EIPS/eip-7873.md
Labels: c-status, t-core, e-review, s-review

#9593 Update EIP-7873: Move to Review
  EIPS/eip-7873.md
Labels: c-status, t-core, e-review, s-review

#9609 Update EIP-7834: Move to Review
  EIPS/eip-7834.md
Labels: c-status, t-core, a-review, s-review

#9503 Update EIP-7620: Align EOFCREATE stack args with EXTCALL
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#9607 Update EIP-7620: Replace mentions of EOF Creation Transactions with InitcodeTransaction
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#9613 Update EIP-7880: Move to Review
  EIPS/eip-7880.md
Labels: c-status, t-core, w-ci, e-review, s-review

#9472 Update EIP-1898: Move to Final
  EIPS/eip-1898.md
Labels: c-status, t-interface, a-review, s-final

#9556 Add EIP: Linear, Page-Based Memory Costing
  EIPS/eip-7923.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9605 docs: fix inconsistency in G2 group point notation
  assets/eip-2537/fast_subgroup_checks.md
Labels: e-consensus

#9566 Update EIP-7872: Move to Review
  EIPS/eip-7872.md
Labels: c-status, t-meta, e-review, s-review

#9554 Update EIP-7918: Move to Review
  EIPS/eip-7918.md
Labels: c-status, t-core, e-review, s-review

#9619 Update EIP-7892: use valid yaml for consensus config
  EIPS/eip-7892.md
Labels: c-update, t-informational, s-draft

#9620 Update EIP-7918: Anderselowsson patch 7
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9617 Update EIP-7701: Minor fixes
  EIPS/eip-7701.md
Labels: c-update, t-core, s-draft

#9622 Update EIP-7907: update initcode limit in EIP 7907
  EIPS/eip-7907.md
Labels: c-update, t-core, s-draft

#9237 Update EIP-7642: Move to Draft
  EIPS/eip-7642.md
Labels: c-status, t-networking, a-review, s-draft

#9581 Update EIP-3540: Make container section size 4 bytes wide
  EIPS/eip-3540.md
Labels: c-update, t-core, s-review

#9627 Update EIP-7702: reduce line width to 80 char
  EIPS/eip-7702.md
Labels: c-update, t-core

#9601 Update EIP-5792: Add errors and update atomicity capability
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-review

#9630 Update EIP-5792: Add Adam & Phil as coauthors
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-review

#9634 Update EIP-7923: update a typo in the gas schedule
  EIPS/eip-7923.md
Labels: c-update, t-core, s-draft

#9565 Update EIP-7916: Address review feedback
  EIPS/eip-7916.md
Labels: c-update, t-core, a-review, s-draft

#9640 Update EIP-7549: Update p2p gossip section
  EIPS/eip-7549.md
Labels: c-update, t-core

#9643 Update EIP-7495: Define interaction with EIP-7916 `ProgressiveList`
  EIPS/eip-7495.md
  EIPS/eip-7688.md
  EIPS/eip-7916.md
Labels: c-status, c-update, t-core, s-draft

#9645 Update EIP-7883: Add reference implementation
  EIPS/eip-7883.md
Labels: c-update, t-core, s-draft

#9611 Update EIP-5920: Move to Review
  EIPS/eip-5920.md
Labels: c-status, t-core, a-review, s-review

#9625 Update EIP-3607: Fix typo
  EIPS/eip-3607.md
Labels: c-update, t-core, w-ci, s-final, e-consensus

#9517 Update EIP-7045: fix typos
  EIPS/eip-7045.md
Labels: c-update, t-core, s-final, e-consensus

#9550 Update EIP-6953: Update Historical Boundary Definitions
  EIPS/eip-6953.md
Labels: c-update, t-informational, s-final, e-consensus

#9614 Update EIP-3860: Update eip-3860.md
  EIPS/eip-3860.md
Labels: c-update, t-core, s-final, e-consensus

#9639 Update EIP-7577: typo fix
  EIPS/eip-7577.md
Labels: c-update, t-meta, a-review, s-stagnant

#9656 Update EIP-5450: Simplify stack overflow checks
  EIPS/eip-5450.md
Labels: c-update, t-core, s-review

#9626 Update EIP-7600: Move to Last Call
  EIPS/eip-7600.md
  EIPS/eip-7642.md
Labels: c-status, c-update, t-meta, t-networking, a-review

#9557 Update EIP-7692: add eof-devnet-2 EIPs
  EIPS/eip-7692.md
Labels: c-update, t-meta, s-review

#9650 Update EIP-5792: atomicBatch --> atomic
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-review

#9647 Update EIP-7701: Make pseudocode more compact; specify new opcodes gas prices
  EIPS/eip-7701.md
Labels: c-update, t-core, s-draft

#9661 Update EIP-4444: Update eip-4444.md
  EIPS/eip-4444.md
Labels: c-update, t-networking, w-ci, a-review, s-stagnant

#9655 Update EIP-7620: Fix failed copy-paste
  EIPS/eip-7620.md
Labels: c-update, t-core, s-review

#9572 Add EIP: History Expiry Meta
  EIPS/eip-7927.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#9664 Update EIP-7607: update Fusaka CFI and SFI list
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9659 Update EIP-7495: fix duplicate eip-7495.md
  EIPS/eip-7495.md
Labels: c-update, t-core, a-review, s-draft

#9684 Update EIP-7748: address special case of eip-7610 accounts
  EIPS/eip-7748.md
Labels: c-update, t-core, s-draft

#9680 Update EIP-7907: add hyperlinks
  EIPS/eip-7907.md
Labels: c-update, t-core, a-review, s-draft

#9682 Update EIP-2935: Fix Ring Buffer Size in Description
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review

#9689 Update EIP-7873: Clarify InitcodeTransaction calldata cost calculation
  EIPS/eip-7873.md
Labels: c-update, t-core, s-review

#9690 Update EIP-7927: EIP 7927 - remove leftover TODO item
  EIPS/eip-7927.md
Labels: c-update, t-meta, s-draft

#9628 Update EIP-7702: refactor for better readability
  EIPS/eip-7702.md
Labels: c-update, t-core

#9662 Update EIP-3540: Claify, improve and fill missing sections of EOF EIPs
  EIPS/eip-3540.md
  EIPS/eip-4200.md
  EIPS/eip-4750.md
  EIPS/eip-5450.md
  EIPS/eip-6206.md
  EIPS/eip-663.md
  EIPS/eip-7069.md
  EIPS/eip-7480.md
  EIPS/eip-7620.md
Labels: c-update, t-core, a-review, s-review

#9501 Add EIP: Pragmatic stack manipulation tools
  EIPS/eip-7912.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9703 Update EIP-7607: Remove EOF from Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9698 Add EIP: Exponential Gas Limit Increase
  EIPS/eip-7938.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#9695 Update EIP-7748: refactor eip7610 account handling code
  EIPS/eip-7748.md
Labels: c-update, t-core, s-draft

#9687 Add EIP: 64-bit mode EVM opcodes (EVM64)
  EIPS/eip-7937.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9668 Update EIP-2539: fix duplicate eip-2539.md
  EIPS/eip-2539.md
Labels: c-update, t-core, a-review, s-stagnant

#9701 Add EIP: Count leading zeros (CLZ) opcode
  EIPS/eip-7939.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9707 Update EIP-7939: fix typo in code comment
  EIPS/eip-7939.md
Labels: c-update, t-core, s-draft

#9710 Update EIP-7702: Remove trie concept from the vm specification
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review

#9704 Add EIP: Ethereum Shah
  EIPS/eip-7940.md
  assets/eip-7940/acd_leader.jpeg
Labels: c-new, t-informational, e-review, s-draft, e-consensus
