Repository ethereum/EIPs, pull requests merged in 2025-07, with the labels that each got.

#9960 Update EIP-7688: Adopt `ProgressiveContainer` / `ProgressiveList`
  EIPS/eip-7688.md
Labels: c-update, t-core, s-draft

#9966 Update EIP-6466: Adopt `ProgressiveContainer`
  EIPS/eip-6466.md
Labels: c-update, t-core, s-draft

#9957 Update EIP-7607: ACDE#214 changes
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9973 Update EIP-7907: add lightclient and rakita to authors list
  EIPS/eip-7907.md
Labels: c-update, t-core, s-draft

#9974 Update EIP-6465: Adopt `ProgressiveContainer` / `ProgressiveList`
  EIPS/eip-6404.md
  EIPS/eip-6465.md
Labels: c-update, t-core, s-draft

#9976 Update EIP-7807: Adopt `ProgressiveContainer`
  EIPS/eip-7807.md
Labels: c-update, t-core, s-draft

#9955 Update EIP-7907: Account for large contracts as tx entry point
  EIPS/eip-7907.md
Labels: c-update, t-core, a-review, s-draft

#9979 Update EIP-7918: finalize BLOB_BASE_COST
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9978 Update EIP-7951: update gas costs for R1 verification
  EIPS/eip-7951.md
Labels: c-update, t-core, a-review, s-draft

#9987 Update EIP-7939: Change gas cost from 3 to 5
  EIPS/eip-7939.md
Labels: c-update, t-core, a-review, s-draft

#9910 Update EIP-7907: Reduce code limit, increase cost per word, fix `EXTCODESIZE` issue
  EIPS/eip-7907.md
Labels: c-update, t-core, s-draft

#9989 Update EIP-7910: Add Fork Id to response, spec BPOs, add "last"
  EIPS/eip-7910.md
Labels: c-update, t-interface, a-review, s-draft

#9708 Add EIP: Available Attestation
  EIPS/eip-7942.md
  assets/eip-7942/available-attestation-paper.pdf
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9986 Update EIP-7825: Move to Draft
  EIPS/eip-7825.md
Labels: c-status, t-core, a-review, s-draft

#9927 Update EIP-2926: Move to Draft
  EIPS/eip-2926.md
Labels: c-status, t-core, a-review, s-draft

#10005 Update EIP-7883: Fix typo in pricing of one test case
  EIPS/eip-7883.md
Labels: c-update, t-core, s-draft

#9492 Update EIP-7657: Bump links to tagged beta spec version
  EIPS/eip-7657.md
Labels: c-update, t-core, a-review, s-stagnant

#10008 Update EIP-7495: fix typos and link formatting
  EIPS/eip-7495.md
Labels: c-update, t-core, a-review, s-draft

#10016 Update EIP-7916: Move reference implementation to ethereum/remerkleable
  EIPS/eip-7916.md
  assets/eip-7916/progressive.py
  assets/eip-7916/remerkleable.patch
  assets/eip-7916/tests.patch
Labels: c-update, t-core, s-draft

#10019 Update EIP-7919: Minimize scope
  EIPS/eip-7919.md
Labels: c-update, t-meta, s-draft

#10003 Update EIP-7949: Fix typos and formatting
  EIPS/eip-7949.md
Labels: c-update, t-informational, a-review, s-draft

#10021 Update EIP-7819: Update/eip 7819
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#10027 Update EIP-7819: Add location to accessed_addresses
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#10033 Update EIP-7819: Update EIP-7819
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#10039 Update EIP-7910: Revise sample hash
  EIPS/eip-7910.md
Labels: c-update, t-interface, a-review, s-draft

#10025 Update EIP-7939: Move to Review
  EIPS/eip-7939.md
Labels: c-status, t-core, e-review, s-review

#10018 Update EIP-3026: fix typos and improve clarity
  EIPS/eip-3026.md
Labels: c-update, t-core, a-review, s-stagnant

#9934 Update EIP-1108: fixed dead link
  EIPS/eip-1108.md
Labels: c-update, t-core, s-final, e-consensus

#9964 Update EIP-8: typo in reason=reasons.incompatibel_p2p_version
  EIPS/eip-8.md
Labels: c-update, t-networking, w-ci, s-final, e-consensus

#9947 Update EIP-7642: Corrected Spelling and Grammar
  EIPS/eip-7642.md
Labels: c-update, t-networking, s-final, e-consensus

#10034 Update EIP-7736: fix typo in check_epoch_end pseudocode
  EIPS/eip-7736.md
Labels: c-update, t-core, a-review, s-stagnant

#9577 Update EIP-2935: Move to Final
  EIPS/eip-2935.md
  EIPS/eip-3540.md
Labels: c-update, t-core, a-review, s-review, s-final

#10051 Update EIP-7910: fix missing 0 in nextHash example
  EIPS/eip-7910.md
Labels: c-update, t-interface, a-review, s-draft

#10052 Update EIP-7910: require addresses and forkids to be in lowecase hex.
  EIPS/eip-7910.md
Labels: c-update, t-interface, s-draft

#10053 Update EIP-7819: Update EIP-7819
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#10055 Update EIP-7966: add client-configured timeout and improve specs
  EIPS/eip-7966.md
Labels: c-update, t-interface, s-draft

#10024 Update EIP-7773: Add EIP-7819 to Glamsterdam's PFI
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#9963 Website: Add missing favicon
  _includes/head.html
  assets/images/favicon.png
Labels: e-consensus

#10068 Update EIP-7960: fix typo in "concise"
  EIPS/eip-7960.md
Labels: c-update, t-core, a-review, s-draft

#10071 Update EIP-7916: Indicate absence of limit explicitly
  EIPS/eip-7916.md
Labels: c-update, t-core, s-draft

#10066 Update EIP-2926: use 31-byte chunk size instead
  EIPS/eip-2926.md
Labels: c-update, t-core, a-review, s-draft

#10079 Update EIP-7910: Fix sorted json
  EIPS/eip-7910.md
Labels: c-update, t-interface, a-review, s-draft

#10082 Update EIP-7928: add system contract logic
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft
