Repository ethereum/EIPs, pull requests merged in 2025-05, with the labels that each got.

#9706 Update EIP-7819: Update EIP-7819
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#9715 Update EIP-7907: 256KB and 512KB hex values
  EIPS/eip-7907.md
Labels: c-update, t-core, a-review, s-draft

#9678 Add gas limit increase EIP
  eip-7935.md
Labels: c-new, t-informational, s-draft, e-consensus

#9724 Update EIP-7912: fix typo, add optimization
  EIPS/eip-7912.md
Labels: c-update, t-core, s-draft

#9528 Update EIP-7607: Add "Pragmatic expansion of stack manipulation tools" as DFI for Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9537 Update EIP-7762: correct spelling errors in EIP-7762
  EIPS/eip-7762.md
Labels: c-update, t-core, a-review, s-review

#9658 Add EIP: RLP Execution Block Size Limit
  EIPS/eip-7934.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9685 Update EIP-6916: Move to Final
  EIPS/eip-6916.md
Labels: c-status, t-core, e-review, s-final

#9670 Update EIP-3220: Correct wording in blockchain identifier documentation
  EIPS/eip-3220.md
Labels: c-update, t-core, a-review, s-stagnant

#9580 Add EIP: Block-Level Access Lists
  EIPS/eip-7928.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9722 Update EIP-5792: Update CAIP-25 links in eip-5792.md to newest commit
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review

#9725 Update EIP-7702: more nits
  EIPS/eip-7702.md
Labels: c-update, t-core

#9726 Update EIP-7600: Update eip-7600.md
  EIPS/eip-7600.md
Labels: c-update, t-meta, a-review

#9727 Update EIP-5792: Typo fix in CAIP-25 sentence of eip-5792.md
  EIPS/eip-5792.md
Labels: c-update, t-interface, a-review

#9728 Update EIP-7892: Consensus Config Format
  EIPS/eip-7892.md
Labels: c-update, t-informational, s-draft

#9730 Add EIP: Set default gas limit to XX0M
  EIPS/eip-7935.md
Labels: e-review, e-consensus

#9731 Update EIP-7918: Update eip-7918.md
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9732 Update EIP-7918: Added empirical analysis
  EIPS/eip-7918.md
  assets/eip-7918/3.png
  assets/eip-7918/4.png
  assets/eip-7918/5.png
Labels: c-update, t-core, s-review

#9735 Update EIP-5792: fix trivial type mismatch
  EIPS/eip-5792.md
Labels: c-update, t-interface

#9736 Update EIP-7918: Minor adjustments to the text for clarity.
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9734 Update EIP-7701: Removing dependency on EOF (#21)
  EIPS/eip-7701.md
  assets/eip-7701/complete_flow.md
  assets/eip-7701/complete_flow.svg
  assets/eip-7701/legacy_eof_7701_comparison.svg
  assets/eip-7701/simple_flow.md
  assets/eip-7701/simple_flow.svg
  assets/eip-7701/simple_flow_legacy_proxy.md
  assets/eip-7701/simple_flow_legacy_proxy.svg
Labels: c-update, t-core, w-ci, s-draft

#9737 Update EIP-5792: add bumblefudge as coauthor
  EIPS/eip-5792.md
Labels: c-update, t-interface

#9739 Update EIP-5792: Remove 7702 reference
  EIPS/eip-5792.md
Labels: c-update, t-interface

#9744 Update EIP-7607: Add ACDE#211 SFI & CFI'd EIPs
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9745 Update EIP-7701: Replace 'n' with 'txparam_id' in the table
  EIPS/eip-7701.md
Labels: c-update, t-core, s-draft

#9755 Update EIP-7701: Fix the discussions link
  EIPS/eip-7701.md
Labels: c-update, t-core, s-draft

#9756 Update EIP-7886: Move from "coinbase fronting" to "payload reversion" mechanism
  EIPS/eip-7886.md
Labels: c-update, t-core, s-draft

#9758 Update EIP-7886: polish eip rational
  EIPS/eip-7886.md
Labels: c-update, t-core, s-draft

#9738 Update EIP-5792: Move to Final
  EIPS/eip-5792.md
Labels: c-status, t-interface, e-review, s-final

#9759 Update EIP-7918: Add author
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9760 Update EIP-7918: Added author
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9763 Update EIP-7702: correct minor typos.
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review

#9764 Update EIP-7939: Strengthen motivation with SP1 optimized example, update authors
  EIPS/eip-7939.md
Labels: c-update, t-core, s-draft

#9765 Update EIP-7702: Fixing minor typos
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review

#9766 Update EIP-4444: Fix typos in EIP-4444
  EIPS/eip-4444.md
Labels: c-update, t-networking, w-ci, a-review, s-stagnant

#9633 Add EIP: Algorithmic Transaction Wrapper
  EIPS/eip-7932.md
  assets/eip-7932/template-eip.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9770 Update EIP-5792: fix typo
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-final, e-consensus

#9590 Update EIP-5920: add status stack return item / improve gas schedule
  EIPS/eip-5920.md
Labels: c-update, t-core, a-review, s-review

#9768 Update EIP-7002: fix variable name typo in withdrawal requests dequeue function
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review

#9772 Update EIP-7607: Update eip-7607.md
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9775 Update EIP-7702: Clarify read ops
  EIPS/eip-7702.md
Labels: c-update, t-core

#9762 Update EIP-7793: Change TXINDEX to ASSERTTXINDEX
  EIPS/eip-7793.md
Labels: c-update, t-core, s-draft

#9752 Update EIP-7691: Move to Final
  EIPS/eip-7691.md
Labels: c-status, t-core, a-review, s-final

#9749 Update EIP-7549: Move to Final
  EIPS/eip-7549.md
Labels: c-status, t-core, a-review, s-final

#9751 Update EIP-7685: Move to Final
  EIPS/eip-7685.md
Labels: c-status, t-core, a-review, s-final

#9746 Update EIP-6110: Move to Final
  EIPS/eip-6110.md
Labels: c-status, t-core, a-review, s-final

#9742 Update EIP-2935: Move to Final
  EIPS/eip-2935.md
Labels: c-status, t-core, a-review, s-final

#9754 Update EIP-7840: Move to Final
  EIPS/eip-7840.md
Labels: c-status, t-informational, a-review, s-final

#9748 Update EIP-7251: Move to Final
  EIPS/eip-7251.md
Labels: c-status, t-core, w-ci, a-review, s-final

#9487 Update EIP-1: eip-1.md add missing symb
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#9784 Update EIP-6110: ensure ints are decoded as uints
  EIPS/eip-6110.md
Labels: c-update, t-core, s-final, e-consensus

#9179 typo-Update SalaryWithDAO.sol
  assets/eip-3267/contracts/SalaryWithDAO.sol
Labels: e-consensus

#9761 Update EIP-7843: change to opcode
  EIPS/eip-7843.md
Labels: c-update, t-core, s-draft

#9800 Update EIP-7907: warm cold table with gas cost and scenarios
  EIPS/eip-7907.md
Labels: c-update, t-core, a-review, s-draft

#9803 Update EIP-7607: Fix Fusaka SFI Changes
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9805 Update EIP-7607: ACDE#212 Changes
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9820 Update EIP-7937: Split EOF support specifications
  EIPS/eip-7937.md
Labels: c-update, t-core, s-draft

#9824 Update EIP-7918: Updated text and figures to reflect new specification
  EIPS/eip-7918.md
  assets/eip-7918/1.png
  assets/eip-7918/2.png
  assets/eip-7918/3.png
  assets/eip-7918/4.png
  assets/eip-7918/5.png
Labels: c-update, t-core, s-review

#9825 Update EIP-7701: Fix incorrect location of 'snapshot' in pseudocode
  EIPS/eip-7701.md
Labels: c-update, t-core, s-draft

#9826 Update EIP-2935: link execution spec tests
  EIPS/eip-2935.md
Labels: c-update, t-core, s-final

#9827 Update EIP-7918: Fixed math display
  EIPS/eip-7918.md
Labels: c-update, t-core, s-review

#9631 Update EIP-7636: Modify author to reflect recent github account renaming
  EIPS/eip-7636.md
Labels: c-update, t-networking, s-final, e-consensus

#9787 Update EIP-225: fix typos
  EIPS/eip-225.md
  EIPS/eip-627.md
Labels: c-update, t-core, t-networking, w-ci, s-final, e-consensus

#9448 Website: Spelling issue
  _includes/head.html
Labels: e-consensus

#9799 Update EIP-7782: Move to Draft
  EIPS/eip-7782.md
Labels: c-status, t-core, e-review, s-draft

#9807 Update EIP-7907: add strong devex motivation examples
  EIPS/eip-7907.md
Labels: c-update, t-core, a-review, s-draft
