Repository ethereum/EIPs, pull requests merged in 2025-10, with the labels that each got.

#8190 Add EIP: Precompile Falcon512 generic verifier
  EIPS/eip-7619.md
  assets/eip-7619/bench_vectors.md
  assets/eip-7619/benchmark_results.md
  assets/eip-7619/invalid_signature_test_vectors.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#10462 Update EIP-7870: Move to Living
  EIPS/eip-7870.md
Labels: c-status, t-informational, e-review

#10391 Update EIP-7723: Include primary point of contact in proposal
  EIPS/eip-7723.md
Labels: c-update, t-meta, a-review

#10463 Update EIP-2711: fix minor typos
  EIPS/eip-2711.md
Labels: c-update, t-core, w-ci, s-withdrawn, e-consensus

#10469 Update EIP-7979: Update eip-7979.md
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10470 Update EIP-7979: Update eip-7979.md
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10471 Update EIP-7928: Clarify EIP 7702
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10483 Update EIP-7807: Fix ProgressiveContainer syntax in GasAmounts
  EIPS/eip-7807.md
Labels: c-update, t-core, a-review, s-draft

#10421 Update EIP-7910: Move to Last Call
  EIPS/eip-7910.md
Labels: c-status, t-interface, w-ci, a-review

#10486 Add EIP: State Creation Gas Cost Increase
  EIPS/eip-8037.md
  assets/eip-8011/multidim_empirical_analysis.md
  assets/eip-8011/plot_1.png
  assets/eip-8011/plot_2.png
  assets/eip-8011/plot_3.png
  assets/eip-8011/plot_4.png
  assets/eip-8011/plot_5.png
  assets/eip-8037/new_state_added.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#10094 Update EIP-1108: correct typo in EIP-1108 rationale section
  EIPS/eip-1108.md
Labels: c-update, t-core, s-final, e-consensus

#10136 Update EIP-7702: Correct link formatting
  EIPS/eip-7702.md
Labels: c-update, t-core, s-final, e-consensus

#10091 Update EIP-684: typo
  EIPS/eip-684.md
Labels: c-update, t-core, s-final, e-consensus

#10312 Update EIP-908: Fix typo
  EIPS/eip-908.md
Labels: c-update, t-core, w-ci, s-withdrawn, e-consensus

#10491 Update EIP-5003: Move to Withdrawn
  EIPS/eip-5003.md
Labels: c-status, t-core, s-withdrawn

#10492 Update EIP-7805: reflect the latest engine APIs spec change
  EIPS/eip-7805.md
Labels: c-update, t-core, a-review, s-draft

#10373 Add EIP: P256 transaction support
  EIPS/eip-8030.md
Labels: c-new, t-core, e-review, a-review, s-draft, e-consensus

#10466 Update EIP-1: Update eip-1.md
  EIPS/eip-1.md
Labels: c-update, t-process, e-consensus

#10495 Update EIP-8007: Update EIP-8007
  EIPS/eip-8007.md
Labels: c-update, t-meta, s-draft
