Repository ethereum/EIPs, pull requests merged in 2025-08, with the labels that each got.

#10076 Update EIP-7937: fix typo in test cases section
  EIPS/eip-7937.md
Labels: c-update, t-core, a-review, s-draft

#10116 Update EIP-7862: Add Exec Specs
  EIPS/eip-7862.md
Labels: c-update, t-core, s-draft

#10122 Update EIP-7932: Move to Draft
  EIPS/eip-7932.md
  assets/eip-7932/template-eip.md
  assets/eip-7932/test-cases.md
  assets/eip-7932/test_cases/additional_info.json
  assets/eip-7932/test_cases/generate_test_cases.py
  assets/eip-7932/test_cases/precompile.json
  assets/eip-7932/test_cases/transactions.json
Labels: c-status, c-update, t-core, w-ci, s-draft

#9940 Add EIP: Ed25519 transaction support
  EIPS/eip-7980.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#10077 Update EIP-1702: fix typos
  EIPS/eip-1702.md
  EIPS/eip-7957.md
Labels: c-update, t-core, a-review, s-draft, s-stagnant

#10047 Update EIP-1571: fix typo
  EIPS/eip-1571.md
Labels: c-update, t-interface, a-review, s-stagnant

#10125 Update EIP-7956: Update eip-7956.md
  EIPS/eip-7956.md
Labels: c-update, t-core, s-draft

#10127 Update EIP-7883: Add empirical analysis
  EIPS/eip-7883.md
  assets/eip-7883/call_analysis.md
  assets/eip-7883/entity_analysis.md
Labels: c-update, t-core, a-review, s-draft

#10130 Update EIP-7928: Fix mistake in tx_index of system contracts
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10137 Update EIP-7732: update to latest CL-spec version
  EIPS/eip-7732.md
Labels: c-update, t-core, s-draft

#10144 Update EIP-7928: Update System Contract Handling
  EIPS/eip-7928.md
Labels: c-update, t-core, w-ci, s-draft

#10075 Update EIP-7773: propose eip 2926 for inclusion in Glamsterdam
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#10149 Update EIP-7918: Clarified that the current block's blobSchedule is used during proces…
  EIPS/eip-7918.md
Labels: c-update, t-core, w-ci, s-review

#10151 Update EIP-7918: Improved clarity in the Motivation, Specification, and Rationale, and updated Figure 1
  EIPS/eip-7918.md
  assets/eip-7918/1.png
Labels: c-update, t-core, s-review

#10155 Update EIP-7918: Updated Figures 2-5 to reflect BLOB_BASE_COST=2**13 and adjusted the rationale to improve clarity
  EIPS/eip-7918.md
  assets/eip-7918/2.png
  assets/eip-7918/3.png
  assets/eip-7918/4.png
  assets/eip-7918/5.png
Labels: c-update, t-core, s-review

#10157 Update EIP-7979: mostly formatting
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10161 Update EIP-7928: Update system contract handling and move from ssz to rlp
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10166 Update EIP-7979: formatting, links, and nits
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10186 Update EIP-7979: simplify calling covention
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10088 Update EIP-1051: fix typo
  EIPS/eip-1051.md
Labels: c-update, t-core, w-ci, e-review, s-stagnant

#10065 Update EIP-7966: remove client-configured timeout validation and change error code
  EIPS/eip-7966.md
Labels: c-update, t-interface, s-draft

#10108 Update EIP-7898: fix typo
  EIPS/eip-7898.md
Labels: c-update, t-core, a-review, s-draft

#10092 Add EIP: Deterministic Factory Predeploy
  EIPS/eip-7997.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#10196 Update EIP-7932: Rewrite for readability and some minor changes to improve clarity in logic
  EIPS/eip-7932.md
Labels: c-update, t-core, s-draft

#10195 Update EIP-7807: correct grammar in Engine API section
  EIPS/eip-7807.md
Labels: c-update, t-core, a-review, s-draft

#10126 Update EIP-7773: Propose EIP-7997 for inclusion
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#10209 Update EIP-7928: Make specification section clearer with dedicated sections.
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10213 Update EIP-7917: fix off-by-one error
  EIPS/eip-7917.md
Labels: c-update, t-core, a-review, s-draft

#10215 Update EIP-7917: Update URLs and reflect changes in helper function
  EIPS/eip-7917.md
Labels: c-update, t-core, s-draft

#10225 Update EIP-7981: Add EELS spec implementation
  EIPS/eip-7981.md
Labels: c-update, t-core, w-ci, s-draft

#10197 Update EIP-7773: Call and Return Opcodes for the EVM
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#10058 Update EIP-7773: `Gloas/Amsterdam` → `Glamsterdam`
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#10191 Update EIP-7607: Update eip-7607.md
  EIPS/eip-7607.md
Labels: c-update, t-meta, w-ci, a-review, s-draft

#10230 Update EIP-7773: Add EIPs 7981, 7999, 7932 and 7980 to PFI
  EIPS/eip-7773.md
Labels: c-update, t-meta, s-draft

#10233 Update EIP-7495: Mix-in selector for CompatibleUnion
  EIPS/eip-7495.md
Labels: c-update, t-core, s-draft

#10242 Update EIP-7997: Improve Abstract, Motivation, and Specification
  EIPS/eip-7997.md
Labels: c-update, t-core, s-draft

#10247 Update EIP-7932: Change from keccak to hash_tree_root
  EIPS/eip-7932.md
Labels: c-update, t-core, s-draft
