Repository ethereum/EIPs, pull requests merged in 2025-06, with the labels that each got.

#9846 Update EIP-7863: Update EIP-7863 and EIP-7928 with small changes
  EIPS/eip-7863.md
  EIPS/eip-7928.md
Labels: c-update, t-core, w-ci, s-draft

#9381 Update EIP-7805: expand on EL changes
  EIPS/eip-7805.md
Labels: c-update, t-core, w-ci, a-review, s-draft

#9848 Update EIP-7928: convert contract code field from union type to list of bytes
  EIPS/eip-7928.md
Labels: c-update, t-core, a-review, s-draft

#9753 Update EIP-7702: Move to Final
  EIPS/eip-7702.md
Labels: c-status, t-core, a-review, s-final

#9859 Update EIP-7917: Change proposer_lookahead type from List to Vector
  EIPS/eip-7917.md
Labels: c-update, t-core, s-draft

#9865 Update EIP-7928: Code change
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#9740 Update EIP-7600: Move to Final
  EIPS/eip-7600.md
Labels: c-status, t-meta, e-review, s-final

#9814 Update EIP-2935: Update eip-2935.md
  EIPS/eip-2935.md
Labels: c-update, t-core, s-final, e-consensus

#9801 Add EIP: Genesis File Format
  EIPS/eip-7949.md
Labels: c-new, t-informational, e-review, s-draft, e-consensus

#9876 Update EIP-7939: Update EIP-7939
  EIPS/eip-7939.md
Labels: c-update, t-core, s-draft

#9871 Update EIP-7928: make explicit that the BAL is its own field in the block, remove SSZ encoding as a requirement for BAL verification
  EIPS/eip-7928.md
Labels: c-update, t-core, a-review, s-draft

#9885 Update EIP-7928: add header field for bal hash to block
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#9888 Update EIP-7934: Bump safety margin to 2MiB.
  EIPS/eip-7934.md
Labels: c-update, t-core, a-review, s-draft

#9855 Update EIP-7883: Assume minimal base/mod length of 32
  EIPS/eip-7883.md
Labels: c-update, t-core, a-review, s-draft

#9893 Update EIP-7928: inconsistencies in SSZ structures
  EIPS/eip-7928.md
Labels: c-update, t-core, a-review, s-draft

#9623 Update EIP-7892: Add blob count per tx limit via blobSchedule
  EIPS/eip-7892.md
Labels: c-update, t-informational, a-review, s-draft

#9898 Update EIP-7804: Minor Typographical and Clarity Improvements in EIP-7804
  EIPS/eip-7804.md
Labels: c-update, t-core, a-review, s-draft

#9897 Update EIP-7886: Change Design
  EIPS/eip-7886.md
Labels: c-update, t-core, s-draft

#9907 Update EIP-7934: Set MAX_RECEIPTS_MESSAGE_SIZE for GetReceipts in devp2p
  EIPS/eip-7934.md
Labels: c-update, t-core, e-review, s-draft, e-consensus

#9648 Update EIP-5081: fix typos
  EIPS/eip-5081.md
  EIPS/eip-7199.md
Labels: c-update, t-core, t-meta, s-withdrawn, s-stagnant, e-consensus

#9629 docs: fix typos in complexity analysis section
  assets/eip-7549/complexity_analysis.md
Labels: e-consensus

#9908 Update EIP-7937: Fix Typos and Improve Clarity in EIP-7937 Specification
  EIPS/eip-7937.md
Labels: c-update, t-core, a-review, s-draft

#9918 Update EIP-7928: specify nonce diffs as post-tx nonces for contract accounts which modified their nonce
  EIPS/eip-7928.md
Labels: c-update, t-core, a-review, s-draft

#9919 Update EIP-7932: Remove redundant section
  EIPS/eip-7932.md
Labels: c-update, t-core, s-review

#9920 Update EIP-7932: Fix critical issue with additional_info
  EIPS/eip-7932.md
Labels: c-update, t-core, s-review

#9921 Update EIP-7932: Update test cases to match changes made to EIP
  EIPS/eip-7932.md
  assets/eip-7932/test_cases/additional_info.json
  assets/eip-7932/test_cases/generate_test_cases.py
  assets/eip-7932/test_cases/transactions.json
Labels: c-update, t-core, s-review

#9916 Update EIP-7898: Fix typos in EIP-7898
  EIPS/eip-7898.md
Labels: c-update, t-core, a-review, s-draft

#9813 Add EIP: Tx Ordering via Block-level Randomness
  EIPS/eip-7956.md
Labels: c-new, t-core, w-ci, e-review, s-draft, e-consensus

#9886 Update README.md
  assets/eip-7701/README.md
Labels: e-consensus

#9882 Update EIP-7950: Move to Review
  EIPS/eip-7950.md
Labels: c-status, t-interface, e-review, s-review

#9878 Update EIP-1186: Fix broken Merkle Tree link in EIP-1186 abstract
  EIPS/eip-1186.md
Labels: c-update, t-interface, w-ci, e-review, s-stagnant

#9924 Update EIP-7928: Fix BAL type definition
  EIPS/eip-7928.md
Labels: c-update, t-core, a-review, s-draft

#9909 Add EIP: Further increase calldata cost
  EIPS/eip-7976.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9938 Update EIP-7749: fix typo in verifier address description
  EIPS/eip-7749.md
Labels: c-update, t-interface, a-review, s-draft

#9913 Website: Fix discord badge images
  index.html
Labels: e-consensus

#9945 Update EIP-7805: Use `MAX_TRANSACTIONS_PER_PAYLOAD` for the max length of IL transactions
  EIPS/eip-7805.md
Labels: c-update, t-core, a-review, s-draft

#9906 Add EIP: eth/70 - partial block receipt lists
  EIPS/eip-7975.md
Labels: c-new, t-networking, e-review, s-draft, e-consensus

#9948 Update EIP-7928: Add assets folder with analysis
  EIPS/eip-7928.md
  assets/eip-7928/bal_size_analysis.md
Labels: c-update, t-core, s-draft
