Repository ethereum/EIPs, pull requests merged in 2025-02, with the labels that each got.

#9316 Update EIP-6110: Polish and actualise
  EIPS/eip-6110.md
Labels: c-update, t-core, s-review

#9319 Update EIP-7251: fix outdated statement
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#9322 Update EIP-7600: Add testnet fork times
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-review

#9351 Update EIP-7623: add reference to eip-3860
  EIPS/eip-7623.md
Labels: c-update, t-core, s-review

#9353 Update EIP-6404: Bump links to tagged beta spec version
  EIPS/eip-6404.md
  EIPS/eip-6465.md
  EIPS/eip-6466.md
  EIPS/eip-6493.md
  EIPS/eip-7495.md
  EIPS/eip-7688.md
  EIPS/eip-7799.md
  EIPS/eip-7807.md
Labels: c-update, t-core, e-review, s-draft, s-review

#9302 Update EIP-7851: multiple fixes and refinements
  EIPS/eip-7851.md
Labels: c-update, t-core, s-draft

#9355 Update EIP-7702: add rationale around refund mechanism
  EIPS/eip-7702.md
Labels: c-update, t-core, s-review

#9338 Update EIP-7702: Move to Last Call
  EIPS/eip-7702.md
Labels: c-status, t-core, a-review

#9336 Update EIP-2935: Move to Last Call
  EIPS/eip-2935.md
Labels: c-status, t-core, a-review

#8794 Update EIP-7732: fix typos
  EIPS/eip-7732.md
Labels: c-update, t-core, w-stale, a-review, s-draft

#9339 Update EIP-7840: Move to Last Call
  EIPS/eip-7840.md
Labels: c-status, t-informational, a-review

#9334 Update EIP-7723: Move to Last Call
  EIPS/eip-7723.md
Labels: c-status, t-meta, e-review

#9335 Update EIP-2537: Move to Last Call
  EIPS/eip-2537.md
Labels: c-status, t-core, a-review

#9360 Update EIP-7691: Move to Last Call
  EIPS/eip-7691.md
Labels: c-status, t-core, e-review

#9359 Update EIP-7623: Move to Last Call
  EIPS/eip-7623.md
Labels: c-status, t-core, e-review

#9292 Update EIP-7607: Proposing 7805 for fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9303 Update EIP-7783: Add exponential gas limit increase strategy to EIP7783
  EIPS/eip-7783.md
Labels: c-update, t-informational, s-draft

#9315 Add EIP: Enhanced RETURN opcodes
  EIPS/eip-7877.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9361 Update EIP-7600: EL vs. CL EIP lists
  EIPS/eip-7600.md
Labels: c-update, t-meta, s-review

#9346 Update EIP-7843: specification update
  EIPS/eip-7843.md
Labels: c-update, t-core, a-review, s-draft

#9250 Update EIP-7702: Clarify CODE* operations behavior
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review

#9327 Update EIP-7685: Move to Last Call
  EIPS/eip-7685.md
Labels: c-status, t-core, a-review

#9299 Add EIP: EOF - TXCREATE and InitcodeTransaction type
  EIPS/eip-7873.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9328 Update EIP-7002: Move to Last Call
  EIPS/eip-7002.md
  assets/eip-7002/fee_analysis.md
Labels: c-status, t-core, e-review

#9329 Update EIP-7251: Move to Last Call
  EIPS/eip-7251.md
Labels: c-status, t-core, w-ci, e-review

#9317 Update EIP-7549: Move to Last Call
  EIPS/eip-7549.md
  assets/eip-7549/attester_slashing.png
  assets/eip-7549/complexity_analysis.md
  assets/eip-7549/max_attestations.png
  assets/eip-7549/on_chain_aggregates.png
Labels: c-status, t-core, a-review

#9356 Add EIP: ModExp Gas Cost Increase
  EIPS/eip-7883.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9333 Update EIP-7600: Move to Last Call
  EIPS/eip-7600.md
Labels: c-status, t-meta, e-review

#9370 Update EIP-1898: Move to Last Call
  EIPS/eip-1898.md
Labels: c-status, t-interface, w-ci, a-review

#9377 Update EIP-7873: memory expansion of TXCREATE and remove 3860 charge mention
  EIPS/eip-7873.md
Labels: c-update, t-core, s-draft

#9154 Update EIP-7675: Move to Withdrawn
  EIPS/eip-7675.md
Labels: c-status, t-meta, a-review, s-withdrawn

#9387 Update EIP-7783: Add stepwise linear strategy
  EIPS/eip-7783.md
Labels: c-update, t-informational, a-review, s-draft

#9392 Update EIP-7607: Proposing 7825 for Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9324 Update EIP-7607: proposes eth/69 inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9367 Update EIP-7607: propose EIP-7783
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9388 Update EIP-7607: Propose EIP-5920 for inclusion in Osaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9342 Add EIP: EOF - EXTCODEADDRESS instruction
  EIPS/eip-7880.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9352 Update EIP-7607: Update EIP-7606 Add EOF testnet Osaka-2 EIPs.
  EIPS/eip-7607.md
Labels: c-update, t-meta, w-ci, a-review, s-draft

#9385 Update EIP-3540: Move to Review
  EIPS/eip-3540.md
Labels: c-status, t-core, e-review, s-review

#9400 Update EIP-3155: Move to Last Call
  EIPS/eip-3155.md
Labels: c-status, t-interface, e-review

#9296 Add EIP: Max blob flag for local builders
  EIPS/eip-7872.md
Labels: c-new, t-meta, e-review, s-draft, e-consensus

#9376 Add EIP: Delayed execution
  EIPS/eip-7886.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9389 Update EIP-5920: Move to Draft
  EIPS/eip-5920.md
Labels: c-status, t-core, a-review, s-draft

#9131 Update EIP-7703: typos in documentation files
  EIPS/eip-7703.md
Labels: c-update, t-core, a-review, s-draft

#9403 Update EIP-3670: Document BLOCKHASH in EOF
  EIPS/eip-3670.md
Labels: c-update, t-core, s-review

#9189 Update EIP-7819: fix typos
  EIPS/eip-7819.md
Labels: c-update, t-core, a-review, s-draft

#8826 Update EIP-5792: Propose changes to EIP-5792
  EIPS/eip-5792.md
Labels: c-status, t-interface, a-review

#9415 Update EIP-7864: Finalize hash function selection to Poseidon2
  EIPS/eip-7864.md
Labels: c-update, t-core, w-ci, a-review, s-draft

#9424 Update EIP-2537: Update eip-2537.md
  EIPS/eip-2537.md
Labels: c-update, t-core

#9416 Update EIP-5920: PAY Opcode Recipient Address
  EIPS/eip-5920.md
Labels: c-update, t-core, a-review, s-draft
