Repository ethereum/EIPs, pull requests merged in 2025-01, with the labels that each got.

#9216 Update EIP-2537: Update eip-2537 Adjusted pairing costs in the 2nd place
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9180 Website: Update index.html
  index.html
Labels: e-consensus

#9175 Config: Update ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: e-consensus

#9188 Update EIP-7843: calculate slot in CL, improve motivation
  EIPS/eip-7843.md
Labels: c-update, t-core, s-draft

#9221 Update EIP-5792: Add status codes
  EIPS/eip-5792.md
Labels: c-status, t-interface

#9222 Update EIP-5792: Add status codes"
  EIPS/eip-5792.md
Labels: c-update, t-interface, s-review

#9227 Update EIP-7623: Clarify the gas refunds handling
  EIPS/eip-7623.md
Labels: c-update, t-core, a-review, s-review

#9144 Update EIP-2935: bring up to date with sys contract impl
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-review

#9233 Update EIP-7805: maximum inclusion list size is in bytes
  EIPS/eip-7805.md
Labels: c-update, t-core, a-review, s-draft

#9234 Update EIP-7851: multiple fixes and refinements
  EIPS/eip-7851.md
Labels: c-update, t-core, s-draft

#9225 Update EIP-7723: Add non-Core EIPs
  EIPS/eip-7723.md
Labels: c-update, t-meta, s-review

#9124 Update EIP-4762: clarify change in behaviour for CALLCODE cost if value transfer
  EIPS/eip-4762.md
Labels: c-update, t-core, a-review, s-draft

#9238 Update EIP-4762: Fix references to CALLCODE and wording around its value-transfer costs
  EIPS/eip-4762.md
Labels: c-update, t-core, a-review, s-draft

#9239 Update EIP-7549: Move to Review
  EIPS/eip-7549.md
Labels: c-status, t-core, e-review, s-review

#9235 Update EIP-7519: Move to Draft
  EIPS/eip-7519.md
  EIPS/eip-7692.md
Labels: c-status, t-core, t-meta, e-review, s-draft, s-review

#9242 Update EIP-2537: Align gas cost in `Constants` section with `Gas schedule` section.
  EIPS/eip-2537.md
Labels: c-update, t-core, a-review, s-review

#9226 Update EIP-7045: Update EIP-7045
  EIPS/eip-7045.md
Labels: c-update, t-core, s-final, e-consensus

#9223 Update EIP-7840: Move to Review
  EIPS/eip-7840.md
Labels: c-status, t-informational, a-review, s-review

#9164 Update EIP-7600: Add EIP-7840
  EIPS/eip-7600.md
Labels: c-update, t-meta, w-ci, s-review

#9186 Update EIP-1485: Fix typographical errors in Documentation
  EIPS/eip-1485.md
  EIPS/eip-158.md
  EIPS/eip-1884.md
  EIPS/eip-1959.md
  EIPS/eip-2294.md
  EIPS/eip-234.md
  EIPS/eip-2474.md
  EIPS/eip-747.md
  EIPS/eip-7808.md
Labels: c-update, t-core, t-informational, t-interface, t-meta, w-ci, s-review, s-final, s-stagnant, e-consensus

#9217 EIP-2537: Update test files to latest gas schedule
  assets/eip-2537/add_G1_bls.json
  assets/eip-2537/add_G2_bls.json
  assets/eip-2537/fail-add_G1_bls.json
  assets/eip-2537/fail-add_G2_bls.json
  assets/eip-2537/fail-map_fp2_to_G2_bls.json
  assets/eip-2537/fail-map_fp_to_G1_bls.json
  assets/eip-2537/fail-mul_G1_bls.json
  assets/eip-2537/fail-mul_G2_bls.json
  assets/eip-2537/fail-multiexp_G1_bls.json
  assets/eip-2537/fail-multiexp_G2_bls.json
  assets/eip-2537/fail-pairing_check_bls.json
  assets/eip-2537/map_fp2_to_G2_bls.json
  assets/eip-2537/map_fp_to_G1_bls.json
  assets/eip-2537/mul_G1_bls.json
  assets/eip-2537/mul_G2_bls.json
  assets/eip-2537/multiexp_G1_bls.json
  assets/eip-2537/multiexp_G2_bls.json
  assets/eip-2537/pairing_check_bls.json
  assets/eip-2537/test-vectors.md
Labels: e-consensus

#9257 Add EIP: Ethereum state using a unified binary tree
  EIPS/eip-7864.md
  assets/eip-7864/diagram1.png
  assets/eip-7864/diagram2.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9252 Update EIP-7702: eip-7702.md
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#9240 Update EIP-7840: Add BaseFeeUpdateFraction
  EIPS/eip-7840.md
Labels: c-status, t-informational, a-review, s-draft

#9249 Update EIP-7691: clarify parameter handling at the fork boundary
  EIPS/eip-7691.md
Labels: c-update, t-core, w-ci, a-review, s-review

#9248 Update EIP-7702: update `EXTCODE*` opcodes to act on full "delegation designator"
  EIPS/eip-7702.md
Labels: c-update, t-core, a-review, s-review

#9229 Update EIP-7761: Change HASCODE to EXTCODETYPE
  EIPS/eip-7761.md
Labels: c-update, t-core, s-draft

#9251 Update EIP-7607: Add EIP-7823 (Set upper bounds for MODEXP) to proposeed-for-inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9260 Update EIP-7607: Propose EIP-7863 for Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9264 Update EIP-7549: Various spelling fixes of EIP 7549
  EIPS/eip-7549.md
Labels: c-update, t-core, s-review

#9266 Update EIP-1898: Move to Review
  EIPS/eip-1898.md
Labels: c-status, t-interface, a-review, s-review

#9241 Add EIP: Delayed Execution Layer State Root
  EIPS/eip-7862.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9271 Update EIP-7823: Fill in missing sections on EIP-7823
  EIPS/eip-7823.md
Labels: c-update, t-core, s-draft

#9278 Update EIP-7788: fix spelling eip-7788.md
  EIPS/eip-7788.md
Labels: c-update, t-core, a-review, s-draft

#9283 Update EIP-7823: Use decimal numbers for input length.
  EIPS/eip-7823.md
Labels: c-update, t-core, s-draft

#9284 Update EIP-7823: Clarify analysis results values.
  EIPS/eip-7823.md
Labels: c-update, t-core, s-draft

#9272 Update EIP-7823: Move to Review
  EIPS/eip-7823.md
Labels: c-status, t-core, e-review, s-review

#9276 Update EIP-7607: Add EIP-7793 & EIP-7843 to proposed-for-inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9289 Update EIP-7251: Final system contract address
  EIPS/eip-7251.md
Labels: c-update, t-core, a-review, s-review

#9288 Update EIP-7002: Final system contract address
  EIPS/eip-7002.md
Labels: c-update, t-core, a-review, s-review

#9287 Update EIP-2935: Final system contract address
  EIPS/eip-2935.md
Labels: c-update, t-core, a-review, s-review
