Repository ethereum/EIPs, pull requests merged in 2025-03, with the labels that each got.

#9438 Update EIP-7830: Update table to 36M gas
  EIPS/eip-7830.md
Labels: c-update, t-core, s-review

#9439 Update EIP-7251: add fee limit check to fee overpayment section
  EIPS/eip-7251.md
Labels: c-update, t-core

#9427 Update EIP-7002: Add high fees check to Fee overpayment code
  EIPS/eip-7002.md
Labels: c-update, t-core

#9453 Update EIP-6110: add filtering by deposit event sig hash
  EIPS/eip-6110.md
Labels: c-update, t-core

#9391 Update EIP-7873: Creator Contract - revert reason & magic value
  EIPS/eip-7873.md
Labels: c-update, t-core, s-draft

#9458 Update EIP-4750: Move to Review
  EIPS/eip-4750.md
  EIPS/eip-7698.md
Labels: c-status, t-core, a-review, s-review

#9306 docs: fix minor typos in EIP-3855 and EIP-7069
  EIPS/eip-3855.md
  EIPS/eip-7069.md
Labels: c-update, t-core, s-review, s-final

#9421 Update EIP-7709: Replace TBD values for FORK_TIMESTAMP and HISTORY_ST…
  EIPS/eip-7709.md
Labels: c-update, t-core, a-review, s-draft

#9463 Update EIP-7002: Add felix to request eips
  EIPS/eip-7002.md
  EIPS/eip-7251.md
  EIPS/eip-7685.md
Labels: c-update, t-core

#9467 Update EIP-7745: improved row mapping, introduced mapping layers
  EIPS/eip-7745.md
Labels: c-update, t-core, s-draft

#9417 Update EIP-7620/7698/7873 - Defer EOF creation rules to legacy
  EIPS/eip-7620.md
  EIPS/eip-7698.md
  EIPS/eip-7873.md
Labels: c-update, t-core, e-review, s-draft, s-review

#9382 Update EIP-4750: Add Rationale section about "minimal" function type
  EIPS/eip-4750.md
Labels: c-update, t-core, e-review, s-review

#9459 Update EIP-5450: Rename RETURNCONTRACT to RETURNCODE
  EIPS/eip-5450.md
  EIPS/eip-7620.md
  EIPS/eip-7698.md
  EIPS/eip-7873.md
Labels: c-update, t-core, a-review, s-draft, s-review

#9414 Update EIP-7698: fix typo
  EIPS/eip-7698.md
Labels: c-update, t-core, e-review, s-review

#9259 Add EIP: Flow Control Wallet Call Capability
  EIPS/eip-7867.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#8980 Add EIP: GAS2ETH opcode
  EIPS/eip-7791.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9422 Add EIP: ABI attachment in `wallet_sendCalls`
  EIPS/eip-7896.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#9480 Update EIP-7607: Add EIP-7819 to the candidate for inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9290 Update EIP-7723: Update 7723 to include EELS/EEST in CFI
  EIPS/eip-7723.md
Labels: c-status, t-meta, a-review, s-review

#9489 Update EIP-7819: Clarify specifications
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#9478 Update EIP-3540: Clarify restrictions on EXTDELEGATECALL targets
  EIPS/eip-3540.md
  EIPS/eip-7069.md
Labels: c-update, t-core, a-review, s-review

#9491 Update EIP-7607: Add EIP-7688 to the candidate for inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9455 CI: Switch to upload-artifact@v4
  .github/workflows/jekyll.yml
Labels: e-consensus

#9483 Add EIP: Meter Contract Code Size And Increase Limit
  EIPS/eip-7907.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9518 Add EIP: Adaptive mean reversion blob pricing
  EIPS/eip-7915.md
  assets/eip-7915/1.png
  assets/eip-7915/2.png
  assets/eip-7915/3.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9533 Update EIP-6404: fix typos
  EIPS/eip-6404.md
  EIPS/eip-7807.md
Labels: c-update, t-core, a-review, s-draft

#9523 Add EIP: SSZ ProgressiveByteList
  EIPS/eip-7745.md
  EIPS/eip-7916.md
Labels: c-new, c-update, t-core, a-review, s-draft, e-consensus

#9390 Add EIP: Emit log on revert
  EIPS/eip-7889.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9507 Update EIP-7870: Move to Review
  EIPS/eip-7870.md
Labels: c-status, t-informational, e-review, s-review

#9493 Add EIP: eth_config JSON-RPC Method
  EIPS/eip-7910.md
Labels: c-new, t-interface, e-review, s-draft, e-consensus

#9527 Update EIP-663: Move to Review
  EIPS/eip-663.md
Labels: c-status, t-core, e-review, s-review

#9452 Add EIP: Remove Initcode Size Limit
  EIPS/eip-7903.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9479 Update EIP-7607: propose eips 7791 and 7903 for inclusion in osaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, w-ci, a-review, s-draft

#9530 Add EIP: Deterministic proposer lookahead
  EIPS/eip-7917.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9525 Update EIP-7607: Add EIP-7892 to the candidate for inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9534 Update EIP-7762: remove specific fork name
  EIPS/eip-7762.md
Labels: c-update, t-core, s-review

#9519 Update EIP-7607: add eip-7907 to fusaka meta
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9535 Update EIP-7607: Propose EIP-7917 for inclusion in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9532 Update EIP-7607: Add EIP-7915 *Adaptive mean reversion blob pricing* as PFI in Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9437 Update EIP-663: Add rationale for immediate arguments
  EIPS/eip-663.md
Labels: c-update, t-core, s-review

#9536 Update EIP-7607: add EIP-7762 to PFI
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9524 Update EIP-7607: Add "remove bloom filters" (EIP 7668) to PFI Fusaka
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9546 Add EIP: Pureth Meta
  EIPS/eip-7919.md
Labels: c-new, t-meta, w-ci, e-review, s-draft, e-consensus

#9547 Update EIP-7607: Add EIP-7919 to Fusaka PFI
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9432 Add EIP: Uncouple execution payload from beacon block
  EIPS/eip-7898.md
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9543 Add EIP: Blob base fee bounded by execution cost
  EIPS/eip-7918.md
  assets/eip-7918/1.png
Labels: c-new, t-core, e-review, s-draft, e-consensus

#9545 Update EIP-7607: Switch out EIP-7915 in favor of new EIP *Blob base fee bounded by execution cost*
  EIPS/eip-7607.md
Labels: c-update, t-meta, a-review, s-draft

#9460 Update EIP-6110: Spec `parse_deposit_data`
  EIPS/eip-6110.md
Labels: c-update, t-core, a-review

#9553 Update EIP-7918: Added a new figure and shifted the previous to another section.
  EIPS/eip-7918.md
  assets/eip-7918/1.png
  assets/eip-7918/2.png
Labels: c-update, t-core, s-draft

#9555 Update EIP-7623: add extra comment about worst case EL payload sizes
  EIPS/eip-7623.md
Labels: c-update, t-core, a-review

#9451 Update EIP-7607: Propose EIP-7889
  EIPS/eip-7607.md
Labels: c-update, t-meta, w-ci, a-review, s-draft

#9559 Update EIP-7607: ACDE#208 Updates
  EIPS/eip-7607.md
Labels: c-update, t-meta, s-draft

#9542 Update EIP-7916: Remove bound parameter and use constant scaling factor
  EIPS/eip-7916.md
Labels: c-update, t-core, a-review, s-draft

#9561 Update EIP-7873: set tx type to a currently unused (?) first RLP byte
  EIPS/eip-7873.md
Labels: c-update, t-core, a-review, s-draft
