Repository ethereum/EIPs, pull requests merged in 2025-09, with the labels that each got.

#10258 Update EIP-7807: fix/correct style issues
  EIPS/eip-7807.md
Labels: c-update, t-core, a-review, s-draft

#10257 Update EIP-2926: correct grammar and punctuation errors
  EIPS/eip-2926.md
Labels: c-update, t-core, a-review, s-draft

#10266 Update EIP-7997: Improve description
  EIPS/eip-7997.md
Labels: c-update, t-core, s-draft

#10268 Update EIP-7778: improve title
  EIPS/eip-7778.md
Labels: c-update, t-core, s-draft

#10269 Update EIP-7976: Update gas limit assumptions to 45M
  EIPS/eip-7976.md
Labels: c-update, t-core, s-draft

#10274 Update EIP-7636: Fix the typo, stop people sending PRs
  EIPS/eip-7636.md
Labels: c-update, t-networking, s-withdrawn, e-consensus

#10238 Update EIP-7773: Propose EIP-7688 for Glamsterdam
  EIPS/eip-7773.md
Labels: c-update, t-meta, a-review, s-draft

#10276 Update EIP-7976: improve wording
  EIPS/eip-7976.md
  EIPS/eip-7981.md
Labels: c-update, t-core, s-draft

#10278 Update EIP-2780: Move to Draft
  EIPS/eip-2780.md
Labels: c-status, t-core, w-ci, s-draft

#10283 Update EIP-2780: Refresh and modernize
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10284 Update EIP-2780: improve wording and clarify
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10286 Update EIP-7594: update table formatting
  EIPS/eip-7594.md
Labels: c-update, t-core, s-review

#10239 Update EIP-2003: fix broken link
  EIPS/eip-2003.md
Labels: c-update, t-interface, w-ci, a-review, s-stagnant

#10289 Update EIP-2780: Change recommendation to 6k
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10290 Update EIP-2780: Add reference table
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10293 Update EIP-2780: Add solady tx
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10295 Update EIP-2780: Add rational to not price as calldata
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10299 Update EIP-2780: Rephrase
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10300 Update EIP-2780: Formatting
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10304 Update EIP-2780: Add equivalent gas-limit increase
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10292 Update EIP-7748: Update EIP-7748
  EIPS/eip-7748.md
Labels: c-update, t-core, a-review, s-draft

#10240 fix: correct RFC reference from 8170 to 8174 in eip-template.md
  eip-template.md
Labels: c-update, t-process, s-draft, e-consensus

#10201 Add chain-specific subsection
  eip-template.md
Labels: c-update, t-process, s-draft, e-consensus

#10282 Update EIP-7980: fix issues
  EIPS/eip-7980.md
Labels: c-update, t-core, a-review, s-draft

#10317 Update EIP-7932: add missing return statement in sigrecover_precompile function
  EIPS/eip-7932.md
Labels: c-update, t-core, a-review, s-draft

#10313 Update EIP-1702: update broken link
  EIPS/eip-1702.md
Labels: c-update, t-core, a-review, s-stagnant

#10327 Update EIP-6873: update grammar
  EIPS/eip-6873.md
Labels: c-update, t-core, a-review, s-stagnant

#10351 Update EIP-7825: Fix broken table rendering
  assets/eip-7825/analysis.md
Labels: e-consensus

#10345 Update EIP-7825: Move to Review
  EIPS/eip-7825.md
Labels: c-status, t-core, a-review, s-review

#10298 Add EIP: Backward compatible SWAPN, DUPN, EXCHANGE
  EIPS/eip-8024.md
Labels: c-new, t-core, e-review, a-review, s-review, e-consensus

#10342 Update EIP-7934: Move to Review
  EIPS/eip-7934.md
Labels: c-status, t-core, a-review, s-review

#10344 Update EIP-7883: Move to Review
  EIPS/eip-7883.md
Labels: c-status, t-core, a-review, s-review

#10353 Update EIP-7932: Fix broken table rendering
  EIPS/eip-7932.md
Labels: c-update, t-core, a-review, s-draft

#10341 Update EIP-7892: Move to Review
  EIPS/eip-7892.md
Labels: c-status, t-informational, a-review, s-review

#10372 Update EIP-7980: Move to Withdrawn
  EIPS/eip-7980.md
Labels: c-status, t-core, s-withdrawn

#10377 Update EIP-7928: Further clarify reverts
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10393 Update EIP-7928: Clarify self destruct
  EIPS/eip-7928.md
Labels: c-update, t-core, s-draft

#10390 Update EIP-6404: Fix RlpSetCodeTransaction payload type to RlpSetCodeTransactionPayload
  EIPS/eip-6404.md
Labels: c-update, t-core, a-review, s-draft

#10425 Update EIP-7723: Add Alex as author
  EIPS/eip-7723.md
Labels: c-update, t-meta

#10426 Update EIP-7819: Document address collision risks in EIP-7819
  EIPS/eip-7819.md
Labels: c-update, t-core, s-draft

#10430 Update EIP-7979: Update eip-7979.md
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10431 Update EIP-7782: Update authors
  EIPS/eip-7782.md
Labels: c-update, t-core, s-draft

#10432 Update EIP-2780: Update authors
  EIPS/eip-2780.md
Labels: c-update, t-core, s-draft

#10436 Update EIP-7979: Update eip-7979.md
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10437 Update EIP-7979: Update eip-7979.md
  EIPS/eip-7979.md
Labels: c-update, t-core, s-draft

#10413 Update EIP-7825: Move to Last Call
  EIPS/eip-7825.md
Labels: c-status, t-core, a-review

#10415 Update EIP-7917: Move to Last Call
  EIPS/eip-7917.md
Labels: c-status, t-core, a-review

#10381 Update EIP-6789: Use Name Alias
  EIPS/eip-6789.md
  EIPS/eip-7266.md
  EIPS/eip-7791.md
Labels: c-update, t-core, t-interface, e-review, s-draft, s-stagnant

#10356 Update EIP-5593: typo fix in EIPS/eip-5593.md
  EIPS/eip-5593.md
Labels: c-update, t-interface, a-review, s-stagnant
